app/pages/patientdata/patientdata.js

What it says on the tin. @jh-bate review?
For Trello card https://trello.com/c/kt8691fr

make trends the default data view

---

app/pages/patientdata/patientdata.js

Set the desired default options for trends view.
@jh-bate another quick look-see?

set lines off, group, range & avg. on by default for trends

---

app/components/navbar/navbar.js
app/components/navbar/navbar.less

Without understanding the rationale for this change, I picked the largest icon size that seemed reasonable. 
@jebeck @skrugman 
Resolves: https://trello.com/c/Zk0IWYcw

Makes the navbar icons bigger.

---

app/components/chart/footer.js
app/core/less/buttons.less
app/core/less/variables.less
app/pages/patientdata/patientdata.less

@jebeck @skrugman 
The gray bar has been removed from footer in the patient data chart. 
The Refresh link is now a button (using the 'teritary' btn style from the core styles). Let me know if you'd prefer something different. The primary button style seemed too distracting and the secondary was too light to be noticeable. 
The links on the right side of the footer are now dark gray and an underline is displayed on hover. 
Resolves: https://trello.com/c/EJL3rmil

Removes the gray bar and makes the refresh link a button.

---

app/components/navbar/navbar.less

@jebeck 
This PR fixes that pesky Firefox alignment issue. I've tested this in Chrome, Firefox, and Safari. 
Resolves: https://trello.com/c/S9d6glhK

Fixes vertical alignment of navbar icons in Firefox.

---

app/pages/patients/patients.js

@jebeck 
This changes just removes a line of text from the welcome flow that didn't make sense anymore given recent layout changes.
Resolves: https://trello.com/c/vLKsJmWe

Removes 'create later' text from welcome flow.

---

README.md

a quick note on how to skip verification for a new user if running locally. @jebeck ??

Add note on running local

---

app/app.js

@ursooperduper this resolves issue seen in https://trello.com/c/Pub5ZwkN/26-ui-debt-if-there-is-one-account-user-should-be-taken-directly-to-data-not-care-team

reset state on logout so that login

---

app/components/chart/modal.js
app/components/chart/settings.js
app/components/chart/weekly.js
package.json

Shouldn't need much review, more approval of language from @brandonarbiter and @HowardLook

remove language that asks for simultaneous uploads in order to see all data

---

app/components/chart/modal.js
package.json

What it says on the tin.
After https://github.com/tidepool-org/tideline/pull/204 is merged and tagged on master, I'll also rev the tideline version here, so don't merge this PR until that's done.
Ping @jh-bate

pass bgUnits to modal-day view

---

README.md

@jebeck based on feedback from opensource dev's have tweaked the readme

add running local to quick start details

---

.jshintrc
README.md
config.app.js
package.json
webpack.config.js

@jebeck -- I believe this resolves the problem we talked about. At least it seems to on my machine.

Remove the remnants of envify and properly load env vars in webpack.

---

app/components/messages/__tests__/message-test.js
package.json

@jebeck here is a test for the message edit fix

add message test for edits

---

app/app.js

add 'beta' after version number

---

package.json

bump platform-client version for addition of GUIDs

---

app/core/personutils.js
app/pages/patient/patientinfo.js
app/pages/patient/patientinfo.less
app/pages/patientnew/patientnew.js
test/unit/components/chart/settings.test.js
test/unit/pages/patient/patientinfo.test.js
test/unit/pages/patientdata.test.js
test/unit/pages/patientnew.test.js
test/unit/utils/personutils.test.js
test/utils/rewireModule.js

I've examined both patientinfo and patientnew and made the signature and behaviour around validation consistent. This means the validateForm function now sits in personUtils.
I've also tested visually in browser.
Notable changes/things to look at:
- Like PatientNew, PatientInfo shows all error messages on screen with red style formatting
- Error messages are consistent across both modules - but may want updating - not sure on what wording is preferred
- Testing of validation has moved into personUtils

Gordyd refactor patient info validation

---

app/pages/signup/signup.js
test/unit/pages/signup.test.js

@jebeck If you could take an initial look at this please. FYI I want to do a full test on devel so I can test with the invite process / emails also.
Details in linked [trello card] (https://trello.com/c/5bFvHhPQ/74-bug-waitlist-when-a-new-user-is-invited-to-join-blip-via-an-existing-user-they-should-bypass-the-waitlist)

Jhbate fix signup

---

app/components/chart/basics.js
app/components/chart/daily.js
app/components/chart/footer.js
app/components/chart/header.js
app/components/chart/index.js
app/components/chart/modal.js
app/components/chart/modalsubnav.js
app/components/chart/settings.js
app/components/chart/weekly.js
app/components/invitation/invitation.js
app/components/modaloverlay/modaloverlay.js
app/components/navbar/navbar.js
app/components/navbarpatientcard/navbarpatientcard.js
app/components/patientcard/patientcard.js
app/components/peoplelist/peoplelist.js
app/components/personcard/personcard.js
app/components/waitlist/waitlist.js
app/pages/patient/patientteam.js
app/pages/patientdata/patientdata.js
app/pages/patientdata/patientdata.less
app/pages/patients/patients.js
package.json
test/unit/components/chart/header.test.js
test/unit/pages/patientdata.test.js

Ping @GordyD or @jh-bate for review.
Depends on [tideline 237](https://github.com/tidepool-org/tideline/pull/237)

MVP of "The Basics"

---

app/components/app/app.js

Prevent crash when trying to logout when logout precedes attempt to update patientData.
Plz review @GordyD and let's discuss tomorrow - this is an illustratively nasty bug not irrelevant to all the things we've been discussing.

fix for basics logout bug

---

app/components/browserwarningoverlay/browserwarningoverlay.js
config.app.js

@jh-bate @GordyD Not sure if this interferes with any other changes, but these changes will need to be merged into master at some point.

Final changes for new environment

---

app/components/app/app.js
app/core/api.js
app/core/core.less
index.html
package.json
webpack.config.js

Two bugfixes here:
- JavaScript error was happening when trying to change password from /profile (turned out to be an issue in a small change made to the API wrapper)
- fix the fact that fonts wouldn't load when navigating directly to a nested URL (like /patients/:id/data) or refreshing on such

router replacement bugfixes

---

app/pages/patientdata/patientdata.js

bugfix for view link in center header

---

app/core/actionhandlers.js
app/core/personutils.js
app/userMessages.js
package.json

WIP updates

---

app/core/utils.js
app/pages/emailverification/emailverification.js
app/pages/login/login.js
app/pages/passwordreset/confirm.js
app/pages/passwordreset/request.js
app/pages/patientdata/patientdata.js
app/pages/patientnew/patientnew.js
app/pages/patients/patients.js
app/pages/profile/profile.js
app/pages/signup/signup.js
test/unit/pages/emailverification.test.js
test/unit/pages/login.test.js
test/unit/pages/passwordreset/confirm.test.js
test/unit/pages/passwordreset/request.test.js
test/unit/pages/patientdata.test.js
test/unit/pages/patientnew.test.js
test/unit/pages/patients.test.js
test/unit/pages/profile.test.js
test/unit/pages/signup.test.js

Also a small bugfix. @GordyD maybe just give this a quick glance and merge? I rebased on top of the new gordyd/redux.

finsh mapStateToProps tests

---

package.json

See release notes for:
- tideline [v0.4.12](https://github.com/tidepool-org/tideline/releases/tag/v0.4.12)
- platform-client [v0.23.1](https://github.com/tidepool-org/platform-client/releases/tag/v0.23.1)

rev dependencies for bugfixes: tideline & platform-client

---

package.json

For more information see: https://github.com/webpack/webpack/issues/91 (at bottomof of page)
@jebeck

Update Webpack dependency to resolve issue

---

app/redux/constants/errorMessages.js

I agree to the terms of Tidepool Project’s Volunteer/Contributor License Agreement v1.0 as it exists at http://tidepool-org.github.io/TidepoolVCLA.pdf on June 9, 2016.

Fix typos in errorMessages.js

---

app/pages/verificationwithpassword/verificationwithpassword.js
app/pages/verificationwithpassword/verificationwithpassword.less
app/redux/utils/trackingMiddleware.js
test/unit/pages/verificationwithpassword.test.js
test/unit/redux/actions/async.test.js

Styling fixes on in-clinic created account verification and addition of a few metrics surrounding that process.

Post VCA Additions

---

README.md
package.json

change npm run karma-watch command to npm run test-watch

---

.travis.yml

Will self-merge if build passes. Since we've updated Bob to 3.x npm we need to be building with that on Travis.

add to before_install to get 3.x version of npm

---

app/components/chart/modal.js
app/pages/patientdata/patientdata.js
package.json

What it says on the tin. Required for [viz #13](https://github.com/tidepool-org/viz/pull/13).

pass through currentPatientInViewId

---

package.json

rev @tidepool/viz version for CGM in trends time binning fix

---

package.json

Paging @krystophv for a quick John Hancock.

rev tideline version for Animas bgTarget.range conversion

---

app/components/waitlist/waitlist.js

@jebeck @jh-bate @krystophv: for your review, when you have time. Thanks! (Is there anyone else I should ping on this? I looked at #324 for reference.)

Update Typeform link

---

app/components/waitlist/waitlist.js
package.json

Sorry, @jebeck! Brandon did have the right URL, so I'm just reverting back to it here.

Revert "Update Typeform link"

---

package.json

What it says on the tin, again.

rev @tidepool/viz version for small device settings style fix

---

package.json

rev @tidepool/viz version to fix missing active text on Tandem device settings

---

package.json

@jh-bate any chance you could sign off on this tonight?
If not, then please @hntrdglss or @krystophv first thing Tuesday...
Companion PR to [viz #32](https://github.com/tidepool-org/viz/pull/32).

rev @tidepool/viz for MedT 'active at upload' regression fix

---

package.json

rev @tidepool/viz for regression in bgTarget data

---

package.json
webpack.config.js

size was too small and causing the image to not load so simply increased to a commonly referred size

Fix image path

---

app/components/patientcard/patientcard.js
app/components/patientcard/patientcard.less
package.json

Fixes some CSS issues Nick observed when testing #352.

Fix some CSS issues on Patient Card

---

app/pages/patient/patient.js
app/pages/patient/patientteam.js
package.json
test/unit/pages/patient/patient.test.js
test/unit/pages/patient/patientteam.test.js

@hntrdglss could you review please? See [trello card](https://trello.com/c/4rfefQaP) for details. I had to do a little refactoring in order to test but the actual code change itself was minimal.

Upload default on

---

app/pages/patient/patientteam.js
package.json
test/unit/pages/patient/patientteam.test.js

@hntrdglss if you could have a look at this. Brandon want the metrics text changed and also another metric measured as well. All tagged and ready to go.
See [trello card](https://trello.com/c/4rfefQaP) for updated details  specifically the updated "Events for KissMetrics" section.

updates and tests for new metrics

---

app/components/chart/basics.js
package.json

See https://github.com/tidepool-org/tideline/pull/292 for details.  @jebeck @hntrdglss

use basics norgys updates

---

package.json

@hntrdglss and the corresponding PR for https://github.com/tidepool-org/tideline/pull/293

Basics norgys cleanup

---

package.json

tideline version bump - @jebeck @hntrdglss

Carbs per day

---

package.json

@jebeck version bump for new tideline update

Basics alignment

---

app/components/chart/footer.js

Just discovered this commit was unpushed from #375. Since it's very very tiny (and not targeting a protected branch) I'm going to self-merge @krystophv @hntrdglss

change 'Range & Average' to just 'Range' in footer checkboxes

---

app/components/chart/modal.js

What it says on the tin. Goes with [viz #43](https://github.com/tidepool-org/viz/pull/43).

update to use combined cbg slice segment & smbg range hover info component

---

package.json

Custom target preparation work done in other repos. see: https://trello.com/c/Bkjjikon
https://github.com/tidepool-org/tideline/pull/300 and
https://github.com/tidepool-org/viz/pull/41

Custom target dependency updates

---

app/components/chart/modal.js

Small cleanup parallel to [viz #48](https://github.com/tidepool-org/viz/pull/48)
Ping @hntrdglss or @krystophv

day to date renaming

---

app/components/chart/modal.js

Goes with [viz #49](https://github.com/tidepool-org/viz/pull/49).

CGM Trends date label on hover of a CGM trace

---

package.json

Corresponds to [this Tideline pull request](https://github.com/tidepool-org/tideline/pull/301).

Update Tideline to v0.5.22

---

package.json

Corresponds to [this Tideline pull request](https://github.com/tidepool-org/tideline/pull/302).

Update Tideline to v0.5.23

---

app/pages/patientdata/patientdata.js
package.json

This should be the last of the substantive changes for the updates to Trends view. There will also be a (larger) companion viz PR.

Trends BGM changes

---

app/core/utils.js
app/pages/patient/patientsettings.js
app/pages/patientdata/patientdata.js
package.json

Wires up `Tideline` and `Viz` with new customized blood glucose target range settings.
@krystophv and/or @jh-bate, once approved, I'll merge this into the pre-existing #399 pull request, then deploying that to `dev` and `stg` for testing.

Integrate CBGTR into Tideline/Viz

---

app/core/api.js
package.json

@jebeck the corresponding PR that is associated with https://github.com/tidepool-org/platform-client/pull/75 and the card https://trello.com/c/VXQ5L102

Clinical load pwd

---

app/core/api.js
package.json

@jebeck I believe this is all we need in this scenario. Local testing for me was good. Hoping that my comments in code code make it more understandable as we spoke about??

filter out those accounts that aren't viewable

---

app/config.js
test/unit/app/app.test.js
test/unit/components/inputgroup.test.js
test/unit/components/invitation.test.js
test/unit/components/loginlogo.test.js
test/unit/components/loginnav.test.js
test/unit/components/logoutoverlay.test.js
test/unit/components/mailto.test.js
test/unit/components/messages/messageform.test.js
test/unit/components/messages/messages.test.js
test/unit/components/modaloverlay.test.js
test/unit/components/navbar.test.js
test/unit/pages/login.test.js
test/unit/pages/passwordreset/confirm.test.js
test/unit/pages/passwordreset/request.test.js
test/unit/pages/patientdata.test.js
test/unit/pages/patientnew.test.js
test/unit/pages/patients.test.js
test/unit/pages/userprofile.test.js

@jebeck the cleanup we talked about based on updates made during T&C updates 
cc @pazaan

Test config cleanup

---

app/components/chart/settings.js
package.json

and this @jebeck 
https://trello.com/c/OXG8jZnU 
and https://github.com/tidepool-org/viz/pull/68

Copy settings metric

---

package.json

OK, if there's no other changes required since @darinkrauss's sign-up metrics are working, then this is the only metrics fix that needs to go out, right?

Copy settings metrics fix

---

app/components/printheader/printheader.js
app/components/printview/settingsprintview.js
package.json
test/unit/components/settingsprintview.test.js

@krystophv could you take a look at this please. It resolves the issue seen here https://trello.com/c/Q15cxITp which was the result of a merge that I made.
I have added a test that now asserts that the header is present and will fail if another issue happens in the same manner (comment out the renderHeader call and then the test will fail)

fix merge issue and add tests so it won't occur again

---

app/core/api.js
app/core/utils.js
app/pages/patientdata/patientdata.js
app/redux/actions/async.js
docs/Architecture.md
package.json
test/unit/redux/actions/async.test.js
test/unit/utils/utils.test.js
yarn.lock

@jebeck @krystophv @jh-bate What it says on the tin. Requires update to `tide-whisperer` to function correctly.
https://trello.com/c/3uyQGXo9

Pass through carelink parameter on URL to patient data API

---

test/unit/components/datasources.test.js
test/unit/pages/patient/patientinfo.test.js
test/unit/redux/actions/async.test.js
test/unit/redux/actions/sync.test.js
test/unit/redux/reducers/working.test.js
yarn.lock

@darinkrauss  I could easily keep adding tests but here is a good start

Data sources tests

---

package.json
yarn.lock

Pulling in new versions of the `tideline` and `viz` repos.
See https://trello.com/c/p7L3RoNn for details

Fix for displaying inaccurate 'High' and 'Low' smbg values

---

app/components/dexcombanner/dexcombanner.js
package.json
test/unit/components/datasources.test.js
test/unit/components/dexcombanner.test.js
yarn.lock

Updated copy and metrics for the dexcom banner, plus enabling the 'Get Started' button.
See https://trello.com/c/1H3rwUBF for details.

Dexcom banner revisions

---

package.json
yarn.lock

Accidentally pushed a prod release with the wrong viz version for the print views.  Simply reverting to the correct viz version

Print view hotfix

---

package.json
yarn.lock

Forgot to create production tags before merging branch to master.  Need to do it in separate PR now.

Production tags for Libre fixes

---

app/pages/emailverification/emailverification.js
package.json

What it says.  See https://trello.com/c/67H081EV for details

Split email verification address to it's own line

---

package.json
server.js
yarn.lock

To follow security best practices (as per
https://expressjs.com/en/advanced/best-practice-security.html), use the
`helmet` package to prevent such things as click-jacking,
MITM attacks, XSS attacks, etc

Use helmet to add web security

---

app/pages/patientdata/patientdata.js

See https://trello.com/c/h1QqftJ6 for details.
Related PRs:
tidepool-org/tideline#334
tidepool-org/viz#103

Add pumpSettings data to Daily print view for per-device basal labels

---

package.json
yarn.lock

Adresses https://nvd.nist.gov/vuln/detail/CVE-2017-18214

Update moment lib to address regex dos vulnerability

---

app/core/constants.js
package.json
test/unit/app/core/constants.test.js

See: https://trello.com/c/LWBzvGMr

Add AADE Foundation to Tidepool Big Data Donation Project Nonprofit Partner List

---

app/pages/patientdata/patientdata.js
package.json
yarn.lock

See https://trello.com/c/nvJocRRd for details.
Related PRs:
tidepool-org/viz#108
tidepool-org/tideline#342

Time in Auto Mode widget

---

package.json
yarn.lock

https://trello.com/c/EJQHZnyv
Implements tidepool-org/tideline#343

Bg defaults daily ticks regression fix

---

app/core/api.js
app/pages/share/share.js
package.json
test/unit/pages/share.test.js
yarn.lock

See https://trello.com/c/4lnTETQg for details

Fix login and share page errors when a shared account is missing a profile

---

app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js
yarn.lock

See https://trello.com/c/UCwOXfD7 for details.
Related PRs:
tidepool-org/tideline#344
tidepool-org/viz#109

Automated basal suspend fix

---

app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js
yarn.lock

See https://trello.com/c/Jpi5YurW for details.
Related PR:
tidepool-org/tideline#345

Fix issue where weekly chart date was set to the next day when switching from daily

---

package.json
yarn.lock

See https://trello.com/c/NFKNjxyT for details.
Related PRs:
https://github.com/tidepool-org/viz/pull/111
https://github.com/tidepool-org/tideline/pull/347

Add Basal:Bolus ratio to basics view for Automated Basal devices

---

package.json
yarn.lock

See https://trello.com/c/OKhvKFnN for details

Display date range when using browser print functionality

---

package.json
yarn.lock

Auto mode target fix
Trello: https://trello.com/c/krrF6CmW
Viz PR: https://github.com/tidepool-org/viz/pull/113

Auto target

---

package.json
yarn.lock

See https://trello.com/c/4vRWbVp3 for details.
Related PR:
tidepool-org/viz#115

Daily print view bg tick formatting regression

---

package.json
yarn.lock

Trello Card: https://trello.com/c/u8Fid7Hi/439-600-series-bug-remove-calibration-yes-annotation
viz PR: https://github.com/tidepool-org/viz/pull/116

Calibration message adjustments

---

package.json
yarn.lock

viz PR: https://github.com/tidepool-org/viz/pull/117
Trello: https://trello.com/c/9ET8Bmh5/146-setting-6-series-bolus-increment-to-025-causes-loss-of-precision-due-to-rounding

Bolus rounding

---

app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js
yarn.lock

See https://trello.com/c/DVZk4lg8 for details
Related PR:
tidepool-org/tideline#350

Allow care team members to assign infusion site change rule

---

package.json
yarn.lock

See https://trello.com/c/uzlypSjy for details.
Related PRs
---
tidepool-org/viz#118
tidepool-org/tideline#353

Basics page shows incorrect suspend count

---

package.json
server.js

See https://trello.com/c/GbuHSNpr for details.

Add CSP worker-src fallback for older browsers

---

app/components/chart/weekly.js
package.json
yarn.lock

See https://trello.com/c/VNKOkCOY for details.
Related PRs:
---
tidepool-org/viz#119
tidepool-org/tideline#354

Fix missing device id error

---

package.json
yarn.lock

See https://trello.com/c/5stilew8 for details.
Related PR: 
tidepool-org/tideline#355

Fix timechange error

---

README.md

Correcting the version number of NPM that was incorrect.

Correcting incorrecting version number

---

package.json
yarn.lock

viz: https://github.com/tidepool-org/viz/pull/121
tideline: https://github.com/tidepool-org/tideline/pull/358
trello: https://trello.com/c/wZk0cMNU

Auto suspend

---

package.json
yarn.lock

Release contains PLGS markers.
trello: https://trello.com/c/wZk0cMNU
Released in concert with:
viz: https://github.com/tidepool-org/viz/pull/122
tideline: https://github.com/tidepool-org/tideline/pull/359
Note: will receive final dependency versions post PR approval.

Release 1.13.0

---

app/core/utils.js
app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js
test/unit/utils/utils.test.js
yarn.lock

Release 1.14.0

---

package.json
yarn.lock

Trello: https://trello.com/c/5arkE8Ra
viz: https://github.com/tidepool-org/viz/pull/125
tideline: https://github.com/tidepool-org/tideline/pull/361

Suspend duration fix

---

app/pages/app/app.js
app/pages/app/app.less
app/pages/emailverification/emailverification.less
app/pages/signup/signup.less
package.json

Hotfix 1.14.1 has been deployed and merged to master.  https://trello.com/c/QMflDPe8
Need to merge here as well.

Merge hotfix 1.14.1 into release 1.15.0

---

app/pages/patientdata/patientdata.js
test/unit/pages/patientdata.test.js

See https://trello.com/c/pEdbpu6t for details
Fixes #532

Fix out of range indexing error in patient data preprocessing

---

app/pages/patient/patientinfo.js
test/unit/pages/patient/patientinfo.test.js

Temporarily disabling export UI rendering for further feature work in future release.

Disable export UI rendering

---

app/components/chart/basics.js
app/components/chart/stats.js
test/unit/components/chart/basics.test.js
test/unit/components/chart/stats.test.js

See https://trello.com/c/8w4zfRPq for details.
Goes with tidepool-org/viz#133

Persist Average Daily Dose input between data views

---

app/components/peopletable/peopletable.less
app/pages/patients/patients.less
package.json

See https://trello.com/c/EMApNn9D for details.

Regression: Scrollbar missing from VCA patients list

---

package.json
yarn.lock

See https://trello.com/c/YcHZj4dI for details
Goes with:
tidepool-org/viz#138

Tidepool web crashes when rendering SD stat widget when SD > mean

---

package.json
yarn.lock

See https://trello.com/c/EnbpV4VY for details.
See also tidepool-org/viz#139

Fix Y-Axis bg tick overlaps on Trends view

---

app/components/chart/stats.js
app/pages/patientdata/patientdata.js
package.json
test/unit/components/chart/stats.test.js
test/unit/pages/patientdata.test.js
yarn.lock

See https://trello.com/c/zCsP7dCr for details.
Goes with tidepool-org/viz#143

Print view stat calculations

---

app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js
yarn.lock

See https://trello.com/c/doJpZONa for details.
Goes with tidepool-org/viz#142

Print food carbs

---

app/components/browserwarning/browserwarning.js
test/unit/components/browserwarning.test.js

Adds metrics that were overlooked for https://trello.com/c/hZi8zF50

add forgotten metrics

---

package.json
yarn.lock

https://trello.com/c/8y1XNWwZ/690-nan-on-cannula-prime-or-site-changes
https://github.com/tidepool-org/tideline/pull/373

bump tideline

---

locales/en/translation.json
locales/fr/translation.json

https://trello.com/c/T8eld2pY/708-spacing-of-text-in-user-profile-when-trying-to-edit-information-is-off

add space when edit user account

---

config.app.js
package.json
server.js

See https://trello.com/c/2JUwzDOg for details

Common request hosts

---

app/pages/patient/patientinfo.less

Updated text bio bug where a user would put in a long string with no spaces, now properly wraps 
https://trello.com/c/tvrji3bT/576-long-profile-text-bug

Updated text fix v1

---

package.json
yarn.lock

See [WEB-165] for details
Related PRs
---
tidepool-org/viz#158
[WEB-165]: https://tidepool.atlassian.net/browse/WEB-165

Tooltip hover fix [WEB-165]

---

app/pages/patient/patientinfo.less

Fixed version of the long text wrapping bug
https://tidepool.atlassian.net/browse/WEB-36?atlOrigin=eyJpIjoiMTY1MTI0ZjAyNmFhNDUxYWIxN2NjMGQ1Yzk4YmVkMjciLCJwIjoiaiJ9

Long Bio text bug w/ fix

---

app/core/validation.js

https://trello.com/c/L4lPx9V1
doesnt allow users to make a diagnosis date earlier than birthdate

birthdate < diagnosis date bug 

---

app/components/peopletable/peopletable.js

fixes the bug where a clinician accepts an invitation but the new user doesn't appear on the userlist

fixing clinician update

---

app/core/validation.js
app/core/validation/errors.js
app/pages/patientnew/patientnew.js

verify that if a user is making an account for themselves (aka they agreed that they are at least 13) then their age cannot be less than 13

under13 verification 

---

Dockerfile
package.json

Part of [WEB-210]
To be used alongside tidepool-org/development#24
[WEB-210]: https://tidepool.atlassian.net/browse/WEB-210

Updates to run in local Tilt/K8s environment [WEB-210]

---

app/pages/patientdata/patientdata.js

[WEB-257] updated print view to include 15 days
[WEB-257]: https://tidepool.atlassian.net/browse/WEB-257

updated print view to include 15 days (WEB-257)

---

app/components/uploaderbutton/uploaderbutton.js
app/components/uploadlaunchoverlay/uploadlaunchoverlay.js
app/core/utils.js
test/unit/utils/utils.test.js

To address [WEB-576]
[WEB-576]: https://tidepool.atlassian.net/browse/WEB-576

Renaming `chrome-uploader` to `uploader` [WEB-576]

---

app/components/addemailbanner/addemailbanner.js
app/components/addemailbanner/addemailbanner.less
app/components/addemailbanner/index.js
app/core/api.js
app/core/personutils.js
app/pages/app/app.js
app/pages/patient/patientinfo.js
app/pages/patient/patientinfo.less
app/style.less
test/unit/app/app.test.js
test/unit/app/core/api.test.js
test/unit/components/addemailbanner.test.js
test/unit/pages/patient/patientinfo.test.js
test/unit/utils/personutils.test.js

Addresses [WEB-29]
[WEB-29]: https://tidepool.atlassian.net/browse/WEB-29

Allow adding email address in Web [WEB-29]

---

package.json

Release for [WEB-257] and [WEB-3]
[WEB-257]: https://tidepool.atlassian.net/browse/WEB-257
[WEB-3]: https://tidepool.atlassian.net/browse/WEB-3

Release 1.28.0 to develop

---

app/pages/patient/patientinfo.js
test/unit/pages/patient/patientinfo.test.js

Commenting out export UI to allow release to progress

WEB-34 Remove export

---

app/components/chart/basics.js
app/core/data.js
app/pages/patientdata/patientdata.js
app/redux/actions/worker.js
app/redux/constants/actionWorkingMap.js
app/redux/reducers/working.js
app/worker/PDFWorker.js
app/worker/index.js
package.json
test/unit/app/core/data.test.js
test/unit/pages/patientdata.test.js
test/unit/redux/actions/worker.test.js
test/unit/redux/reducers/working.test.js
test/unit/worker/PDFWorker.test.js
yarn.lock

Addresses [WEB-25]
Related PR: tidepool-org/viz#179
[WEB-25]: https://tidepool.atlassian.net/browse/WEB-25

Generate PDFs with data from new worker [WEB-25]

---

package.json
yarn.lock

Fixes [WEB-709]
[WEB-709]: https://tidepool.atlassian.net/browse/WEB-709

[WEB-709] CSP validation fix

---

app/core/api.js
app/rollbar.js
config.app.js
config.webpack.js
karma.conf.js
package.json
server.js
test/unit/app/core/api.test.js
webpack.config.js
yarn.lock

See [WEB-75] for details
[WEB-75]: https://tidepool.atlassian.net/browse/WEB-75

[WEB-75] Add rollbar

---

app/pages/patientdata/patientdata.js
app/redux/actions/worker.js
app/redux/reducers/data.js
app/worker/DataWorker.js
package.json
test/unit/redux/actions/worker.test.js
test/unit/redux/reducers/data.test.js
test/unit/worker/DataWorker.test.js
yarn.lock

See [WEB-732] for details
Goes with tidepool-org/viz#185
[WEB-732]: https://tidepool.atlassian.net/browse/WEB-732

[WEB-732] Make data available in browser console or via download for debugging

---

package.json
server.js

See [WEB-735] for details
[WEB-735]: https://tidepool.atlassian.net/browse/WEB-735

[WEB-735] Hotfix: Update CSP imgSrc policy to allow ZD images to load

---

app/core/constants.js
test/unit/app/core/constants.test.js

See [WEB-736] for details
[WEB-736]: https://tidepool.atlassian.net/browse/WEB-736

[WEB-736] updated AADE to ADCES

---

package.json
yarn.lock

Fixes [WEB-743]
Related PR: tidepool-org/viz#187
[WEB-743]: https://tidepool.atlassian.net/browse/WEB-743

[WEB-743] Fix suppressed basal rendering

---

app/redux/actions/async.js
test/unit/redux/actions/async.test.js

[WEB-744] Fetch initial patient data based on the most recent renderable diabetes datum

---

app/pages/patient/patientinfo.js
test/unit/pages/patient/patientinfo.test.js

With Export service updated, we can now re-enable the export UI for [WEB-34]
[WEB-34]: https://tidepool.atlassian.net/browse/WEB-34

WEB-34 enable export UI

---

package.json
yarn.lock

See [WEB-750] for details
Goes with tidepool-org/viz#188
[WEB-750]: https://tidepool.atlassian.net/browse/WEB-750

[WEB-750] Fix basics copy-to-text empty calibration values

---

app/components/chart/bgLog.js
package.json

See [WEB-751] for details
[WEB-751]: https://tidepool.atlassian.net/browse/WEB-751

[WEB-751] Ensure BG Log 'showingValues' state persists when navigating

---

app/components/elements/TextInput.js
package.json
stories/TextInput.stories.js
yarn.lock

See [WEB-582] for details
[WEB-582]: https://tidepool.atlassian.net/browse/WEB-582

[WEB-582] text input

---

app/components/elements/Button.js
app/components/elements/Dialog.js
app/components/elements/FontStyles.js
app/components/elements/IconButton.js
app/components/elements/Popover.js
app/themes/baseTheme.js
package.json
stories/Popover.stories.js
yarn.lock

See [WEB-590]
[WEB-590]: https://tidepool.atlassian.net/browse/WEB-590

[WEB-590] Popover Component

---

app/components/elements/DatePicker.js
app/components/elements/DateRangePicker.js

I noticed a couple of issues while using the Date Pickers storybook.  The date range picker wasn't working correctly due to a typo (`onDateChange` needed to be `onDatesChange`) and the passed-in `onDate(s)Change` handlers weren't firing due to the way I'd implemented them.

Date picker fixes

---

app/components/elements/TextInput.js
stories/TextInput.stories.js

See [WEB-587] for details
Borrows icon placement logic from `Select`
[WEB-587]: https://tidepool.atlassian.net/browse/WEB-587

[WEB-587] search input

---

app/components/datasources/datasources.js
app/components/datasources/datasources.less

Added a note for international Dexcom users who try to link their clarity account

[WEB-754] Added warning for international Dexcom users

---

app/components/elements/RadioGroup.js
app/themes/base/inputs.js
app/themes/baseTheme.js
stories/RadioGroup.stories.js

See [WEB-588] for details
[WEB-588]: https://tidepool.atlassian.net/browse/WEB-588

[WEB-588] Radio component

---

app/themes/base/buttons.js
stories/Button.stories.js

See [WEB-756]
[WEB-756]: https://tidepool.atlassian.net/browse/WEB-756

[WEB-756] Add 'text' button variant

---

app/pages/patientdata/patientdata.js
app/redux/actions/async.js
package.json
test/unit/pages/patientdata.test.js

Hotfix -- see [WEB-780]
[WEB-780]: https://tidepool.atlassian.net/browse/WEB-780

[WEB-780] Add 'startDate' param of 6 months ago when querying the backend for the latest diabetes datums

---

app/pages/patientdata/patientdata.js
app/redux/actions/async.js
package.json
test/unit/pages/patientdata.test.js

Merges hotfix [WEB-780] into release
[WEB-780]: https://tidepool.atlassian.net/browse/WEB-780

[WEB-780] Merge query hotfix into upcoming release

---

package.json
yarn.lock

See [WEB-787] for details
Related PR: tidepool-org/viz#195
[WEB-787]: https://tidepool.atlassian.net/browse/WEB-787

[WEB-787] Hotfix: extended bolus validation fix

---

app/pages/patient/patientinfo.js
test/unit/pages/patient/patientinfo.test.js

Pull request to get [WEB-767] into the current release branch. (already reviewed and merged into `develop`)
[WEB-767]: https://tidepool.atlassian.net/browse/WEB-767

[WEB-767] only allow clinics to edit MRN fields

---

package.json
yarn.lock

Closes [WEB-787] hotfix release
[WEB-787]: https://tidepool.atlassian.net/browse/WEB-787

Merge [WEB-787] extended bolus validation fix to release-1.32.0

---

app/components/elements/Checkbox.js

Small CSS update to styled-component, missed when updating to PR recommendations before merging -- https://tidepool.atlassian.net/browse/WEB-593?atlOrigin=eyJpIjoiNTgzMjJkODdiNGExNDJjM2JkMDVkMDQwMmU4ODRhOTEiLCJwIjoiaiJ9

[WEB-593] Checkbox

---

package.json
yarn.lock

See [WEB-791] for details.
Related PR: tidepool-org/viz#198
[WEB-791]: https://tidepool.atlassian.net/browse/WEB-791

[WEB-791] Add GMI to basics view PDF

---

app/pages/patient/patientinfo.js
test/unit/pages/patient/patientinfo.test.js

For [WEB-34], to remove currently blocked export feature from current release branch. This is a well worn path. 
[WEB-34]: https://tidepool.atlassian.net/browse/WEB-34

[WEB-34] remove export rendering (from 1.32.0)

---

app/components/elements/Avatar.js
app/components/elements/Pagination.js
app/components/elements/Select.js
app/components/elements/TabGroup.js
app/components/elements/Table.js
app/components/elements/TextInput.js
app/themes/base/inputs.js
app/themes/base/tables.js
app/themes/baseTheme.js
app/themes/colorPalette.js
stories/Avatar.stories.js
stories/Pagination.stories.js
stories/Select.stories.js
stories/Table.stories.js
stories/TextInput.stories.js

See [WEB-585] for details.
Storybook example includes table sorting, filtering by columns by nested data (such as patient name and email), ability to specify render functions for any column, sticky header and row hover options.
Also includes some consolidation of the Select and TextInput component styles, and some fixes to allow easier positioning of them via rebass props.
[WEB-585]: https://tidepool.atlassian.net/browse/WEB-585

[WEB-585] Table Component

---

app/components/elements/Dialog.js
app/components/elements/Popover.js
app/themes/base/buttons.js
app/themes/baseTheme.js
stories/Button.stories.js
stories/Dialog.stories.js
stories/Popover.stories.js
stories/Table.stories.js

See [WEB-766]
Had to make slight mods to a few of the components involved in piecing the storybook example together.  The commit messages should outline the changes pretty well.
[WEB-766]: https://tidepool.atlassian.net/browse/WEB-766

[WEB-766] Radio filter menu

---

app/components/peopletable/peopletable.js

See [WEB-771] for details
[WEB-771]: https://tidepool.atlassian.net/browse/WEB-771

[WEB-771] Patient list order fix

---

app/components/elements/TextInput.js
stories/TextInput.stories.js

Added a simple number input storybook example that uses knobs for min, max, and step properties.

[WEB-745] Number input

---

app/components/elements/Checkbox.js
app/components/elements/FontStyles.js
app/components/elements/RadioGroup.js
app/components/elements/Select.js
app/components/elements/TextInput.js
app/themes/base/inputs.js
stories/Checkbox.stories.js
stories/RadioGroup.stories.js
stories/Select.stories.js
stories/TextInput.stories.js

[WEB-764] input form validation error state styling
[WEB-764]: https://tidepool.atlassian.net/browse/WEB-764

[WEB-764] validation

---

app/redux/actions/async.js
test/unit/redux/actions/async.test.js

See my 1st comment on [WEB-810] for details of the actual issue.
I've gone ahead with the solution I thought would work there, which is basically setting the endDate param for the query for future datums, which eliminates future datums, while assuring us that we use an appropriate date range for the non-excluded, non-future data.
One unfortunate repercussion of this is that since we no longer get future datums in the initial datum query result, we don't have anything to report to rollbar.  The only way to still be able to pass this info would be a separate call to the database to get future datums, and, if present in a user's account, dispatch the info to rollbar.
This seemed to be out-of-place to me, though.  If you have a sensible way for us to surface these situations, I'd love to hear …

[WEB-810] Set endDate param for fetching latest datums to server time

---

app/components/elements/Accordion.js
stories/Accordion.stories.js

[WEB-762] Accordion component
[WEB-762]: https://tidepool.atlassian.net/browse/WEB-762

[WEB-762] accordion

---

package.json
yarn.lock

See [WEB-805] for details.
Related PR: tidepool-org/viz#202
[WEB-805]: https://tidepool.atlassian.net/browse/WEB-805

[WEB-805] Fix BG Log crashes for patients viewing data in time zones with irregular offsets

---

package.json
yarn.lock

Merge release branch for [WEB-771] [WEB-785] [WEB-805] [WEB-807] back to `develop`
[WEB-771]: https://tidepool.atlassian.net/browse/WEB-771
[WEB-785]: https://tidepool.atlassian.net/browse/WEB-785
[WEB-805]: https://tidepool.atlassian.net/browse/WEB-805
[WEB-807]: https://tidepool.atlassian.net/browse/WEB-807

Release 1.33.0 to develop [WEB-771, WEB-785, WEB-805, WEB-807]

---

app/core/api.js

Moves around prioritization/labeling for Rollbar extra info to help with [WEB-830]
[WEB-830]: https://tidepool.atlassian.net/browse/WEB-830

[WEB-830] re-prioritize/re-label error properties

---

app/core/constants.js
locales/en/translation.json
locales/es/translation.json
locales/fr/translation.json
test/unit/app/core/constants.test.js
test/unit/components/donateform.test.js
test/unit/utils/personutils.test.js

Removed CarbDM from possible donation organizations and swapped out BT1 for CARBDM in tests. Jira Ticket: https://tidepool.atlassian.net/browse/WEB-811

[WEB-811] Remove CarbDM from donation list

---

app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js

Merging [WEB-831] (`v1.33.1`) back into release branch
[WEB-831]: https://tidepool.atlassian.net/browse/WEB-831

Merge [WEB-831] daily view JS hotfix to current release branch

---

package.json
yarn.lock

To resolve [WEB-829], involves a `superagent` update via `platform-client`. 
[WEB-829]: https://tidepool.atlassian.net/browse/WEB-829

[WEB-829] retry API calls

---

app/pages/prescription/PrescriptionForm.js
app/pages/prescription/prescriptionFormConstants.js
app/pages/prescription/therapySettingsFormStep.js
test/unit/pages/prescription/prescriptionFormConstants.test.js

See [WEB-899] for details.
[WEB-899]: https://tidepool.atlassian.net/browse/WEB-899

[WEB-899] Update guardrails, default values, and descriptions for therapy settings

---

app/components/sharedatabanner/sharedatabanner.js
app/pages/app/app.js
test/unit/components/sharedatabanner.test.js

Original Jira Ticket: https://tidepool.atlassian.net/browse/WEB-794
Test Plan Ticket: https://tidepool.atlassian.net/browse/WEB-963

[WEB-794] Share Data Banner -- Fix to address QA test failure

---

app/components/sharedatabanner/sharedatabanner.js
app/pages/app/app.js
test/unit/components/sharedatabanner.test.js

Jira Ticket: https://tidepool.atlassian.net/browse/WEB-794

[WEB-794] Fix to address test failure

---

package.json
yarn.lock

See [WEB-975] 
Related PR: tidepool-org/viz#220
[WEB-975]: https://tidepool.atlassian.net/browse/WEB-975

[WEB-975] Fix flickering with mouseover events on horizontal bar stats

---

app/core/language.js
karma.conf.js

See [WEB-957] for details.
[WEB-957]: https://tidepool.atlassian.net/browse/WEB-957

[WEB-957] Only set localStorage.lang to browser locale if i18n feature flag is on

---

package.json
yarn.lock

See [WEB-983]
Related PR:
tidepool-org/viz/pull/221
[WEB-983]: https://tidepool.atlassian.net/browse/WEB-983

[WEB-983] Update reductio and crossfilter

---

package.json
yarn.lock

See [WEB-1003] for details
Related PR: tidepool-org/viz#223
[WEB-1003]: https://tidepool.atlassian.net/browse/WEB-1003

[WEB-1003] Stat animation precision fix

---

app/components/chart/basics.js
app/components/chart/stats.js
app/components/chart/trends.js
app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js
yarn.lock

Jira Ticket: https://tidepool.atlassian.net/browse/WEB-889

[WEB-889] using new bgExtents commonStat

---

app/pages/prescription/PrescriptionForm.js
app/pages/prescription/prescriptionFormConstants.js
app/pages/prescription/prescriptionSchema.js
app/pages/prescription/reviewFormStep.js
app/pages/prescription/therapySettingsFormStep.js
test/unit/pages/prescription/prescriptionFormConstants.test.js
test/unit/pages/prescription/prescriptionSchema.test.js
test/unit/pages/prescription/reviewFormStep.test.js
test/unit/pages/prescription/therapySettingsFormStep.test.js

See [WEB-1021] for details
[WEB-1021]: https://tidepool.atlassian.net/browse/WEB-1021

[WEB-1021] Re-enable Insulin Model and Suspend Threshold in prescription form

---

app/components/uploaderbanner/uploaderbanner.js
app/components/uploaderbanner/uploaderbanner.less
app/pages/app/app.js
package.json
test/unit/app/app.test.js

Hotfix modifications to enable the uploader banner to display for all logged in users and expire 10/1/2020.

[WEB-1026] display banner for all logged in users

---

app/pages/prescription/PrescriptionForm.js
app/pages/prescription/accountFormSteps.js
app/pages/prescription/prescriptionFormConstants.js
app/pages/prescription/prescriptionSchema.js
app/pages/prescription/profileFormSteps.js
app/pages/prescription/reviewFormStep.js
test/unit/pages/prescription/accountFormSteps.test.js
test/unit/pages/prescription/prescriptionFormConstants.test.js
test/unit/pages/prescription/prescriptionSchema.test.js

See [WEB-864]
[WEB-864]: https://tidepool.atlassian.net/browse/WEB-864

[WEB-864] Add caregiver fields to prescription form

---

webpack.config.js

Thanks for finding the fix so quick @krystophv
Just wrapped it up in a PR for your review

Fix for broken production config stemming from webpack html plugin bump

---

app/components/PrintDateRangeModal.js
app/pages/patientdata/patientdata.js
test/unit/components/printDateRangeModal.test.js

See [WEB-1063] for details
[WEB-1063]: https://tidepool.atlassian.net/browse/WEB-1063

[WEB-1063] Add print dialog metrics

---

app/components/inputgroup/inputgroup.js
app/components/simpleform/simpleform.js
app/pages/login/login.js
app/pages/signup/signup.js

Jira Ticket: https://tidepool.atlassian.net/browse/WEB-270
`Remember me` set to default checked on login page

WEB-270 Add default checked to Remember me on login page

---

app/components/inputgroup/inputgroup.js
app/components/simpleform/simpleform.js
app/pages/login/login.js
app/pages/signup/signup.js

Jira Ticket: https://tidepool.atlassian.net/browse/WEB-343
Updated first input fields to autofocus on the sign up and login pages

WEB-343 autoFocus on signup/login pages

---

app/core/personutils.js
app/core/validation/errors.js
test/unit/utils/personutils.test.js
test/unit/utils/validation.test.js

Jira Ticket: https://tidepool.atlassian.net/browse/WEB-330
Addressed confusing error message when user enters date as "M/DD/YYYY" (or any other format other than) "MM/DD/YYYY"

[WEB-330] Updated error for profile datepicker

---

app/pages/login/login.js

Jira Ticket: https://tidepool.atlassian.net/browse/WEB-270

[WEB-270] FIX - update value of checkbox to persist

---

app/core/constants.js
test/unit/app/core/constants.test.js

Jira Ticket: https://tidepool.atlassian.net/browse/WEB-503
Added MODY diabetes to the list of available diabetes type for a user to choose

[WEB-503] Added MODY diabetes type

---

package.json
yarn.lock

See [WEB-1102]
Related PR: tidepool-org/tideline#415
[WEB-1102]: https://tidepool.atlassian.net/browse/WEB-1102

[WEB-1102] Fix basics count css regression

---

app/components/elements/Stepper.js
app/pages/prescription/PrescriptionForm.js

See [WEB-1103]
[WEB-1103]: https://tidepool.atlassian.net/browse/WEB-1103

[WEB-1103] Handle async errors on prescription form

---

package.json
yarn.lock

See [WEB-1127]
Related PR: tidepool-org/viz#246
[WEB-1127]: https://tidepool.atlassian.net/browse/WEB-1127

[WEB-1127] Round carbs from HealthKit in print view

---

package.json
yarn.lock

See [WEB-1127]
[WEB-1127]: https://tidepool.atlassian.net/browse/WEB-1127

Release 1.42.0 to develop [WEB-1127]

---

package.json

Merge release for [WEB-1129] back to develop
[WEB-1129]: https://tidepool.atlassian.net/browse/WEB-1129

Release 1.43.0 to develop [WEB-1129]

---

package.json
yarn.lock

See [WEB-1137]
Related PR:
https://github.com/tidepool-org/viz/pull/252
[WEB-1137]: https://tidepool.atlassian.net/browse/WEB-1137

[WEB-1137] Fix PDF bolus rendering errors 

---

.eslintrc
app/components/browserwarning/browserwarning.js
app/components/chart/basics.js
app/components/chart/bgLog.js
app/components/chart/settings.js
app/components/dexcombanner/dexcombanner.js
app/components/donatebanner/donatebanner.js
app/components/donateform/donateform.js
app/components/footerlinks/footerlinks.js
app/components/sharedatabanner/sharedatabanner.js
app/pages/patient/patient.js
app/pages/patientdata/patientdata.js
app/pages/patientnew/patientnew.js
app/pages/signup/signup.js
app/pages/terms/terms.js

Addresses [WEB-1138] by adding requisite `rel="noreferrer noopener"` to external `target="_blank"` links and enabling the eslint rule to ensure future links are caught at development time
[WEB-1138]: https://tidepool.atlassian.net/browse/WEB-1138

[WEB-1138] add noreferrer noopener and eslint rule

---

package.json
yarn.lock

Hotfix. See [WEB-1151].
Related PR: https://github.com/tidepool-org/viz/pull/257
[WEB-1151]: https://tidepool.atlassian.net/browse/WEB-1151

[WEB-1151] Reject duplicate wizards

---

app/pages/patientdata/patientdata.js

What is says ;)
See [WEB-1156]
[WEB-1156]: https://tidepool.atlassian.net/browse/WEB-1156

[WEB-1156] Do not use latestPumpSettings time as most recent datum time for basics view

---

package.json
yarn.lock

See [WEB-1171] for details
[WEB-1171]: https://tidepool.atlassian.net/browse/WEB-1171

[WEB-1171] Hotfix: Fix CIQ capabilities checks

---

package.json
yarn.lock

See [WEB-1179]
Related PR: https://github.com/tidepool-org/viz/pull/272
[WEB-1179]: https://tidepool.atlassian.net/browse/WEB-1179

[WEB-1179] Fix for incorrect devices count when switching users

---

app/pages/prescription/prescriptionSchema.js

See [WEB-1167]
[WEB-1167]: https://tidepool.atlassian.net/browse/WEB-1167

[WEB-1167] Update prescription birthdate validation to require date within last 130 years

---

app/redux/actions/async.js
test/unit/redux/actions/async.test.js

See [WEB-1194]
[WEB-1194]: https://tidepool.atlassian.net/browse/WEB-1194

Filter out 'pumpSettings' when determining latest diabetes datum time to fetch from [WEB-1194]

---

app/core/utils.js
app/pages/login/login.js
app/redux/actions/async.js
index.ejs
test/unit/utils/utils.test.js

Addresses [WEB-1178] by adding some basic pendo integration.
This will need to be augmented once the new clinical system goes in.
[WEB-1178]: https://tidepool.atlassian.net/browse/WEB-1178

[WEB-1178] pendo integration

---

server.js

Adds CSP configuration to allow Pendo.io functionality

[WEB-1178] update CSP for pendo

---

app/pages/prescription/PrescriptionForm.js
app/pages/share/PatientInvites.js
package.json
test/unit/pages/share/PatientInvites.test.js

See [WEB-1208]
[WEB-1208]: https://tidepool.atlassian.net/browse/WEB-1208

[WEB-1208] Add a button to refresh the patient invite list when there are no pending invites

---

app/components/clinic/ClinicianPermissionsDialog.js
app/pages/clinicadmin/clinicadmin.js
app/pages/clinicianedit/clinicianedit.js
app/pages/clinicinvite/clinicinvite.js
package.json
test/unit/pages/clinicianedit.test.js
test/unit/pages/clinicinvite.test.js

See [WEB-1214]
[WEB-1214]: https://tidepool.atlassian.net/browse/WEB-1214

[WEB-1214] Add permissions info dialog to clinician invite and edit forms

---

app/components/clinic/ClinicProfile.js
app/components/clinic/WorkspaceSwitcher.js
app/components/navbar/NavigationMenu.js
app/components/navbar/navbar.js
app/components/peopletable/peopletable.js
app/pages/clinicadmin/clinicadmin.js
app/pages/clinicianedit/clinicianedit.js
app/pages/clinicinvite/clinicinvite.js
app/pages/clinicworkspace/clinicworkspace.js
app/pages/share/PatientInvites.js
app/pages/workspaces/workspaces.js

See [WEB-1210]
[WEB-1210]: https://tidepool.atlassian.net/browse/WEB-1210

[WEB-1210] Add metrics to clinic admin flow

---

app/pages/patientdata/patientdata.js
package.json
yarn.lock

See [WEB-1202]
Related PR: https://github.com/tidepool-org/viz/pull/278
[WEB-1202]: https://tidepool.atlassian.net/browse/WEB-1202

[WEB-1202] Add percentages to readings in range stat text output

---

app/components/elements/Button.js
app/components/elements/TabGroup.js
app/components/elements/TextInput.js
app/components/peopletable/peopletable.js
app/components/peopletable/peopletable.less
app/pages/clinicadmin/clinicadmin.js
app/pages/clinicinvite/clinicinvite.js
app/pages/share/AccessManagement.js
app/pages/share/InviteClinic.js
app/pages/share/InviteMember.js
app/pages/workspaces/workspaces.js
app/themes/base/buttons.js
app/themes/base/forms.js
app/themes/base/icons.js
app/themes/base/inputs.js
app/themes/baseTheme.js
app/themes/colorPalette.js
locales/en/translation.json
locales/es/translation.json
locales/fr/translation.json
test/unit/components/peopletable.test.js
test/unit/pages/clinicadmin.test.js
test/unit/pages/share/AccessManagement.test.js
test/unit/pages/workspaces/workspaces.test.js

See [WEB-1217]
Design updates incorporating feedback from the clinic UI review, as well as some general 'tightening up' of some of the common component styling.
[WEB-1217]: https://tidepool.atlassian.net/browse/WEB-1217

[WEB-1217] Clinic UI design updates

---

package.json
yarn.lock

See [WEB-1201]
Related PR: https://github.com/tidepool-org/viz/pull/280
[WEB-1201]: https://tidepool.atlassian.net/browse/WEB-1201

[WEB-1201] Add Avg. Glucose to Basics portion of PDF printout

---

app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js
yarn.lock

See [WEB-698]
Related PR: https://github.com/tidepool-org/viz/pull/282
[WEB-698]: https://tidepool.atlassian.net/browse/WEB-698?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-698] Add standard deviation stat to basics web and print views

---

app/components/peopletable/peopletable.js
app/pages/clinicadmin/clinicadmin.js
app/pages/patients/patients.js
app/pages/patients/patients.less

Addresses [WEB-1289] and [WEB-1292]
Also updated the visibility of the pagination to the patient list (and the clinic member list) to only show when needed for consistency with other views.
[WEB-1289]: https://tidepool.atlassian.net/browse/WEB-1289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1292]: https://tidepool.atlassian.net/browse/WEB-1292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Use legacy patient list for clinician's private workspaces [WEB-1289,WEB-1292]

---

app/components/elements/NotificationIcon.js
app/components/navbar/NavigationMenu.js
app/pages/workspaces/workspaces.js
test/unit/components/navbar/NavigationMenu.test.js
test/unit/pages/workspaces/workspaces.test.js

See [WEB-1290]
[WEB-1290]: https://tidepool.atlassian.net/browse/WEB-1290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1290] Add notification indicators for pending clinic invites

---

.travis.yml
app/components/navbar/NavigationMenu.js
app/pages/clinicdetails/clinicdetails.js

See [WEB-1237]
Also includes a typo fix that was causing a CSS nav menu width issue
[WEB-1237]: https://tidepool.atlassian.net/browse/WEB-1237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1237] migration logout instructions modal

---

app/pages/clinicianedit/clinicianedit.js
app/pages/clinicinvite/clinicinvite.js

See [WEB-1286] 
[WEB-1286]: https://tidepool.atlassian.net/browse/WEB-1286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1286] Update copy for clinician invite and edit backout modals

---

app/components/ChartDateRangeModal.js
app/components/PrintDateRangeModal.js

See [WEB-1297]
[WEB-1297]: https://tidepool.atlassian.net/browse/WEB-1297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1297] Add 90 day option to basics web and print date range presets

---

package.json
yarn.lock

Main PR: https://github.com/tidepool-org/viz/pull/284

Allow DataUtil storybook to use raw data from blip console downloads

---

app/core/clinicUtils.js

See [WEB-1305]
[WEB-1305]: https://tidepool.atlassian.net/browse/WEB-1305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1305] Update website validation to alert the user to the need for the protocol if missing

---

app/pages/clinicworkspace/ClinicPatients.js
test/unit/pages/ClinicPatients.test.js

See [WEB-1303]. Only needed to add `MRN`. Other fields required by ticket were already present.
[WEB-1303]: https://tidepool.atlassian.net/browse/WEB-1303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1303] Add MRN field to clinic patient list

---

app/pages/clinicdetails/clinicdetails.js
test/unit/pages/clinicdetails.test.js

See [WEB-1294]
[WEB-1294]: https://tidepool.atlassian.net/browse/WEB-1294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1294] Design review updates for clinic details page decline button

---

app/pages/clinicadmin/clinicadmin.js
app/pages/share/AccessManagement.js
test/unit/pages/clinicadmin.test.js
test/unit/pages/share/AccessManagement.test.js

See [WEB-1336]
[WEB-1336]: https://tidepool.atlassian.net/browse/WEB-1336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1336] Update revoke/resend copy to be consistent across pages

---

app/pages/clinicdetails/clinicdetails.js

See [WEB-1344]
[WEB-1344]: https://tidepool.atlassian.net/browse/WEB-1344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1344] Redirect to clinician details page for newly created clinician after clinic invite decline.

---

app/pages/clinicworkspace/ClinicPatients.js
test/unit/pages/ClinicPatients.test.js

For [WEB-1340], moves the edit and delete columns into a popover menu
[WEB-1340]: https://tidepool.atlassian.net/browse/WEB-1340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1340] move edit/delete to popover

---

app/pages/clinicadmin/clinicadmin.js
test/unit/pages/clinicadmin.test.js

Addresses [WEB-1350] by using the clinic invite modified time instead of the created time. 
[WEB-1350]: https://tidepool.atlassian.net/browse/WEB-1350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1350] use modified time instead of created time

---

.travis.yml
app/pages/app/app.js
package.json
test/unit/app/app.test.js

Hotfix for [WEB-1359] to ensure that datasource information displays correctly on profile page refresh.
[WEB-1359]: https://tidepool.atlassian.net/browse/WEB-1359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1359] datasource refresh

---

app/components/ChartDateRangeModal.js
package.json

See [WEB-1364]
[WEB-1364]: https://tidepool.atlassian.net/browse/WEB-1364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1364] Increase min-height of basics date range calendars

---

app/pages/clinicworkspace/ClinicPatients.js
package.json
test/unit/pages/ClinicPatients.test.js

Re-enables [WEB-1302] [WEB-1303]
[WEB-1302]: https://tidepool.atlassian.net/browse/WEB-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1303]: https://tidepool.atlassian.net/browse/WEB-1303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1302,WEB-1303] Re-enable patient add/edit functionality in new Clinic UI patients list

---

package.json
yarn.lock

See [WEB-1188]
Related PR: https://github.com/tidepool-org/viz/pull/292
[WEB-1188]: https://tidepool.atlassian.net/browse/WEB-1188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1188] Add new device settings to web, print and text output

---

app/core/utils.js
package.json
yarn.lock

As the functionality was tightly related, this PR covers [WEB-1369], [WEB-1370], and [WEB-1371]
Related PR: https://github.com/tidepool-org/viz/pull/293
[WEB-1369]: https://tidepool.atlassian.net/browse/WEB-1369?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1370]: https://tidepool.atlassian.net/browse/WEB-1370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1371]: https://tidepool.atlassian.net/browse/WEB-1371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1369,WEB-1370,WEB-1371] Updates to PDF and Text Stat output

---

app/pages/clinicadmin/clinicadmin.js
app/pages/clinicianedit/clinicianedit.js
package.json
test/unit/pages/clinicadmin.test.js
test/unit/pages/clinicianedit.test.js

Hotfix for [WEB-1413]
[WEB-1413]: https://tidepool.atlassian.net/browse/WEB-1413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1413] clinic clinician list all results

---

app/pages/clinicadmin/clinicadmin.js
app/pages/clinicianedit/clinicianedit.js
package.json
test/unit/pages/clinicadmin.test.js
test/unit/pages/clinicianedit.test.js

Back merge [WEB-1413] to `1.49.0` release candidate.
[WEB-1413]: https://tidepool.atlassian.net/browse/WEB-1413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1413] Merge release 1.48.1 hotfix to 1.49.0 release candidate

---

app/core/personutils.js
app/pages/clinicdetails/clinicdetails.js
app/routes.js
package.json
test/unit/pages/clinicdetails.test.js
test/unit/routes.test.js
test/unit/utils/personutils.test.js

See [WEB-1440] for details.
[WEB-1440]: https://tidepool.atlassian.net/browse/WEB-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1440] Route redirect hotfixes

---

app/core/personutils.js
app/pages/clinicdetails/clinicdetails.js
app/routes.js
package.json
test/unit/pages/clinicdetails.test.js
test/unit/routes.test.js
test/unit/utils/personutils.test.js

Merge hotfix release 1.48.2 ([WEB-1440]) into 1.49.0 
[WEB-1440]: https://tidepool.atlassian.net/browse/WEB-1440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Merge hotfix release 1.48.2 into 1.49.0 

---

app/components/chart/bgLog.js
app/components/chart/daily.js
app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js
yarn.lock

See [WEB-1213] 
Related PR: https://github.com/tidepool-org/viz/pull/296
[WEB-1213]: https://tidepool.atlassian.net/browse/WEB-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1213] Allow changing to default BG target ranges

---

app/components/elements/Button.js
app/themes/base/paginators.js
stories/Pagination.stories.js

See [WEB-1447]
[WEB-1447]: https://tidepool.atlassian.net/browse/WEB-1447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1447] Fix overflowing text on pagination buttons once 3 digits are shown

---

app/components/navbar/NavigationMenu.js
app/redux/actions/async.js
app/redux/reducers/working.js
app/routes.js
package.json
test/unit/components/navbar/NavigationMenu.test.js
test/unit/routes.test.js

See [WEB-1458]
[WEB-1458]: https://tidepool.atlassian.net/browse/WEB-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1458] Check for clinic invites on initial browser load for authenticated routes

---

package.json
yarn.lock

Merges release 1.50.0 back to develop

Release 1.50.0 to develop

---

app/components/clinic/PatientForm.js
app/pages/clinicworkspace/ClinicPatients.js

See [WEB-1462]
[WEB-1462]: https://tidepool.atlassian.net/browse/WEB-1462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1462] Add metric for addition of emails to created or updated clinic patients

---

app/redux/actions/async.js
app/redux/constants/errorMessages.js
package.json
test/unit/redux/actions/async.test.js

See [WEB-1450]
[WEB-1450]: https://tidepool.atlassian.net/browse/WEB-1450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1450] Better duplicate clinic invite message

---

app/pages/clinicadmin/clinicadmin.js
package.json

See [WEB-1451]
[WEB-1451]: https://tidepool.atlassian.net/browse/WEB-1451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1451] Fix for sorting clinic team members by status

---

package.json
yarn.lock

See [WEB-1412]
Related PR: https://github.com/tidepool-org/viz/pull/305
[WEB-1412]: https://tidepool.atlassian.net/browse/WEB-1412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1412] Fix incorrect disabled state criteria on stats

---

app/components/navbar/NavigationMenu.js
package.json

Hotfix for [WEB-1458]
[WEB-1458]: https://tidepool.atlassian.net/browse/WEB-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1458] Release 1.50.2 to master

---

app/components/navbarpatientcard/navbarpatientcard.js
app/components/patientcard/patientcard.less
test/unit/components/navbarpatientcard.test.js

See ticket [WEB-95]
[WEB-95]: https://tidepool.atlassian.net/browse/WEB-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-95] add patient date of birth to header

---

app/core/personutils.js
package.json
test/unit/redux/utils/pendoMiddleware.test.js
test/unit/utils/personutils.test.js

Per [WEB-1503], adding in `clinician` role to act as the new `migrated_clinic` role
[WEB-1503]: https://tidepool.atlassian.net/browse/WEB-1503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WEB-1503 - deprecate `migrated_clinic` role

---

app/components/elements/DatePicker.js
app/components/elements/DateRangePicker.js
app/pages/clinicadmin/clinicadmin.js
app/pages/clinicworkspace/ClinicPatients.js
package.json
test/unit/pages/ClinicPatients.test.js
test/unit/pages/clinicadmin.test.js
yarn.lock

Release 1.53.0 to develop

---

app/components/clinic/ClinicProfileFields.js
app/core/clinicUtils.js
app/pages/clinicworkspace/ClinicPatients.js
test/unit/app/core/clinicUtils.test.js
test/unit/pages/ClinicPatients.test.js
test/unit/pages/ClinicProfile.test.js
test/unit/pages/clinicdetails.test.js

See [WEB-1620]
[WEB-1620]: https://tidepool.atlassian.net/browse/WEB-1620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1620] Add preferred bg units to clinic profile 

---

app/core/utils.js
app/pages/patientdata/patientdata.js
test/unit/pages/patientdata.test.js

See [WEB-1631]
Shows the patient data in the clinic's preferred BG units when available
[WEB-1631]: https://tidepool.atlassian.net/browse/WEB-1631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1631] Show patient data in a clinic's preferred BG units

---

app/pages/share/InviteClinic.js
app/pages/share/InviteMember.js

See [WEB-1560]
I applied this styling change to both the clinic and member share forms for consistency
[WEB-1560]: https://tidepool.atlassian.net/browse/WEB-1560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1560] Update sharing link text styling

---

app/core/utils.js
app/pages/patientdata/patientdata.js

Need to add some debugging log statements to production to investigate further.

Debug cause of preferred bg units not working in production

---

app/pages/app/app.js
app/redux/reducers/data.js
package.json
test/unit/redux/reducers/data.test.js

Release 1.54.3 hotfix merge to Release 1.55.0

Release 1.54.3 hotfix merge to Release 1.55.0

---

app/redux/actions/async.js
test/unit/redux/actions/async.test.js

See [WEB-1683]
[WEB-1683]: https://tidepool.atlassian.net/browse/WEB-1683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1683] Set selected clinic ID upon login for users with a single clinic before redirecting

---

app/core/utils.js
app/pages/app/app.js
app/pages/patientdata/patientdata.js
app/redux/actions/async.js
app/redux/reducers/data.js
app/redux/reducers/working.js
package.json
test/unit/redux/actions/async.test.js
test/unit/redux/reducers/data.test.js
test/unit/redux/reducers/working.test.js

Merge release 1.55.0 back to develop

Release 1.55.0 to develop

---

app/components/elements/Table.js
package.json

Back-merge [WEB-1702] fix to next release
[WEB-1702]: https://tidepool.atlassian.net/browse/WEB-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Back-merge [WEB-1702] fix to next release

---

app/components/clinic/WorkspaceSwitcher.js
app/components/navbar/NavigationMenu.js
app/pages/clinicworkspace/clinicworkspace.js
app/pages/patients/patients.js
app/pages/workspaces/workspaces.js
app/redux/actions/async.js
package.json
test/unit/components/clinic/WorkspaceSwitcher.test.js
test/unit/components/navbar/NavigationMenu.test.js
test/unit/pages/workspaces/workspaces.test.js
test/unit/redux/actions/async.test.js

See [WEB-1697]
[WEB-1697]: https://tidepool.atlassian.net/browse/WEB-1697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1697] Persist selected clinic ID when using the browser navigation buttons

---

app/components/clinic/ClinicProfileFields.js

For [WEB-1669], pretty much what it says on the tin
[WEB-1669]: https://tidepool.atlassian.net/browse/WEB-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1669] switch city and address field positions

---

app/pages/workspaces/workspaces.js
test/unit/pages/workspaces/workspaces.test.js

See [WEB-1642].  Addresses design review changer requests
[WEB-1642]: https://tidepool.atlassian.net/browse/WEB-1642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1642] Clincian signup design review tweaks

---

app/core/clinicUtils.js
test/unit/app/core/clinicUtils.test.js

[WEB-1842]
[WEB-1842]: https://tidepool.atlassian.net/browse/WEB-1842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1842] Update 'research_organization' clinic type key to match backend

---

app/pages/clinicworkspace/ClinicPatients.js

For [WEB-1848] and [WEB-1849], manually tracks part of working state to force a re-render after state updates that aren't being properly propagated to useEffect hooks and augments/combines some of the logic to set fetch options to ensure that multiple setState's don't collide and overwrite each other in a single render cycle.
[WEB-1848]: https://tidepool.atlassian.net/browse/WEB-1848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1849]: https://tidepool.atlassian.net/browse/WEB-1849?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1848, WEB-1849] clear loading state, set options on first render

---

app/pages/clinicworkspace/ClinicPatients.js

See [WEB-1752]
[WEB-1752]: https://tidepool.atlassian.net/browse/WEB-1752?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1752] Only apply summary filters to premium tier clinics

---

app/pages/share/ShareInvite.js

For design review on [WEB-1710], changes the previous button behavior to be more consistent across the two sharing options.
[WEB-1710]: https://tidepool.atlassian.net/browse/WEB-1710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1710] switch button labels

---

.travis.yml

Update travis dist to jammy

---

app/pages/clinicworkspace/ClinicPatients.js
app/pages/clinicworkspace/clinicworkspace.js

See [WEB-1891]
[WEB-1891]: https://tidepool.atlassian.net/browse/WEB-1891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1891] intermittent clinic UI fix

---

app/pages/clinicdetails/clinicdetails.js
app/pages/workspaces/workspaces.js
app/redux/actions/async.js
app/routes.js

See [WEB-1892]
[WEB-1892]: https://tidepool.atlassian.net/browse/WEB-1892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1892] Ensure all clinics are fetched for a clinician

---

app/components/navbar/NavigationMenu.js
package.json
test/unit/components/navbar/NavigationMenu.test.js

Release 1.57.1 to master

---

app/pages/clinicdetails/clinicdetails.js
package.json

Metrics Hotfix for [WEB-1933] (clinic creation metric)
[WEB-1933]: https://tidepool.atlassian.net/browse/WEB-1933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release 1.57.3 to master

---

app/core/constants.js
locales/en/translation.json
locales/es/translation.json
locales/fr/translation.json
package.json

[WEB-1905]
[WEB-1905]: https://tidepool.atlassian.net/browse/WEB-1905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1905] donation partner name update

---

app/pages/clinicworkspace/ClinicPatients.js
app/pages/signup/signup.js

[WEB-1944]
Also includes a rather minor fix for the role setting on signup.
[WEB-1944]: https://tidepool.atlassian.net/browse/WEB-1944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1944] Clinic member tag update fixes

---

app/pages/clinicworkspace/ClinicPatients.js

[WEB-1954]
[WEB-1954]: https://tidepool.atlassian.net/browse/WEB-1954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1954] Fix default pending tags on patient popovers

---

app/components/clinic/WorkspaceSwitcher.js
app/components/navbar/NavigationMenu.js

[WEB-1901]
[WEB-1901]: https://tidepool.atlassian.net/browse/WEB-1901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1901] Clinic List Ordering

---

app/core/clinicUtils.js

See [WEB-1939]
[WEB-1939]: https://tidepool.atlassian.net/browse/WEB-1939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1939] Update regex for tag name validation

---

app/components/chart/basics.js
app/components/chart/bgLog.js
app/components/chart/daily.js
app/components/chart/trends.js
app/pages/patientdata/patientdata.less
package.json
test/unit/components/chart/bgLog.test.js
yarn.lock

[WEB-1805]
Related: https://github.com/tidepool-org/viz/pull/333
[WEB-1805]: https://tidepool.atlassian.net/browse/WEB-1805?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1805] Copy as text button for BG Log

---

app/pages/clinicworkspace/ClinicPatients.js
package.json
test/unit/pages/ClinicPatients.test.js

Hotfix for [WEB-1963]
[WEB-1963]: https://tidepool.atlassian.net/browse/WEB-1963?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1963] disable summary period dropdown

---

app/pages/clinicworkspace/ClinicPatients.js

[WEB-1964]
[WEB-1964]: https://tidepool.atlassian.net/browse/WEB-1964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1964] Fix for assign patient tag open metric

---

package.json
yarn.lock

Release v1.59.0 to develop

---

app/pages/patientdata/patientdata.js
app/redux/reducers/misc.js
package.json
yarn.lock

See [WEB-1877] 
Related PR: https://github.com/tidepool-org/viz/pull/334
[WEB-1877]: https://tidepool.atlassian.net/browse/WEB-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1877] Add MRN to text output on data views

---

package.json
yarn.lock

Release v1.60.0 to develop

---

app/pages/clinicworkspace/ClinicPatients.js
app/redux/reducers/misc.js
package.json
test/unit/redux/reducers/clinics.test.js

Hotfix.  See [WEB-2012]
[WEB-2012]: https://tidepool.atlassian.net/browse/WEB-2012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2012] patient list sorting

---

app/components/clinic/PatientForm.js
test/unit/pages/ClinicPatients.test.js

Addresses design feedback for [WEB-2039]
[WEB-2039]: https://tidepool.atlassian.net/browse/WEB-2039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2039] design feedback

---

app/components/clinic/PatientForm.js

[WEB-2040]
[WEB-2040]: https://tidepool.atlassian.net/browse/WEB-2040?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2040] Show dexcom connect form if patient has declined authorization

---

app/components/clinic/PatientForm.js

See [WEB-2045]
[WEB-2045]: https://tidepool.atlassian.net/browse/WEB-2045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2045] Add ability to resend dexcom connection emails for error and expired connections

---

app/core/clinicUtils.js
app/pages/clinicworkspace/ClinicPatients.js
locales/en/translation.json
locales/es/translation.json
locales/fr/translation.json
test/unit/app/core/clinicUtils.test.js

[WEB-2010]
[WEB-2010]: https://tidepool.atlassian.net/browse/WEB-2010?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2010] Increase max patient tags to 20

---

app/pages/login/login.js
app/redux/reducers/misc.js
test/unit/pages/login.test.js
test/unit/redux/reducers/keycloakConfig.test.js

for [BACK-2365] forward the user back to the beginning of login/signup if they decline the terms of service
[BACK-2365]: https://tidepool.atlassian.net/browse/BACK-2365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACK-2365] tos decline flow

---

app/keycloak.js
app/pages/uploadredirect/index.js
app/pages/uploadredirect/uploadredirect.js
app/routes.js
package.json
test/unit/pages/uploadredirect.test.js
yarn.lock

for [UPLOAD-936] we need to have a launchpad for the uploader login process
[UPLOAD-936]: https://tidepool.atlassian.net/browse/UPLOAD-936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UPLOAD-936] provide redirect/launch for uploader login

---

app/redux/reducers/misc.js

[WEB-2069]
I think the best way to move forward is simply to add some extra existential checks where the JS error is occurring, and check with the affected users to see if the issue is resolved for them.
[WEB-2069]: https://tidepool.atlassian.net/browse/WEB-2069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2069] Add possible JS error due to race condition in redux store

---

app/components/clinic/PatientForm.js
app/redux/actions/async.js
app/redux/reducers/misc.js
package.json
test/unit/redux/actions/async.test.js

Hotfix release 1.62.1
Includes:
[WEB-2064]
[WEB-2065]
[WEB-2069]
[WEB-2064]: https://tidepool.atlassian.net/browse/WEB-2064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2065]: https://tidepool.atlassian.net/browse/WEB-2065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2069]: https://tidepool.atlassian.net/browse/WEB-2069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release 1.62.1 to master

---

app/pages/uploadredirect/uploadredirect.js
package.json
test/unit/pages/uploadredirect.test.js
yarn.lock

for [UPLOAD-995] displays browser-specific text for the launch dialog
[UPLOAD-995]: https://tidepool.atlassian.net/browse/UPLOAD-995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[UPLOAD-995] set browser specific text for external app launch

---

app/pages/clinicianedit/clinicianedit.js
app/pages/workspaces/workspaces.js
test/unit/pages/clinicianedit.test.js
test/unit/pages/workspaces/workspaces.test.js

for [WEB-1749], makes some efforts to prevent the last clinic admin from either leaving or dropping their admin privileges which would effectively orphan the clinic
[WEB-1749]: https://tidepool.atlassian.net/browse/WEB-1749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1749] prevent last clinic admin from leaving clinic

---

app/pages/clinicianedit/clinicianedit.js
test/unit/pages/clinicianedit.test.js

for [WEB-2115] adjusts logic to only consider non-invited clinic admins
[WEB-2115]: https://tidepool.atlassian.net/browse/WEB-2115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2115] disable leaving if last other admin is only invited

---

app/core/api.js
test/unit/app/core/api.test.js

for [WEB-2117], only attempts to make the user account update call if there's something to put there
[WEB-2117]: https://tidepool.atlassian.net/browse/WEB-2117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2117] only make user update call if necessary

---

app/pages/workspaces/workspaces.js
test/unit/pages/workspaces/workspaces.test.js

for [WEB-2115] also apply the filter for invited clinicians when determining last clinic admin to the workspaces page
[WEB-2115]: https://tidepool.atlassian.net/browse/WEB-2115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2115] apply invite filtering to workspaces page

---

package.json
yarn.lock

[WEB-2194]
Related PR: https://github.com/tidepool-org/viz/pull/346
[WEB-2194]: https://tidepool.atlassian.net/browse/WEB-2194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2194] Fix cgm days calculation for AGP report

---

app/components/PrintDateRangeModal.js
package.json

[WEB-2192]
[WEB-2192]: https://tidepool.atlassian.net/browse/WEB-2192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2192] Scroll date range pickers into view when opened on print modal

---

package.json
yarn.lock

[Web 2185]
Related PR: https://github.com/tidepool-org/viz/pull/349

[Web 2185] Hotfix: use 5 minute cgm sample frequency for Libre 3 data

---

package.json
yarn.lock

Merge tag version fix for v1.65.1 back to develop

Merge tag version fix for v1.65.1 back to develop

---

package.json
yarn.lock

[WEB-2252]
Related PR: https://github.com/tidepool-org/viz/pull/352
[WEB-2252]: https://tidepool.atlassian.net/browse/WEB-2252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2252] Hotfix: time in target daily print view missing

---

package.json
yarn.lock

Release 1.65.2 to develop

---

app/pages/clinicworkspace/ClinicPatients.js
test/unit/pages/ClinicPatients.test.js

[WEB-2094]
Note: forked off of https://github.com/tidepool-org/blip/pull/1208, so easiest may be to review that one first, then this one, once https://github.com/tidepool-org/blip/pull/1208 has been merged to `develop`
[WEB-2094]: https://tidepool.atlassian.net/browse/WEB-2094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2094] Add cgm use filter

---

app/components/uploaderbanner/uploaderbanner.js
app/components/uploaderbanner/uploaderbanner.less
app/pages/app/app.js
test/unit/components/uploaderbanner.test.js

[WEB-2259]
Note: I decided not to check for previous banner interactions with the old uploader banner, since the purpose of this ticket is to highlight uploader to newly-claimed, dexcom-connected accounts, who would not otherwise see the instructions to add uploader, since they likely already have CGM data present.
[WEB-2259]: https://tidepool.atlassian.net/browse/WEB-2259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2259] Uploader banner for new dexcom usets

---

app/pages/clinicworkspace/ClinicPatients.js

[WEB-2274]
[WEB-2274]: https://tidepool.atlassian.net/browse/WEB-2274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2274] Fix clear button handling on cgm use filter

---

app/pages/clinicworkspace/ClinicPatients.js
test/unit/pages/ClinicPatients.test.js

[WEB-2283] 
[WEB-2283]: https://tidepool.atlassian.net/browse/WEB-2283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2283] Don't show insufficient CGM data text for patient summaries with no cgm data

---

app/pages/clinicworkspace/ClinicPatients.js
package.json

[WEB-2089]
[WEB-2089]: https://tidepool.atlassian.net/browse/WEB-2089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2089] Update bg units in bg event info popover

---

app/pages/clinicworkspace/ClinicPatients.js
package.json
test/unit/pages/ClinicPatients.test.js

[WEB-2300]
Also includes small typo fix that was found
[WEB-2300]: https://tidepool.atlassian.net/browse/WEB-2300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2300] Bgm summary period sort fix

---

app/components/clinic/PatientForm.js
app/pages/clinicworkspace/ClinicPatients.js
test/unit/pages/ClinicPatients.test.js

[WEB-2182]
[WEB-2182]: https://tidepool.atlassian.net/browse/WEB-2182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2182] Clinic tier updates

---

app/components/chart/header.js
app/components/chart/trends.js
app/pages/patientdata/patientdata.js
test/unit/components/chart/trends.test.js

[WEB-2249]
[WEB-2249]: https://tidepool.atlassian.net/browse/WEB-2249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2249] Add print button to trends view while viewing CGM data

---

app/pages/clinicdetails/clinicdetails.js
locales/en/translation.json
locales/es/translation.json
locales/fr/translation.json

[WEB-2157]
[WEB-2157]: https://tidepool.atlassian.net/browse/WEB-2157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2157] Require clinician role on profile form

---

app/components/PrintDateRangeModal.js
package.json
yarn.lock

[WEB-1593]
[WEB-1593]: https://tidepool.atlassian.net/browse/WEB-1593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-1593] Ensure that dates beyond the last diabetes datum date can't be chosen in print date range pickers

---

package.json
yarn.lock

[WEB-2101] 
Related PR: https://github.com/tidepool-org/viz/pull/355
[WEB-2101]: https://tidepool.atlassian.net/browse/WEB-2101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2101] Add MRN to pdf headers

---

app/pages/clinicworkspace/ClinicPatients.js
app/redux/actions/async.js
package.json
test/unit/pages/ClinicPatients.test.js

[WEB-2340]
[WEB-2340]: https://tidepool.atlassian.net/browse/WEB-2340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2340] Consolidate period params

---

app/components/PrintDateRangeModal.js
app/pages/clinicadmin/clinicadmin.js
app/pages/clinicworkspace/ClinicPatients.js
package.json

[WEB-2353]
[WEB-2353]: https://tidepool.atlassian.net/browse/WEB-2353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2353] Ensure tag toasts don't show repeatedly on view load

---

app/pages/clinicworkspace/ClinicPatients.js
package.json
test/unit/pages/ClinicPatients.test.js

Adresses [WEB-2366], [WEB-2365], [WEB-2368]
[WEB-2366]: https://tidepool.atlassian.net/browse/WEB-2366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2365]: https://tidepool.atlassian.net/browse/WEB-2365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2368]: https://tidepool.atlassian.net/browse/WEB-2368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2366,WEB-2365,WEB-2368] Retain current sort when changing last upload filter, and add last upload date sorting

---

app/pages/clinicworkspace/ClinicPatients.js
package.json

[WEB-2381]
[WEB-2381]: https://tidepool.atlassian.net/browse/WEB-2381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2381] Ensure default cgm sort is set on last upload filter clear

---

app/keycloak.js
app/pages/uploadredirect/uploadredirect.js
app/pages/userprofile/userprofile.js
app/routes.js
package.json
test/unit/pages/uploadredirect.test.js
test/unit/pages/userprofile.test.js
test/unit/routes.test.js

for [WEB-2269], strives to handle cases where a user hasn't completed their requisite fullname in their profile before trying to launch uploader authentication via blip
[WEB-2269]: https://tidepool.atlassian.net/browse/WEB-2269?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2269] handle partial signups with incomplete fullname trying to launch uploader

---

app/redux/utils/pendoMiddleware.js
package.json
test/unit/redux/utils/pendoMiddleware.test.js

Takes care of [WEB-2397] and [WEB-2386] with some pendo ID and environment fixes
[WEB-2397]: https://tidepool.atlassian.net/browse/WEB-2397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2386]: https://tidepool.atlassian.net/browse/WEB-2386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2397][WEB-2386] Pendo updates

---

app/keycloak.js
app/pages/workspaces/workspaces.js
package.json
test/unit/keycloak.test.js
test/unit/pages/workspaces/workspaces.test.js
yarn.lock

For [WEB-2334] enables new interactions around invite restrictions based on email domain or SSO IDP requirements
[WEB-2334]: https://tidepool.atlassian.net/browse/WEB-2334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2334] sso clinician account linking

---

app/pages/workspaces/workspaces.js
test/unit/pages/workspaces/workspaces.test.js

for [WEB-2454] copy updates to SSO account linking flow
[WEB-2454]: https://tidepool.atlassian.net/browse/WEB-2454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2454] sso flow copy updates

---

app/pages/clinicdetails/clinicdetails.js
app/pages/uploadredirect/uploadredirect.js
test/unit/pages/uploadredirect.test.js

for [WEB-2460] sends clinicians who have only verified their email address and try to launch uploader to their clinician-specific profile form and back instead of the generic profile form
[WEB-2460]: https://tidepool.atlassian.net/browse/WEB-2460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2460] clinicians to their profile page on partial signup redirect

---

package.json

Release 1.68.0 to develop

---

app/routes.js
test/unit/routes.test.js

[WEB-2495]
[WEB-2495]: https://tidepool.atlassian.net/browse/WEB-2495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2495] Persist query params in keycloak redirect

---

package.json
yarn.lock

[WEB-2055]
Related PR: https://github.com/tidepool-org/viz/pull/360
[WEB-2055]: https://tidepool.atlassian.net/browse/WEB-2055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2055] Fix for showing empty basals calendar instead of empty text on Basics view

---

app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js
yarn.lock

[WEB-2246]
Related PR: https://github.com/tidepool-org/viz/pull/361
[WEB-2246]: https://tidepool.atlassian.net/browse/WEB-2246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2246] Add uploaded devices to text output

---

package.json
yarn.lock

[WEB-2503], [WEB-2504], [WEB-2506]
Related PR: https://github.com/tidepool-org/viz/pull/364
[WEB-2503]: https://tidepool.atlassian.net/browse/WEB-2503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2506]: https://tidepool.atlassian.net/browse/WEB-2506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2504]: https://tidepool.atlassian.net/browse/WEB-2504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2503,WEB-2504,WEB-2506] Fix bugs in matched device generation

---

package.json
yarn.lock

Addresses [WEB-2512], [WEB-2514]
Related PR: https://github.com/tidepool-org/tideline/pull/433
[WEB-2512]: https://tidepool.atlassian.net/browse/WEB-2512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2514]: https://tidepool.atlassian.net/browse/WEB-2514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2512,WEB-2514] Fix disabled rendering issues for basics calendar

---

app/pages/dashboard/TideDashboard.js
package.json

[WEB-2545]
[WEB-2545]: https://tidepool.atlassian.net/browse/WEB-2545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2545] Ensure only active clinic patient tags are sent in tide dashboard query

---

app/pages/dashboard/TideDashboard.js
app/themes/baseTheme.js
app/themes/colorPalette.js
package.json
test/unit/pages/TideDashboard.test.js
yarn.lock

[WEB-2546] Update TIDE header to show both upload date range and period
Supported by https://github.com/tidepool-org/viz/pull/366
[WEB-2546]: https://tidepool.atlassian.net/browse/WEB-2546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2546] date range adjustment

---

app/pages/dashboard/TideDashboard.js
package.json
yarn.lock

[WEB-2555]
[WEB-2555]: https://tidepool.atlassian.net/browse/WEB-2555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2555] Zero value display fix for time in ranges

---

config.webpack.js
webpack.config.js

for [WEB-2560] just switching out the tokens
[WEB-2560]: https://tidepool.atlassian.net/browse/WEB-2560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2560] Rollbar tokens

---

app/pages/dashboard/TideDashboard.js
package.json

See [WEB-2574]
[WEB-2574]: https://tidepool.atlassian.net/browse/WEB-2574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2574] Fix empty patient edit forms on Tide dash 

---

app/pages/dashboard/TideDashboard.js
app/redux/reducers/misc.js
package.json
test/unit/redux/reducers/tideDashboardPatients.test.js

[WEB-2576]
[WEB-2576]: https://tidepool.atlassian.net/browse/WEB-2576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2576] Update patients in tide dashboard results state

---

app/pages/clinicworkspace/ClinicPatients.js
package.json
test/unit/pages/ClinicPatients.test.js

[WEB-2588]
[WEB-2588]: https://tidepool.atlassian.net/browse/WEB-2588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2588] average glucose sort indicator UI fix

---

app/bootstrap.js
app/pages/clinicworkspace/ClinicPatients.js
app/pages/dashboard/TideDashboard.js
package.json
test/unit/pages/ClinicPatients.test.js
test/unit/pages/TideDashboard.test.js

[WEB-2590]
[WEB-2590]: https://tidepool.atlassian.net/browse/WEB-2590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2590] Allow showing summary dash for lower tier clinics with a flag

---

app/components/dexcombanner/dexcombanner.js
app/core/constants.js
package.json
test/unit/app/core/constants.test.js
test/unit/components/dexcombanner.test.js
test/unit/pages/ClinicPatients.test.js

[WEB-2110]
[WEB-2110]: https://tidepool.atlassian.net/browse/WEB-2110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2110] Update Dexcom banner copy

---

app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js
yarn.lock

[WEB-2605] 
[WEB-2605]: https://tidepool.atlassian.net/browse/WEB-2605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2605] agp print hotfix

---

package.json
test/unit/redux/actions/async.test.js
yarn.lock

to handle the timeouts associated with [WEB-2599] from extraneous traffic to metrics endpoints
platform client pr: https://github.com/tidepool-org/platform-client/pull/158
[WEB-2599]: https://tidepool.atlassian.net/browse/WEB-2599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2599] network timeouts (hotfix)

---

package.json
yarn.lock

[WEB-2618]
Related: https://github.com/tidepool-org/viz/pull/371
[WEB-2618]: https://tidepool.atlassian.net/browse/WEB-2618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2618] Fix error generating daily print view for bgm data

---

package.json
yarn.lock

[WEB-2620] 
Related PR: https://github.com/tidepool-org/viz/pull/372
[WEB-2620]: https://tidepool.atlassian.net/browse/WEB-2620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2620] Fix bgm count for basics readings in range stat

---

app/pages/patientdata/patientdata.js
package.json

[WEB-2623]
[WEB-2623]: https://tidepool.atlassian.net/browse/WEB-2623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2623] Fix for js error when deselecting all days on Trends bgm view

---

app/components/PrintDateRangeModal.js
package.json
yarn.lock

[WEB-2401]
Related PR: https://github.com/tidepool-org/viz/pull/374
[WEB-2401]: https://tidepool.atlassian.net/browse/WEB-2401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2401] Update PDF report config order

---

app/components/PrintDateRangeModal.js
package.json
test/unit/components/printDateRangeModal.test.js

[WEB-2656] 
[WEB-2656]: https://tidepool.atlassian.net/browse/WEB-2656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2656] Hotfix for invalid localStorage PDF config causing hanging for some users

---

app/components/clinic/PatientForm.js
app/components/elements/FontStyles.js
app/components/elements/TextInput.js
app/core/clinicUtils.js
app/pages/clinicworkspace/ClinicPatients.js
test/unit/app/core/clinicUtils.test.js
test/unit/pages/ClinicPatients.test.js
test/unit/pages/ClinicianPatients.test.js
test/unit/pages/TideDashboard.test.js

for [WEB-2517]
related to: https://github.com/tidepool-org/uploader/pull/1596
[WEB-2517]: https://tidepool.atlassian.net/browse/WEB-2517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2517] mrn validation

---

app/core/clinicUtils.js
test/unit/app/core/clinicUtils.test.js
test/unit/pages/clinicprofile.test.js

for [WEB-2562] - adds optional `timezone` field for clinic profile and passes it back on profile updates if it exists
[WEB-2562]: https://tidepool.atlassian.net/browse/WEB-2562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2562] allow optional timezone on clinic profile

---

app/pages/clinicadmin/clinicadmin.js
test/unit/pages/clinicadmin.test.js

for [WEB-2341]
[WEB-2341]: https://tidepool.atlassian.net/browse/WEB-2341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2341] export clinic member list CSV

---

app/components/chart/header.js
app/pages/patientdata/patientdata.js
package.json
test/unit/components/chart/trends.test.js

[WEB-2664]
[WEB-2664]: https://tidepool.atlassian.net/browse/WEB-2664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2664] Enable print link on BGM Trends view

---

app/core/clinicUtils.js
package.json
test/unit/app/core/clinicUtils.test.js

[WEB-2607]
[WEB-2607]: https://tidepool.atlassian.net/browse/WEB-2607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2607] Increase tag limit

---

app/core/constants.js
package.json

[WEB-2728]
[WEB-2728]: https://tidepool.atlassian.net/browse/WEB-2728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2728] Update data donation blog URL

---

app/components/PrintDateRangeModal.js
test/unit/components/printDateRangeModal.test.js

[WEB-2733]
[WEB-2733]: https://tidepool.atlassian.net/browse/WEB-2733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2733] Add a 30 day preset to CGM AGP print options

---

app/components/clinic/PatientForm.js
app/core/api.js
app/core/personutils.js
app/pages/clinicworkspace/ClinicPatients.js
app/pages/clinicworkspace/ClinicianPatients.js
app/pages/dashboard/TideDashboard.js
app/pages/share/PatientInvites.js
app/redux/actions/async.js
app/redux/actions/sync.js
app/redux/reducers/working.js
package.json
test/unit/pages/share/PatientInvites.test.js
test/unit/redux/actions/async.test.js
test/unit/redux/actions/sync.test.js
test/unit/utils/personutils.test.js
yarn.lock

See [WEB-2714]
Related PR: https://github.com/tidepool-org/platform-client/pull/161
[WEB-2714]: https://tidepool.atlassian.net/browse/WEB-2714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2714] Set patient MRN and other details while accepting invite to clinic

---

package.json
server.js

[WEB-2785]
[WEB-2785]: https://tidepool.atlassian.net/browse/WEB-2785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2785] Remove HSTS header

---

karma.conf.js
package.json
server.js

Release 1.75.0 to master

---

karma.conf.js
package.json
server.js

Release 1.75.0 to develop

---

app/pages/clinicworkspace/ClinicPatients.js
package.json

[WEB-2834] 
[WEB-2834]: https://tidepool.atlassian.net/browse/WEB-2834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2834] Remove patient list warning

---

app/core/clinicUtils.js
package.json
test/unit/pages/ClinicPatients.test.js

for [WEB-2837] - changes minimum length for MRN from 6 to 5
[WEB-2837]: https://tidepool.atlassian.net/browse/WEB-2837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2837] MRN minimum length adjustment hotfix

---

app/redux/utils/pendoMiddleware.js
package.json
test/unit/redux/utils/pendoMiddleware.test.js

[WEB-2839]
[WEB-2839]: https://tidepool.atlassian.net/browse/WEB-2839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2839] Add clinic plan limits info to Pendo

---

app/redux/actions/async.js
app/redux/constants/errorMessages.js
package.json
test/unit/redux/actions/async.test.js

[WEB-2855]
[WEB-2855]: https://tidepool.atlassian.net/browse/WEB-2855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2855] Handle patient limit reached errors on custodial account creation

---

Dockerfile
app/pages/signup/signup.js
package.json
test/unit/pages/signup.test.js

[WEB-2856]
[WEB-2856]: https://tidepool.atlassian.net/browse/WEB-2856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2856] Distinct keycloak registration urls

---

app/redux/actions/async.js
package.json
test/unit/redux/actions/async.test.js

[WEB-2857]
[WEB-2857]: https://tidepool.atlassian.net/browse/WEB-2857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2857] Update clinic patient count  UI when patient is added or patient invite accepted

---

app/redux/actions/async.js
package.json
test/unit/redux/actions/async.test.js

[WEB-2859]
[WEB-2859]: https://tidepool.atlassian.net/browse/WEB-2859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2859] Update limit UI on patient remove

---

app/core/forms.js
app/pages/clinicdetails/clinicdetails.js
package.json
test/unit/app/core/forms.test.js
test/unit/pages/ClinicPatients.test.js
test/unit/pages/clinicianedit.test.js
test/unit/pages/clinicinvite.test.js
test/unit/pages/share/ShareInvite.test.js

Addresses [WEB-2776] 
[WEB-2776]: https://tidepool.atlassian.net/browse/WEB-2776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2776] Clinic form validation fixes

---

app/components/clinic/ClinicWorkspaceHeader.js
app/components/clinic/PatientForm.js
app/components/elements/DatePicker.js
app/components/elements/DateRangePicker.js
app/components/elements/FontStyles.js
app/components/elements/MultiSelect.js
app/components/elements/Pill.js
app/components/elements/RadioGroup.js
app/components/elements/Select.js
app/components/elements/TextInput.js
app/pages/clinicdetails/clinicdetails.js
app/pages/patientnew/patientnew.js
package.json

[WEB-2862]
[WEB-2862]: https://tidepool.atlassian.net/browse/WEB-2862?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2862] Updates to address design review feedback

---

app/pages/clinicadmin/clinicadmin.js
package.json
test/unit/pages/clinicadmin.test.js

[WEB-2898]
[WEB-2898]: https://tidepool.atlassian.net/browse/WEB-2898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2898] Copy change

---

app/pages/clinicdetails/clinicdetails.js
app/redux/actions/async.js
package.json
test/unit/pages/clinicdetails.test.js
test/unit/redux/actions/async.test.js

[WEB-2922]
[WEB-2922]: https://tidepool.atlassian.net/browse/WEB-2922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2922] Fix newly-created clinic not getting UI details set

---

app/components/clinic/ClinicWorkspaceHeader.js
app/pages/clinicworkspace/ClinicPatients.js
app/themes/base/links.js
app/themes/baseTheme.js
package.json

Hotfix release for:
[WEB-2933]
[WEB-2933]: https://tidepool.atlassian.net/browse/WEB-2933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2933] Release 1.77.1 to master

---

app/components/clinic/RpmReportConfigForm.js
package.json

[WEB-2955]
[WEB-2955]: https://tidepool.atlassian.net/browse/WEB-2955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2955] Manually construct start and end dates to ensure desired calendar date is preserved regardless of time zone

---

package.json
yarn.lock

See [WEB-2959] and https://github.com/tidepool-org/tideline/security/dependabot/112
Related PR: https://github.com/tidepool-org/tideline/pull/438
[WEB-2959]: https://tidepool.atlassian.net/browse/WEB-2959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2959] Address @babel/traverse vulnerability

---

app/components/clinic/RpmReportConfigForm.js
package.json
test/unit/pages/ClinicPatients.test.js

[WEB-2978]
[WEB-2978]: https://tidepool.atlassian.net/browse/WEB-2978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2978] Add summary period to rpm report config

---

.travis.yml

Fix travis builds by removing buildx install step

Fix travis builds by removing buildx install step

---

app/bootstrap.js
app/components/clinic/BgRangeSummary.js
app/components/clinic/BgSummaryCell.js
app/core/constants.js
app/pages/clinicworkspace/ClinicPatients.js
app/themes/baseTheme.js
package.json
test/unit/app/core/constants.test.js
test/unit/components/clinic/BgRangeSummary.test.js
test/unit/pages/ClinicPatients.test.js
yarn.lock

[WEB-2992]
Related PR: https://github.com/tidepool-org/viz/pull/380
[WEB-2992]: https://tidepool.atlassian.net/browse/WEB-2992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2992] Add extreme hyper cgm summary stat

---

app/core/utils.js
package.json
test/unit/utils/utils.test.js

[WEB-2853]
[WEB-2853]: https://tidepool.atlassian.net/browse/WEB-2853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-2853] Use nearest Etc/GMT timezone from latestUpload.timezoneOffset if timezone is not available

---

app/components/clinic/ClinicWorkspaceHeader.js
app/pages/prescription/Prescriptions.js
package.json
test/unit/pages/Prescriptions.test.js

[WEB-3021] 
[WEB-3021]: https://tidepool.atlassian.net/browse/WEB-3021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3021] Show prescription access code in prescription table

---

app/pages/prescription/PrescriptionForm.js
app/pages/prescription/prescriptionFormConstants.js
app/pages/prescription/profileFormSteps.js
package.json
test/unit/pages/prescription/PrescriptionForm.test.js
test/unit/pages/prescription/prescriptionFormConstants.test.js

[WEB-3020]
Disables the calculator step if the selected pump is 'Palmtree', or all the available pumps have skipCalculator set to true 
[WEB-3020]: https://tidepool.atlassian.net/browse/WEB-3020?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3020] Disable ace calculator step for palmtree pumps

---

app/pages/prescription/PrescriptionForm.js
app/pages/prescription/accountFormSteps.js
app/pages/prescription/profileFormSteps.js
app/pages/prescription/reviewFormStep.js
app/pages/prescription/settingsCalculatorFormSteps.js
app/pages/prescription/therapySettingsFormStep.js
package.json

[WEB-3068]
I spent an inordinate amount of time trying to unit test this one, but the stepper form wrapper has proved to be difficult to navigate.  Given that this is considered a temporary solution/situation, and the plans to alter our testing approach, I felt it fine to forego unit-testing this change.
Happy to hear your thoughts if you have any pushback on this.
[WEB-3068]: https://tidepool.atlassian.net/browse/WEB-3068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3068] Skip device selection if only one pump and cgm option available

---

app/components/chart/settings.js
app/pages/patientdata/patientdata.js
test/unit/components/chart/settings.test.js
test/unit/pages/patientdata.test.js

addresses feedback resulting in [WEB-3082] and takes care of small adjustment for [WEB-3035] for very short pump settings duration ranges
[WEB-3082]: https://tidepool.atlassian.net/browse/WEB-3082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3035]: https://tidepool.atlassian.net/browse/WEB-3035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3082][WEB-3035] fetch _all_ uploads and adjust less than half day time range display

---

app/pages/prescription/PrescriptionForm.js
package.json

[WEB-3090]
[WEB-3090]: https://tidepool.atlassian.net/browse/WEB-3090?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3090] Don't persist to localstorage while doing single-step edits

---

app/pages/prescription/prescriptionFormConstants.js
package.json
test/unit/pages/prescription/prescriptionFormConstants.test.js

[WEB-3074]
[WEB-3074]: https://tidepool.atlassian.net/browse/WEB-3074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3074] Fix js error when a device guardrail is provided with a null value

---

app/components/clinic/TideDashboardConfigForm.js
app/core/forms.js
app/core/utils.js
app/pages/prescription/PrescriptionForm.js
app/pages/prescription/Prescriptions.js
app/pages/prescription/ScheduleForm.js
app/pages/prescription/prescriptionFormConstants.js
app/pages/prescription/prescriptionSchema.js
app/pages/prescription/profileFormSteps.js
app/pages/prescription/reviewFormStep.js
app/pages/prescription/settingsCalculatorFormSteps.js
app/pages/prescription/therapySettingsFormStep.js
package.json
test/unit/app/core/forms.test.js
test/unit/pages/Prescriptions.test.js
test/unit/pages/prescription/PrescriptionForm.test.js
test/unit/pages/prescription/ScheduleForm.test.js
test/unit/pages/prescription/prescriptionFormConstants.test.js
test/unit/utils/utils.test.js

[WEB-3108] [WEB-3109] [WEB-3111] [WEB-3112] [WEB-3120] [WEB-3123] [WEB-3155] [WEB-3162]
[WEB-3108]: https://tidepool.atlassian.net/browse/WEB-3108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3109]: https://tidepool.atlassian.net/browse/WEB-3109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3111]: https://tidepool.atlassian.net/browse/WEB-3111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3112]: https://tidepool.atlassian.net/browse/WEB-3112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3120]: https://tidepool.atlassian.net/browse/WEB-3120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …

Prescription flow tweaks [WEB-3108,WEB-3109,WEB-3111,WEB-3112,WEB-3120,WEB-3123,WEB-3155,WEB-3162]

---

app/components/clinic/TideDashboardConfigForm.js
app/core/forms.js
app/core/utils.js
app/pages/prescription/PrescriptionForm.js
app/pages/prescription/Prescriptions.js
app/pages/prescription/ScheduleForm.js
app/pages/prescription/prescriptionFormConstants.js
app/pages/prescription/prescriptionSchema.js
app/pages/prescription/profileFormSteps.js
app/pages/prescription/reviewFormStep.js
app/pages/prescription/therapySettingsFormStep.js
package.json
test/unit/app/core/forms.test.js
test/unit/pages/Prescriptions.test.js
test/unit/pages/prescription/PrescriptionForm.test.js
test/unit/pages/prescription/ScheduleForm.test.js
test/unit/pages/prescription/prescriptionFormConstants.test.js

Replaced by https://github.com/tidepool-org/blip/pull/1433
Leaving this untouched and deployed to QA1 for ongoing test study v&v

Prescription flow tweaks

---

app/components/chart/settings.js
package.json
yarn.lock

[WEB-3033] [WEB-3163]
Related PR: https://github.com/tidepool-org/viz/pull/405
[WEB-3033]: https://tidepool.atlassian.net/browse/WEB-3033?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3163]: https://tidepool.atlassian.net/browse/WEB-3163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3033,WEB-3163] Loop-specific therapy settings in device settings

---

package.json
yarn.lock

[WEB-3115] [WEB-3116] [WEB-3128]
Related PR: https://github.com/tidepool-org/viz/pull/406
[WEB-3115]: https://tidepool.atlassian.net/browse/WEB-3115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3116]: https://tidepool.atlassian.net/browse/WEB-3116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3128]: https://tidepool.atlassian.net/browse/WEB-3128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3115,WEB-3116,WEB-3128] Various loop data viz fixes

---

app/pages/prescription/prescriptionFormConstants.js
package.json
test/unit/pages/prescription/prescriptionFormConstants.test.js

[WEB-3207]
[WEB-3207]: https://tidepool.atlassian.net/browse/WEB-3207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3207] Remove cgm simulator option from prescription flow

---

package.json
yarn.lock

[WEB-3128] [WEB-3225] 
Related PR: https://github.com/tidepool-org/viz/pull/408
[WEB-3128]: https://tidepool.atlassian.net/browse/WEB-3128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3225]: https://tidepool.atlassian.net/browse/WEB-3225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3128,WEB-3225] Loop data viz fixes

---

package.json
yarn.lock

[WEB-3230]
Related PR: https://github.com/tidepool-org/viz/pull/409
[WEB-3230]: https://tidepool.atlassian.net/browse/WEB-3230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3230] Pdf JS error fix

---

app/core/forms.js
app/pages/prescription/PrescriptionForm.js
test/unit/app/core/forms.test.js

[WEB-3182]
[WEB-3182]: https://tidepool.atlassian.net/browse/WEB-3182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3182] Fix for some valid fields in future steps being removed when navigating back and re-submitting old steps 

---

app/core/api.js
app/redux/actions/async.js
package.json
test/unit/app/core/api.test.js
test/unit/redux/actions/async.test.js
yarn.lock

[WEB-3242]
Related PR: https://github.com/tidepool-org/platform-client/pull/176
[WEB-3242]: https://tidepool.atlassian.net/browse/WEB-3242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3242] increase prescriptions fetch limit

---

app/pages/prescription/prescriptionSchema.js

[WEB-3229]
[WEB-3229]: https://tidepool.atlassian.net/browse/WEB-3229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3229] Update birthday field validation to allow current date on prescription form

---

app/core/utils.js
app/pages/patientdata/patientdata.js
app/pages/prescription/prescriptionSchema.js
package.json
test/unit/utils/utils.test.js
yarn.lock

Release 1.81.1 to master

---

app/components/elements/Button.js
app/components/elements/Icon.js
app/pages/prescription/PrescriptionForm.js
app/pages/prescription/prescriptionSchema.js
app/pages/prescription/reviewFormStep.js
app/redux/actions/worker.js
app/themes/base/buttons.js
app/worker/PDFWorker.js
app/worker/index.js
config/local.example.js
package.json
test/unit/components/navbar/NavigationMenu.test.js
test/unit/pages/TideDashboard.test.js
test/unit/pages/prescription/prescriptionSchema.test.js
test/unit/redux/actions/async.test.js
test/unit/redux/actions/worker.test.js
test/unit/worker/PDFWorker.test.js
yarn.lock

[WEB-3110]
Related PR: https://github.com/tidepool-org/viz/pull/417
[WEB-3110]: https://tidepool.atlassian.net/browse/WEB-3110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3110] Add prescription print view to hotfix release

---

app/components/elements/Button.js
app/pages/prescription/PrescriptionForm.js
app/pages/prescription/prescriptionSchema.js
app/pages/prescription/reviewFormStep.js
app/redux/actions/worker.js
app/themes/base/buttons.js
app/worker/PDFWorker.js
app/worker/index.js
config/local.example.js
package.json
test/unit/components/navbar/NavigationMenu.test.js
test/unit/pages/TideDashboard.test.js
test/unit/pages/prescription/prescriptionSchema.test.js
test/unit/redux/actions/async.test.js
test/unit/redux/actions/worker.test.js
test/unit/worker/PDFWorker.test.js
yarn.lock

Release 1.81.2 to master

---

app/core/hooks.js
app/pages/prescription/therapySettingsFormStep.js
package.json

[WEB-3267]
[WEB-3267]: https://tidepool.atlassian.net/browse/WEB-3267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3267] Disable mouse wheel value updates while scrolling on number inputs

---

app/core/hooks.js
app/pages/prescription/therapySettingsFormStep.js
package.json

Release 1.81.3 to master

---

app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js
yarn.lock

[WEB-3083]
Related PR: https://github.com/tidepool-org/viz/pull/424
[WEB-3083]: https://tidepool.atlassian.net/browse/WEB-3083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3083] Ensure bgSource chartPrefs are set if missing on subsequent data fetches

---

app/core/clinicUtils.js
package.json
test/unit/pages/ClinicPatients.test.js

hotfix - remove MRN character count validation

Release 1.81.4

---

app/pages/dashboard/TideDashboard.js

Build currently failing:
`915:21  error    '_' is not defined`

[WEB-3336] - Resolve lodash import error

---

app/components/navpatientheader/DemographicInfo.js
app/components/navpatientheader/Name.js
app/components/navpatientheader/index.js
app/components/navpatientheader/navPatientHeaderHelpers.js
app/pages/app/app.js
test/unit/components/navpatientheader/index.test.js

[WEB-3343]
[WEB-3344]
WEB-3343 Description: When an account is claimed, the name,mrn,dob displayed does not update after editing when opened in the clinic patient list.
WEB-3344 Description: when clearing the mrn in the patient list, the mrn displayed when clicking on the patient row does not update to a blank value.
-----
Post-fix:
https://github.com/user-attachments/assets/a6af12a9-9468-46aa-bbcd-359bb41bb2aa
https://github.com/user-attachments/assets/394f8a9b-85f4-4189-bea6-fc4bd8ca0464
[WEB-3344]: https://tidepool.atlassian.net/browse/WEB-3344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3343]: https://tidepool.atlassian.net/browse/WEB-3343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3343, WEB-3344] - Navbar Demographics Not Updating Correctly

---

app/pages/share/AccessManagement.js
app/themes/base/tables.js

[WEB-3410]
[WEB-3410]: https://tidepool.atlassian.net/browse/WEB-3410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WEB-3410 - Add Missing Space in Access Management

---

app/components/chart/settings.js
app/components/datasources/DataConnections.js
app/pages/patientdata/patientdata.js
app/providers/AppBanner/appBanners.js
stories/Card.stories.js
test/unit/components/datasources/DataConnections.test.js

[WEB-3442]
[WEB-3442]: https://tidepool.atlassian.net/browse/WEB-3442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3442] Copy changes

---

app/components/chart/settings.js
package.json
test/unit/components/chart/settings.test.js

[WEB-3438]
[WEB-3438]: https://tidepool.atlassian.net/browse/WEB-3438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3438] Show all options in data connections modal on Devices view

---

app/providers/AppBanner/AppBanner.js

[WEB-3457]
Basically what it says, but I also added some additional for when to consider an action async result to be complete by adding a check against the previous monitored working state.  This extra safeguard is following the pattern we've used in `handleAsyncResult` in a number of other components to prevent extra firing of toast messages
[WEB-3457]: https://tidepool.atlassian.net/browse/WEB-3457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3457]Ensure that we only show toast messages in response to working state updates caused by banner interaction

---

app/components/chart/settings.js
package.json
test/unit/components/chart/settings.test.js

[WEB-3461]
[WEB-3461]: https://tidepool.atlassian.net/browse/WEB-3461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3461] Always-show-add-devices-button

---

package.json
yarn.lock

updates to twiist loop data filtering
viz PR: https://github.com/tidepool-org/viz/pull/444

[WEB-3428] twiist update

---

package.json
yarn.lock

[WEB-3474]
Related PR: https://github.com/tidepool-org/viz/pull/446
[WEB-3474]: https://tidepool.atlassian.net/browse/WEB-3474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3474] Hide twiist wizard bolus filters when empty

---

app/providers/AppBanner/AppBannerProvider.js

[WEB-3494]
[WEB-3494]: https://tidepool.atlassian.net/browse/WEB-3494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Admittedly I couldn't quite figure out how to generate these banners organically for testing the exact scenarios they come up, but I did test by modifying some variables and I'm quite certain everything here works as intended.
Also, my thought is that maybe we don't want to put in tests since it's only a temporary measure?

WEB-3494 - Hide specific banners when viewing on a mobile device

---

package.json
yarn.lock

[WEB-3030]
Related PR: https://github.com/tidepool-org/viz/pull/448
[WEB-3030]: https://tidepool.atlassian.net/browse/WEB-3030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3030] Fix Twiist Loop override durations

---

package.json
yarn.lock

[WEB-3396]
Missed adding this bit to my last PR for the ticket.
Related PR: https://github.com/tidepool-org/viz/pull/451
[WEB-3396]: https://tidepool.atlassian.net/browse/WEB-3396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3396] Use cgm sampleInterval property when available

---

package.json
yarn.lock

[WEB-3524]
Related PR: https://github.com/tidepool-org/tideline/pull/462
[WEB-3524]: https://tidepool.atlassian.net/browse/WEB-3524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3524] Show tooltip for mutable/incomplete boluses

---

app/components/datasources/DataConnections.js
app/components/datasources/DataSourceDisconnectDialog.js
app/themes/base/containers.js
app/themes/baseTheme.js
app/themes/colorPalette.js
package.json
test/unit/components/datasources/DataConnections.test.js
yarn.lock

[WEB-3516]
Related PR: https://github.com/tidepool-org/viz/pull/453
[WEB-3516]: https://tidepool.atlassian.net/browse/WEB-3516?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3516] Add post-disconnection instructions modal for abbott connections

---

app/components/chart/settings.js
app/components/datasources/useProviderConnectionPopup.js
app/pages/oauth/OAuthConnection.js
app/pages/patients/patients.js
test/unit/pages/OAuthConnection.test.js

There is an issue with redirecting back on mobile
https://tidepoolteam.slack.com/archives/C07F46SL6QZ/p1743968074258309

Fix missing provider when redirecting after successful Data Connection

---

package.json
yarn.lock

[WEB-3547]
Related PR: https://github.com/tidepool-org/viz/pull/458
[WEB-3547]: https://tidepool.atlassian.net/browse/WEB-3547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3547] Sample interval error fix for AGP prints

---

package.json
yarn.lock

[WEB-3546]
Related PR: https://github.com/tidepool-org/tideline/pull/463
[WEB-3546]: https://tidepool.atlassian.net/browse/WEB-3546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3546] Render extended bolusus under other boluses of same height

---

app/components/datasources/DataConnection.js
app/components/datasources/DataConnections.js
package.json

[WEB-3581]
[WEB-3581]: https://tidepool.atlassian.net/browse/WEB-3581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3581] Hide twiist disconnect button

---

app/components/chart/settings.js
app/pages/patientdata/patientdata.js
package.json
stories/Card.stories.js

[WEB-3590] 
[WEB-3590]: https://tidepool.atlassian.net/browse/WEB-3590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3590] Update data connection card copy

---

package.json
yarn.lock

[WEB-3631] 
Related PR: https://github.com/tidepool-org/viz/pull/467
[WEB-3631]: https://tidepool.atlassian.net/browse/WEB-3631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3631] twiist v3 pump settings

---

app/components/chart/settings.js
app/pages/patientdata/patientdata.js
package.json
test/unit/components/chart/settings.test.js
test/unit/pages/patientdata.test.js

[WEB-3633]
[WEB-3633]: https://tidepool.atlassian.net/browse/WEB-3633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3633] Data connection card copy change

---

app/components/datasources/DataConnections.js
package.json
test/unit/components/datasources/DataConnections.test.js

[WEB-3641]
[WEB-3641]: https://tidepool.atlassian.net/browse/WEB-3641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3641] Hide twiist no data message

---

app/pages/clinicdetails/clinicdetails.js
app/redux/reducers/working.js
test/unit/redux/reducers/working.test.js

[WEB-3650]
[WEB-3650]: https://tidepool.atlassian.net/browse/WEB-3650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3650] New clinic create form not redirecting

---

app/pages/clinicdetails/clinicdetails.js
app/pages/oauth/OAuthConnection.js
app/redux/reducers/working.js
package.json
test/unit/redux/reducers/working.test.js

Release 1.84.1 to master

---

package.json
yarn.lock

[WEB-3002]
[WEB-3002]: https://tidepool.atlassian.net/browse/WEB-3002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WEB-3002 - Change wording on tooltip label

---

app/pages/clinicworkspace/ClinicPatients.js
test/unit/pages/ClinicPatients.test.js

WEB-2367
Feedback from Design:
"I totally failed to define this in the Figma but would it be possible to hide the blue bar when no filters/search are applied? There are a few reasons for this: ...`

WEB-2367 - Design Feedback 1

---

app/pages/patientdata/patientdata.js
test/unit/pages/patientdata.test.js

[WEB-3657]
[WEB-3657]: https://tidepool.atlassian.net/browse/WEB-3657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3657] Only attempt to fetch clinics for patient if user is viewing own data

---

app/pages/clinicworkspace/ClinicPatients.js

[WEB-3573]
[WEB-3573]: https://tidepool.atlassian.net/browse/WEB-3573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Sorry Clint, missed this detail

WEB-3573 - Sort tags in dropdown

---

app/pages/patientdata/patientdata.js

[WEB-3454]
[WEB-3454]: https://tidepool.atlassian.net/browse/WEB-3454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WEB-3454 - Print PDF patient has wrong name for claimed accounts

---

package.json
yarn.lock

[WEB-3471]
Related PR: https://github.com/tidepool-org/viz/pull/470
[WEB-3471]: https://tidepool.atlassian.net/browse/WEB-3471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3471] One button boluses

---

package.json
yarn.lock

[WEB-3667] 
Related PR: https://github.com/tidepool-org/viz/pull/471
[WEB-3667]: https://tidepool.atlassian.net/browse/WEB-3667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3667] Rename Sequel device filter label to twiist

---

app/core/utils.js
app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js
test/unit/utils/utils.test.js
yarn.lock

- Add cbgFilter query parameter to backend API calls
- https://tidepool.atlassian.net/browse/WEB-3670

[WEB-3670] Add cbgFilter query parameter to backend API calls

---

app/pages/clinicworkspace/ClinicPatients.js
test/unit/pages/ClinicPatients.test.js

[WEB-3676]
[WEB-3676]: https://tidepool.atlassian.net/browse/WEB-3676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
New Behaviour:
https://github.com/user-attachments/assets/45196459-40ad-4660-920c-429ccabb03e0

WEB-3676 - Handle "Add Tags" button when MRN requirement not met

---

app/core/utils.js
package.json
test/unit/utils/utils.test.js
yarn.lock

[WEB-3501]
Addressing this feedback: https://tidepool.atlassian.net/browse/WEB-3501?focusedCommentId=67043
Viz: https://github.com/tidepool-org/viz/pull/476
[WEB-3501]: https://tidepool.atlassian.net/browse/WEB-3501?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WEB-3501 - QA Feedback 1

---

app/core/utils.js
app/pages/clinicworkspace/ClinicPatients.js
test/unit/utils/utils.test.js

[WEB-3573]
New abstracted sorting mechanism that could or will apply to everything (patient list, etc)
Related to new requirements around sorting: https://tidepool.atlassian.net/browse/PROD-264
[WEB-3573]: https://tidepool.atlassian.net/browse/WEB-3573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WEB-3573 - QA Feedback 2

---

app/components/chart/daily.js
package.json
test/unit/components/chart/daily.test.js

[WEB-3711] 
[WEB-3711]: https://tidepool.atlassian.net/browse/WEB-3711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3711] Disable one min cgm toggle

---

package.json
yarn.lock

[WEB-3688]
[WEB-3688]: https://tidepool.atlassian.net/browse/WEB-3688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3688] Generate suppressed basal data for twiist

---

app/redux/actions/async.js
package.json
test/unit/redux/actions/async.test.js

[WEB-3745]
[WEB-3745]: https://tidepool.atlassian.net/browse/WEB-3745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3745] Add one button bolus reason to dosing decision fetch filter

---

app/redux/utils/pendoMiddleware.js
package.json
test/unit/redux/utils/pendoMiddleware.test.js

[WEB-3767]
[WEB-3767]: https://tidepool.atlassian.net/browse/WEB-3767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3767] Send unique combinations of major/minor/patch semvers to Pendo for currentlyViewedDevices

---

package.json
yarn.lock

[WEB-3773] 
Related PR: https://github.com/tidepool-org/viz/pull/491
[WEB-3773]: https://tidepool.atlassian.net/browse/WEB-3773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3773] Re-enable hidden twiist bolus filters

---

app/components/chart/cgmSampleIntervalRangeToggle.js
package.json
test/unit/components/chart/cgmSampleIntervalRangeToggle.test.js
yarn.lock

[WEB-3825]
Related PR: https://github.com/tidepool-org/viz/pull/504
[WEB-3825]: https://tidepool.atlassian.net/browse/WEB-3825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3825] CGM sample interval label updates

---

app/pages/patientdata/patientdata.js
package.json
test/unit/pages/patientdata.test.js

[WEB-3828]
[WEB-3828]: https://tidepool.atlassian.net/browse/WEB-3828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3828] Ensure loading indicator is shown while fetching additional data through to when it's finished being added to the data worker

---

package.json
yarn.lock

[WEB-3836]
Related PR: https://github.com/tidepool-org/viz/pull/512
[WEB-3836]: https://tidepool.atlassian.net/browse/WEB-3836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3836] Max basal precision update

---

app/pages/dashboard/PatientDrawer/CGMDeltaSummary/index.js

[WEB-3883]
[WEB-3883]: https://tidepool.atlassian.net/browse/WEB-3883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3883] - Color Markers for TIDE Dashboard labels

---

app/components/elements/PopoverMenu.js
app/pages/clinicworkspace/ClinicPatients.js
app/pages/clinicworkspace/ClinicianPatients.js

[WEB-3965]
[WEB-3965]: https://tidepool.atlassian.net/browse/WEB-3965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WEB-3965 - Entire row of Pop Health / Essential / Private Workspace table is clickable

---

package.json
yarn.lock

[WEB-3964] 
Related PR: https://github.com/tidepool-org/viz/pull/535
[WEB-3964]: https://tidepool.atlassian.net/browse/WEB-3964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3964] Limit alarms shown

---

package.json
yarn.lock

[WEB-3974] Additional alarm copy changes
Related PR: https://github.com/tidepool-org/viz/pull/538
[WEB-3974]: https://tidepool.atlassian.net/browse/WEB-3974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[WEB-3974] Additional alarm copy changes

---

app/pages/clinicworkspace/ClinicianPatients.js
app/pages/patientdata/patientdata.js
app/redux/utils/pendoMiddleware.js
package.json
test/unit/pages/patientdata.test.js
test/unit/redux/utils/pendoMiddleware.test.js
yarn.lock

Related PR: https://github.com/tidepool-org/viz/pull/534

Release 1.88.4 to master

---

app/pages/dashboard/TideDashboard.js

[WEB-3890]
[WEB-3890]: https://tidepool.atlassian.net/browse/WEB-3890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

WEB-3890 - Tide Dashboard passes extreme high visibility flag to BgSummaryCell
