app/components/chart/modalsubnav.less, app/core/less/variables.less, package.json
In conjunction with [tideline PR #197](https://github.com/tidepool-org/tideline/pull/197). That should be merged and tagged first, then this PR updated.
At present, the sub-navigation for selecting and deselecting days of the week - in particular, the dark text for weekday abbrevs on the darker turquoise - does not meet our accessibility requirements for text contrast:
I attempted a quick solution (make the day of week text white for weekdays), but I don't think it works very well:
(White text on the weekend color also fails our accessibility requirements.)
Further input required to move forward... Ping @skrugman @brandonarbiter
=> two-tone color scheme for trends view days of the week

app/components/navbar/navbar.less
@jebeck @skrugman 
Quick change to move the white arrow in the dropdown menu of the navbar to line up under the blue down arrow. 
Resolves: https://trello.com/c/z7iYok6F
=> Moves the white dropdown menu up arrow so it aligns with the blue arrow in the navbar

app/components/chart/daily.js, app/components/chart/header.js, app/components/chart/modal.js, app/components/chart/weekly.js, app/pages/patientdata/patientdata.less
This PR abbreviates the dates shown in daily, weekly, and trend views of patient data. 
@jebeck @skrugman 
To tighten the position of the arrows, I removed a large block element that surrounded the dates in each view. When you test this, you'll notice that this causes the arrows to bounce slightly as the width of the date string changes. In my testing, I found that you can still click the arrows repeatedly to move forward or backward in time without losing focus. 
If the slight jump/bounce of the arrows is undesirable, I can create CSS rules for each view that will reintroduce the block around the date, just a bit tighter than before when there was one block for all views. 
Let me know how you'd like me to proceed!
Resolves: https://trello.com/c/RELPBpRy
I agree to the terms of Tidepool …
=> Abbreviates dates in the patient data charts and brings arrows in closer.

app/components/navbar/navbar.less
@skrugman @jebeck 
This PR removes the shadow from the dropdown menu and adds a light gray border around it. The change took a bit more time than I thought since you have to do some CSS magic to get an outline around that triangle in the menu. I've tested my change in Chrome, Safari, and Firefox to make sure it's working cross-browser and it looks good.
Resolves: https://trello.com/c/Y5eXAWyQ
=> Light gray outline added to the navbar dropdown menu.

app/components/patientcard/patientcard.less
@skrugman @jebeck 
This PR updates the patient card component in two places: 
1) On the patients page, the bold hover effect has been removed from the View|Share|Upload links to make navigation less jumpy. 
2) On the patient data page, the patient name and icon (in the patient card component in the navbar) now has a light blue green hover effect with an underline for the patient name for consistency with other text links in the site. 
Per @skrugman, in the future, we'll look for better affordances for indicating hover than the outline, but this will be good for accessibility for the time being. 
Resolves: https://trello.com/c/W6OCIaCY
=> Link cleanup for the patientcard component

app/app.js, app/core/api.js
this relates an error seen when a session times out, then the user clicks "log out", the app hangs. It should re-direct to the login page.
@jebeck if you could have a quick look?
=> ignore error on logout and destroy the session

app/pages/patients/patients.js, app/pages/patients/patients.less
@skrugman @jebeck 
This PR removes the white box background from the welcome screen and aligns the two buttons on the screen (instead of stacking them). 
One other change I made was to use the 'gray-text' style instead of 'gray-dark'. The contrast between the gray background and gray text was too hard to read. The 'gray-text' style uses a slightly darker gray that's much easier to read. I hope this is okay. 
Resolves: https://trello.com/c/DVAEVnEC
=> Removes white background and lines up buttons on welcome screen.

app/components/peoplelist/peoplelist.js, app/core/personutils.js
@jh-bate 
This PR fixes functionality that determines whether the 'Remove people' link should be shown. The original code (editControls, editablePersonExists) was incorrectly always showing the link because it was looking for the existence of admin perms, which are always there - because the logged in user has admins perms for their own account. 
To get this working, I added an .isRemoveable function to core/personutils.js that, when passed a person, checks to ensure that the perms aren't empty and their they're not root and not admin. If that is true, then it's a person the user has view/upload/etc rights for. When that is the case, the remove button should be shown onscreen. 
Resolves: PR: https://trello.com/c/1YFnGntX
=> Only show "Remove People" link when there's an account displayed that the user does not own.

app/app.js
This change picks up on a stale PR (https://github.com/tidepool-org/blip/pull/164) which had some logic problems. 
The approach is pretty simple, whenever we call redirectToDefaultRoute, we call showPatients, which now sets a state called canSkipPatients as true.
In the renderPatients function, when we see that canSkipPatients flag, we do some checks to make sure data has loaded, then figure out how many people the user can view data for - then direct them to either the patients page or patient data page. After stepping carefully through all the cases (if you're a patient, caregiver, etc.) and the permissions you have for various other users, the logic I arrived at it pretty simple: 
Providing the user has no pending invites, if there is only patient (including the user themselves) the …
=> Determine whether to render the Patients or skip and go directly to Patient Data

webpack.config.js
@kentquirk @jebeck 
Updates the webpack config to use the file loader which allows you to specify a name for a file in a build so that it's not hashed like most other assets.  
Resolves: https://trello.com/c/iQwJAoxZ
=> Fixes webpack configuration for favicon.ico

app/app.js, app/components/notification/notification.js
Sarah's jshint mysteriously broke -- it seems React has now added an object called Notification, which conflicts with ours. So I've renamed it TidepoolNotification.
I didn't see this problem until I deleted my node_modules and reinstalled them. Then jshint started failing.
=> Rename Notification; it seems React now has one

app/components/navbar/navbar.less
@jebeck 
By making the navbar icons larger in an earlier change the other week, the spacing allotted for username length was reduced by several pixels causing wrapping of the menu section. 
To fix this, I removed extra padding created by the ul element automatically, which reduced the amount of space left for layout in the div. I also reduced the allotted space for a username by 10px. I've tested this change with extremely long and short names in Safari, Chrome, and Firefox to ensure our previous changes to align arrows and increase sizes were not effected. Everything checks out. 
Resolves:  https://trello.com/c/y9MIvhtH
=> Fixes long name layout issues.

app/app.js, app/router.js
@jh-bate @kentquirk 
This PR is the first of a two parter to fix a bug that occurs when a user clicks the "reset password" link from the Chrome Uploader. Today, when a user clicks that 'reset password' link, they are taken from the uploader to Blip and if they're logged in, you are redirected to the /patients by default. 
To resolve this bug and make future external requests a bit easier to manage, I made some changes that allow us to support URLs that will route to different locations based on whether a user is logged in or out. 
For the Chrome Uploader, reset password link bug, the solution will be to change the reset password link to a new URL (request-password-from-uploader) rather than the default 'request-password-reset'. When the user clicks that link in the Uploader, if they are …
=> Adds ability to route an external request to different app location based on whether the user is logged in or out.

app/app.js, app/components/messages/__tests__/messages-test.js, app/components/messages/message.js, app/components/messages/messages.js, app/preprocessor.js, package.json
I believe this addresses both bugs recently found on staging: https://trello.com/c/2I11ddBi and https://trello.com/c/0zfGV7oG.
The issue is that `_.first` does not return an array, and we were trying to extract from it at index 0. Possibly/probably(?) this is a change in lodash and came in with the dependency updates.
Ping @kentquirk
=> lodash _.first doesn't return an array

app/components/messages/__tests__/message-test.js, app/components/messages/message.js, package.json
Nick found another regression - edited note text wasn't displaying until after closing and reopening the note. `git blame` showed yours truly to blame for the regression :/
Ping @jh-bate for a quick review.
No regression test at the moment, could add one since I've already got started on Jest stuff for this component. LMK what you'd prefer @jh-bate.
=> make sure edited note text is rendered right away

app/app.js, app/pages/patientdata/patientdata.js
@jh-bate I believe this fixes the issue, and I hope I found all the uses of patient data so I'm not creating new bugs by changing what the prop looks like. I'd definitely appreciate another pair of eyes taking a close look to trace through uses of `patientData` as a prop to make sure nothing's been left out.
My plan is to try to get this fix in ASAP. On a separate branch I am pulling in @GordyD's work so far and there I will try to start working on (a) a regression test and (b) the clean up on `app/components/peoplelist.js` that we discussed (i.e., getting rid of the attempt to mutate props).
P.S. A side benefit of this change is it paves the way quite nicely for caching data that's already been fetched so we don't refetch every time you navigate between people :)
=> store patient data in hash under userid to prevent name + data mismatch

app/app.js
This fixes the issue I found on staging after deploying #230 yesterday. It turned out the `_.cloneDeep` I'd added was hanging the browser for *seconds* when there was actually something already in `this.state.patientData` (understandably, because it was deep-cloning all of the device data). The deep clone isn't actually necessary here, so I changed it to `_.clone`, and that works.
As a reminder, the issue on staging was this: log into an account, go to view data, navigate away (first data fetch still happening in background), navigate to view away (second data fetch starts), and then navigate away again, to the edit profile page. I noticed I couldn't keep editing my profile after a bit - app was frozen. In the console it was apparent this was happening after both the first and second data …
=> get rid of long browser hang

app/app.js, app/pages/patientdata/patientdata.js
In testing the fix originally implemented in #230 @NSRiggall was getting some crashes occasionally when fetching data (reported [here](https://trello.com/c/HUPEouyS)). After talking with him and also experiencing similar myself on devel yesterday when tide-whisperer was timing out completely on data requests, I think the change in this pull request handles the issue by more gracefully recognizing when the server doesn't respond with data.
Still going to try to have a look in the logs to see if I can tell that this is the same issue as @NSRiggall was experiencing, but it may be difficult because of the weird stringification of blip errors that we haven't fixed yet in the logs...
=> handle two crashing scenarios possible because of data + name mismatch fix

app/app.js, app/components/chart/daily.js, app/components/chart/modal.js, app/components/chart/settings.js, app/components/chart/weekly.js, app/pages/patientdata/patientdata.js
This isn't as sophisticated as I'd hoped. It's a chicken-and-egg problem to add the timezone to the data-viewing URL when we don't know what timezone to display in until *after* we've loaded the data and found the most recent metadata object with a timezone.
So:
- if a timezone is in the query params before the hash (e.g., `?timezone=US-Pacific#/`), that timezone takes precedence
- otherwise, blip defaults to the timezone from the most recent upload metadata for display, but this timezone will *not* be displayed in the URL (the only way to do that requires either a full page refresh and re-fetch of data (if in query params) or setting a new route and thus re-fetching data) :(
We could just take the setting of the timezone via query params away now, **but**:
- most people won't know it's …
=> default to the timezone from the most recent upload metadata for display

app/app.js, package.json
Depends on [tideline 213](https://github.com/tidepool-org/tideline/pull/213). Once that's merged and tagged, will update tideline version in package.json here.
This makes the default BG display in mg/dL, with the option to switch to mmol/L by putting a query parameter `units=mmoll` before the hash (`#`).
=> default to mg/dL for display of BG values (but allow change to mmol/L through query param)

app/components/invitation/invitation.js, app/components/messages/message.js, app/components/modaloverlay/modaloverlay.js, app/pages/patient/patient.js, app/pages/patient/patientteam.js, app/pages/patients/patients.js, test/unit/components/messages/message.test.js, test/unit/pages/patient/patient.test.js
Hi,
When I was checking out your app I noticed some warnings in the console and here is a patch to fix them. Do let me know if there is a better option than targeting this branch - I don't know the codebase well so I wanted to include test coverage to validate that my changes weren't breaking anything, and the best place to accomplish that at the moment was in this branch (as I wasn't able to run tests effectively in master).
- removed usage of 'transferPropsTo'
- changed React.PropTypes.renderable -> React.PropTypes.node
- removed unused property 'patientsComponent'
- added test coverage for the changes
Issue: #228
=> eliminate React warnings re: api deprecation and increase test coverage

app/app.js, app/components/messages/message.js, app/components/messages/messageform.js, app/components/messages/messagemixins.js, app/components/messages/messages.js, app/pages/patientdata/patientdata.js, package.json
Fixes display and editing of timestamps on notes for new default to timezone-aware display.
Depends on [tideline #217](https://github.com/tidepool-org/tideline/pull/217).
=> timezone-aware bugfixes for notes

package.json
Fun times. After I merged #240, I did a `git pull` on master to get the merged in update, then I cleaned out my node modules and did a fresh install just to do a final check before tagging. After the clean install, the `npm start` script was failing. The build (i.e., `npm run build`) was still working, but...not good to not be able to run locally.
We've been getting some autoprefixer warnings for a while, and I've been bitten before by the fact that even though *we* lock down our dependencies, if one of our deps doesn't lock down *its* dependencies, that can break things. (This happened to me once with Jest.)
So my theory is that's what happened. I went through and updated *all* of our webpack-related dependencies (with the help of [this …
=> update build-related dependencies

app/core/actionhandlers.js, app/userMessages.js
I managed to produce this error from the uploader (by clicking Go to Blip for a user that the user I had logged into blip w/Remember Me did not have access to). I noticed a grammatical mistake in the error message ('your' instead of 'you're') and fixed it here.
CC @darinkrauss @jh-bate
=> fix grammar in new authorization error message

app/components/app/app.js, test/unit/components/app.test.js
What you had in mind @GordyD?
I think for each smart component may have to decide how many batches of tests to do. Here it made sense to do one batch on the initial (not logged in) state and one batch on the post-logged-in state since the mappings are a bit different.
=> test mapStateToProps for app.js

package.json, test/unit/redux/reducers/allUserMap.test.js, test/unit/redux/reducers/membersOfTargetCareTeam.test.js, test/unit/redux/reducers/membershipPermissionsInOtherCareTeams.test.js, test/unit/redux/reducers/messageThread.test.js, test/unit/redux/reducers/notification.test.js, test/unit/redux/reducers/patientDataMap.test.js, test/unit/redux/reducers/patientNotesMap.test.js, test/unit/redux/reducers/pendingReceivedInvites.test.js, test/unit/redux/reducers/pendingSentInvites.test.js, test/unit/redux/reducers/permissionsOfMembersInTargetCareTeam.test.js
- Add object-invarient-test-helper to package.json
- Use object-invariant-test-helper in all reducer tests to ensure state is not mutated
=> Add helper and tests for tracking mutations

package.json
What it says on the tin. Sign-off @jh-bate?
=> rev tideline version to v0.4.10 for active basal sched display

app/routes.js, test/unit/routes.test.js
During the testing of the blip w/redux RC, it was discovered that it was possible to navigate directly to /patients/new without having accepted the TOS and Privacy Policy first. Here is the fix, including regression tests.
@GordyD review plz.
=> modify requireAuthAndNoPatient to redirect to /terms as appropriate

app/components/peoplelist/peoplelist.js, test/unit/components/peoplelist.test.js
When displaying a list of patients whose data you are able to view we need to ensure the list is sorted by the patient's name rather than the name associated with the profile that manages the patient. This commit updates the sorting rules and adds a new test condition to ensure that this property is used when the patient isOtherPerson flag is set to true.
=> Account for patient being other person

package.json, test/unit/redux/actions/async.test.js, test/unit/redux/reducers/showingWelcomeMessage.test.js
- Update API usage of `redux-mock-store` due to breaking changes
- Fix buggy tests that were not failing due to being caught out by old interface
- Address suppressed bug in showWelcomeMessage.test.js where state was declared twice
=> Update redux-mock-store to new version

app/redux/utils/trackingMiddleware.js
This metric will also be fire before login, but we can't push metrics until after login. This PR therefore removes the metric for greatest code readability.
=> remove a metric that will never actually get recorded

package.json, webpack.config.js
Fixes the issue with the app crashing on IE post-redux migration.
@krystophv have a brief look-see?
=> get Object.assign through babel-runtime

app/components/waitlist/waitlist.js
@jebeck @jh-bate @krystophv Can you please do a quick review? At my request, @brandonarbiter updated the Typeform URL from brandon72.typeform.com to tidepool.typeform.com for the clinic survey, but that also changed the sign up URL. The old one is still working and may continue to work, but I'm a little nervous that it may stop if/when typeform updates DNS and propagation occurs.
Thanks!
=> Updated to new tidepool URL for typeform

config.webpack.js
Ping @jh-bate for review. Just an oversight after I ended up creating a new webpack config for just the config bundle with the updates work.
=> add back `library` option that exposes the bundle on `window` (crucially)

webpack.config.js
Looks like 'app.js' was being used for both dev and prod for a while, and it was only when I separated out the config bundling that it surfaced as a problem...somehow.
As discussed with @darinkrauss, in the near future (possibly on the 🛩 tomorrow) I'll try to do the hour or so work it would take to cleanly separate the dev and prod webpack configs (as I've seen in quite a few React app boilerplates) so that it's easier to read and something like this doesn't happen again.
Ping @darinkrauss for review?
=> point to the correct of app/main.(prod.)js

webpack.config.js
So the problem that we were having was that dependencies in the resolve tree were defaulting to their own local node_modules directory first (since that's the way that the resolver generally works). By setting the reaolver.root property, we tell webpack that it should check blip's node_modules before anything else, so if a dependency can be resolved locally, it is. We can also use resolver.alias in order to do one-by-one resolutions, but unless I'm mistaken, we'd prefer to have any dependency that's available in blip to be the one that's used.
=> add local node_modules as root resolve path

app/components/chart/settings.js
The grouped patientData is sorted by date ascending, so the first index will be the earliest available. We want the latest available instead.
=> grab last settings instead of first

.travis.yml, app/components/waitlist/waitlist.js, package.json
Update Typeform link with newest from Brandon.
Disable failing Nightwatch tests in Travis. No obvious change or misconfiguration caused it; it seems to be on Travis' end. So, we decided to disable for now.
@jh-bate @krystophv @jebeck Since this repo is now locked, could one of you provide a review when you have a moment?
=> Update Typeform link, disable Nightwatch tests

app/components/chart/settings.less, app/core/less/scaffolding.less, app/pages/login/login.less, app/pages/patient/patient.less, app/style.less, package.json
What it says on the tin 😆
In response to a user support request, this restores the ability to select & copy text from device settings.
When [viz #27](https://github.com/tidepool-org/viz/pull/27) is approved and published to npm, this branch should get the updated version in the package.json.
=> get rid of all screwing around with 'user-select' property

app/components/chart/settings.js, app/pages/patientdata/patientdata.js, package.json, test/unit/components/chart/settings.test.js
Companion branch to [viz #31](https://github.com/tidepool-org/viz/pull/31), nothing huge to comment on here, should be fairly self-explanatory I think.
=> persist state of open/collapsed basal schedules (or settings profiles, for Tandem devices)

app/components/patientcard/patientcard.js, app/components/patientcard/patientcard.less, package.json, test/unit/components/patientcard.test.js
Updates the `Patient Card` component to better align visual affordances (i.e., "View" link appearance changes when entire card was hovered hovered over, but wasn't clickable) with real interactions:
- Patient avatar icon now clicks to "View" page
- Patient full name also clicks to "View" page
- Hovering over either of these highlights/activates "View" link hover state
- Pointer cursor removed from `.patient-list-item`, since the entire area is not interactive
Also updated CSS and unit test to support these changes. See [Trello card](https://trello.com/c/LNsakXUO) for more info.
/cc: @krystophv @jebeck @jh-bate
=> Patient card interactions

app/pages/patientdata/patientdata.js, package.json, test/unit/pages/patientdata.test.js
We neglected to add metric tracking to a new Blip Notes link on the improved main upload button (PR #345), so here it is! See [Trello card](https://trello.com/c/cb5ujwjI/) for more info.
/cc: @krystophv @jebeck @jh-bate
=> Add metric tracking to Blip Notes link

package.json
I merged master **after** tag v0.14.20 was created, so we're creating a new tag (v0.14.21) to include v0.14.19. Phew! 😅
=> Fix missing v0.14.19, from v0.14.20, with v0.14.21

README.md
=> Fix typo in signup confirmation URL query parameter in the README.md

app/redux/containers/Root.dev.js, package.json, webpack.config.js
I did it @krystophv!!! 🎉 🎊 🎉
We just weren't using webpack right /o\
This PR also contains the addition of the React Perf addon in dev (attached to `window` so you can use in the console, as described e.g., here: http://benchling.engineering/performance-engineering-with-react/). Sticking it in the redux dev mode `<Root />` component seemed like the easiest way (to me) to keep it out of prod, but LMK if you can think of a cleaner way.
@hntrdglss for context: @krystophv noticed a while ago that we were clearly still using the dev build of React in production because propTypes validation shows up all over any perf profiles...
=> perf stuff

package.json
Updates Tideline to v0.5.14, which includes calendar hovers and metrics. See [Trello card](https://trello.com/c/a9tHEqoK/) for more info.
=> Tideline v0.5.14 - calendar hovers and metrics

app/components/chart/modal.js, package.json
What it says on the tin - some documentation/further explanation forthcoming about need to track previous dates shown in order to get expected/desired animation behavior.
Goes with [viz #40](https://github.com/tidepool-org/viz/pull/40).
=> track the previous domain (for exit animations) when switching between 1, 2, & 4 weeks

app/pages/app/app.js, app/pages/patientdata/patientdata.js, app/pages/patients/patients.js, app/pages/share/share.js, app/redux/store/configureStore.dev.js, package.json, test/unit/app/app.test.js, test/unit/pages/emailverification.test.js, test/unit/pages/login.test.js, test/unit/pages/passwordreset/confirm.test.js, test/unit/pages/passwordreset/request.test.js, test/unit/pages/patientdata.test.js, test/unit/pages/patientnew.test.js, test/unit/pages/patientprofile.test.js, test/unit/pages/patients.test.js, test/unit/pages/share.test.js, test/unit/pages/signup.test.js, test/unit/pages/terms.test.js, test/unit/pages/userprofile.test.js, test/unit/pages/verificationwithpassword.test.js
A fix that gets more to the root of the problem than #390 
As discussed @jh-bate I have a bit more to add on this:
But please try it and see if it solves the issue for you!
Fuller explanation of this bug:
@jh-bate discovered a bug where blip was crashing on some accounts he had in the situation where of the three requests made when hard refreshing (w/remember me) on the data view route (/patients/:id/data) route, the fetch patient (profile, etc.) and fetch patient data requests were coming back prior to the fetch *user* request. This is pretty unusual and I'd guess is connected to very little data being present in the accounts in question. (That doesn't explain why the fetch patient is beating the fetch user request back, but `¯\_(ツ)_/¯`.)
The patient data view renders the loading GIF …
=> bugfix race condition state tree

.travis.yml, app/components/chart/basics.js, app/pages/patientdata/patientdata.js, app/redux/reducers/misc.js, test/unit/pages/patientdata.test.js, test/unit/redux/reducers/membershipPermissionsInOtherCareTeams.test.js
Changes involved:
- membershipPermissionsInOtherCareTeams reducer handles FETCH_PATIENT_SUCCESS so that hard refresh works
- PatientData extracts permsOfLoggedInUser appropriately depending on whether logged-in user is the patient in view or not and passes it through to the Basics (goes with [tideline PR #306](https://github.com/tidepool-org/tideline/pull/306))
- tests for both of these changes, natch
=> restore VCA ability to change site change source if still custodian

app/core/api.js, package.json
Apparently another bug exists on the backend, where multiple metadata calls results in a race condition that causes, in essence, the profile to be knocked out by the preferences fetch. By changing `async.parallel` to `async.series`, we hope that profile will be fetched first, followed by preferences. See https://tidepoolteam.slack.com/archives/eng/p1487964878001211 for more info.
=> Switch api.user.get from parallel to series

app/components/peopletable/peopletable.js, package.json
@jebeck discovered when resolving this "child account" issue https://trello.com/c/NMr0pTEF. We were displaying the account owners name not the associated patient (aka child account) name.
=> fix display name to be fullname of pwd

.gitignore, .travis.yml, deploy-env.sh, deploy.sh, start.sh
@jebeck @jh-bate @pazaan Adds "deploy" process which builds "binary" artifact for later deployment. Update start script to utilize the targeted version of node. Uses shared environment variable to ensure artifact build and deployed execution use same exact version of node.
To move to a new version of node, we will need to: 1) update infrastructure configuration to automatically install new target version (outside of blip); 2) update `travis.yaml` here to include target version (under `node_js:`); and 3) update `deploy-env.sh` to specify target version used to build artifact and run service.
=> Create deploy artifacts via Travis; update start script to use node version

.gitignore, .travis.yml, deploy-env.sh, deploy.sh, package.json, start.sh
Ping @jh-bate and @krystophv 
Can you think of anything I missed? Updated .travis.yml and "engines" in the package.json. Didn't look like we mentioned version of node anywhere in README
Not sure if we have `engines` in tideline and viz, but I'll check.
=> updates for blip to be built/run with node v6.x LTS

app/components/chart/trends.js, package.json
What it says on the tin. Since this is such a small change, I figure we can merge whenever and just check that target range is set properly on Trends page in whatever release it goes out with. Lemme know if you disagree @krystophv
=> use viz's reshapeBgClassesToBgBounds function

app/core/api.js, app/core/utils.js, app/pages/signup/signup.js, app/redux/utils/trackingMiddleware.js, package.json, test/unit/redux/utils/trackingMiddleware.test.js, test/unit/utils/utils.test.js
@jebeck @jh-bate @krystophv This allows the signup URL to accept a new parameter `roles` (a comma-delimited array of strings, with `clinic` as the only valid value) that will automatically pass that to the create user call on the backend (`platform-client` has already been updated to pass `roles` through). The net result is that by specifying the `roles` parameter on the URL an account can be created that is immediately a VCA.
After this feature (and `shoreline`) is deployed, but prior to the new clinic signup workflow deployment, we will update the signup TypeForm to allow the user to immediately signup (with the `inviteKey` and optional `roles` parameter depending upon how they answer some of the TypeForm questions). There will be a redirect involved (with the redirect service in our …
=> Allow clinic role to specified on signup; update platform-client

app/components/peopletable/peopletable.js, app/components/peopletable/peopletable.less, app/pages/patients/patients.js, package.json, test/unit/components/peopletable.test.js, test/unit/pages/patients.test.js
@jebeck @jh-bate When you signup with a clinic account (with "&roles=clinic" on signup url) you now get automatically shared with the Jill Jellyfish account. With the existing logic, that means when you login for the first time, you end up going right into the one account you are associated with. Instead, we want to land on the Patient List screen (that's the change in `patients.js`).
Furthermore, as a first landing page immediately after signing up, the Patient List really gives no instructions so we add some here.
=> Display instructions in People List if not searching or showing all

app/components/chart/trends.js, package.json
What it says on the tin. Depends on [viz #71](https://github.com/tidepool-org/viz/pull/71).
=> standardize on passing through bgPrefs with bgUnits and bgBounds inside

app/components/inputgroup/inputgroup.js, app/components/inputgroup/inputgroup.less, app/pages/patientnew/patientnew.js, app/pages/patientnew/patientnew.less, package.json, test/unit/pages/patientnew.test.js, yarn.lock
Adds the option to share data with the BDDP and specify one of a number of nonprofit partners with which to attribute the proceeds.
This necessitated the addition of a `renderSelect` addition to the `SimpleForm` system, as it previously had no notion of select elements.
=> adding bddp option to DSA signup

package.json, yarn.lock
Coincides with https://github.com/tidepool-org/tideline/pull/317
=> Extendeding no bolus period limit for aggregating data from 24 to 72 hours

webpack.config.js
i.e., when `DEV_TOOLS` env variable is unset/undefined.
Unless y'all made a conscious decision to disable them by default? In which case (but I suspect not since I found the regression [here](https://github.com/tidepool-org/blip/commit/dc7ec489699fb5f12bdd285c669f728c674c264f#diff-11e9f7f953edc64ba14b0cc350ae7b9d)), just lemme know and I'll do a PR to update the README for you.
(I have an ulterior motive for fixing this: a small 🐛  that crashes the app in dev mode only (due to the mutation tracker). So look for that fix soon 😉 )
=> restore dev tools by default 

package.json, yarn.lock
On the basics view, remove the 'Manual' bolus filter, and separate the the 'Overrides' filter into 'Overrides' and 'Underrides'
see https://trello.com/c/pQaZdjad for full details.
Pulling in changes from https://github.com/tidepool-org/tideline/pull/320
=> Distinguishing bolus override up from override down in basics view

package.json, yarn.lock
Libre CBG data is not being calculated in a number of locations due to having an insufficient number of data points collected in a day.
This is because the minimum data thresholds are all based on getting a certain percentage of the day covered, based on getting a new reading every 5 minutes.  The Libre, however, only gets readings every 15 minutes, so we have to reduce the minimum amount of readings expected for Libre data threefold.
This PR only pulls in updated versions of `tideline` and `@tidepool/viz` which contain the actual fixes.
See https://trello.com/c/FNlDqd1A for details.
Goes hand-in-hand with:
https://github.com/tidepool-org/viz/pull/96
https://github.com/tidepool-org/tideline/pull/326
=> Libre data not being calculated due to insufficient data points

app/pages/patientdata/patientdata.js, package.json, test/unit/pages/patientdata.test.js
Since the possibility now arises for the initial set of data queued up for processing includes renderable diabetes data but no `upload` records, we end up in a situation where we avoid checking for which chart type we need to display. However, the system is already built to handle this case and will check for the latest data point's type in order to determine which chart to display in the event that it cannot get the type from the latest upload record, so we can safely default to an empty array should the `upload`s not exist on the `grouped` data.
This also copies a set of unit tests for determining the default chart to display and alters them such that we don't pass in a set of upload records to ensure that they have the same behavior as was already established in the application.
=> Chart selection hotfix

app/pages/patientdata/patientdata.js, package.json
See https://trello.com/c/dr9EeALW
The changes made for the data paging/processing feature meant that at the time the initial print view generation was called, it was not yet set to state in the PatientData instance.
I've changed it to use the incoming `nextState` as supplied from the `componentWillUpdate` hook.
This is actually how I'd intended it to work when the initial print view was released.  I simply forgot to change one instance of `this.state` to `state`.
=> Ensure we use up-to-date state timeprefs for daily print view

app/components/chart/daily.js, package.json, yarn.lock
See https://trello.com/c/OKj6Qyji for details.
Related PRs:
tidepool-org/tideline#338
tidepool-org/viz#107
This PR is required due to a side effect of a rounding fix applied to the tideline PR in the nurseshark plugin that was rounding the BG values when converting from the stored `mmol/L` values to `mg/dL` prior to categorization.  
This PR simply passes the `bgPrefs` in to the BolusTooltip component to allow BG formatting there.
=> Update glucose defaults to reflect standards

README.md
I was trying out the new docker-based development setup, and it wasn't immediately obvious for me how to bypass the email verification step there. Added some instructions to the README, hoping they will help someone else.
=> Add email verification bypass info for Docker setup

app/components/chart/header.js, app/pages/app/app.less, app/pages/patientdata/patientdata.js
Tweak the CSS so that the current date range is visible in the @print media renderer.  This is a stop-gap until there are proper print views for all visualizations.
=> Display date range when using browser print functionality

package.json, yarn.lock
Updated `tideline` dependency to disable `bg/out-of-range` annotations being rendered the old way. 
tideline PR: https://github.com/tidepool-org/tideline/pull/356
Trello card: https://trello.com/c/pQv4sTKV
=> Disable bg annotation

app/components/chart/bgLog.js
https://trello.com/c/bsnBhR7g/701-page-reload-when-switching-to-basics-from-empty-weekly-view
=> stop reload switching from weekly to basics view with no data

server.js
This adds a new subdomain to the CSP config to allow integration testing in this subdomain.
=> Allow connections from integration-test.

app/components/chart/stats.js, app/pages/patientdata/patientdata.js, package.json, yarn.lock
https://trello.com/c/kiGrj7Oo
The main fix was to ensure that the CSS loading dot animations are only happening while visible.
The other fix is a workaround for the time being, allowing the the stat animations to be disabled via a `animateStats=false` query param.
Related PR: tidepool-org/viz#156
=> Reduce idle cpu usage on data views

app/pages/patient/patientinfo.js, test/unit/pages/patient/patientinfo.test.js
Added a text count for editing a users bio (ie, 26/256 or 276/256). If a user is over the allotted count for a bio, then the counter turns error red.
Part 3 of this Trello 
https://trello.com/c/DI2bGRAa
=> Added dynamic text count

app/pages/verificationwithpassword/verificationwithpassword.js
This is to take care of [WEB-474]. The new param passed tells the initial patient claim form validation to treat the values as it would an `isOtherPerson` account when a user is signing up on behalf of a minor. This will allow clinicians to send invites to parents of children accounts and allow them to claim them properly at home. 
[WEB-474]: https://tidepool.atlassian.net/browse/WEB-474
=> allow claimed accounts to validate as isOtherPerson [WEB-474]

server.js
Caught in QA, just need to point the CSP at the updated URL
=> remove one more `chrome-uploader` release

app/core/personutils.js, app/pages/patient/patientinfo.js
Takes care of a couple things that came up in QA for [WEB-29].
1. Moves the `fullName` property to the `profile` instead of top level `patient`
2. Allows clinicians (with `custodial` permissions) to bypass the validation requiring `diagnosisDate` (which shows up as `OUT_OF_ORDER` due to the field being empty)
[WEB-29]: https://tidepool.atlassian.net/browse/WEB-29
=> tweak validation, move fullName property [WEB-29]

Dockerfile, app/rollbar.js, config.webpack.js, package.json, webpack.config.js
Uses the Github commit SHA for the version used in Rollbar.
Part of [WEB-75]
Related PR: tidepool-org/tools#83
[WEB-75]: https://tidepool.atlassian.net/browse/WEB-75
=> [WEB-75] rollbar GitHub sha

app/components/elements/FontStyles.js, app/themes/baseTheme.js
Noticed that all the line-heights in the `FontStyles` components were hard-coded to pixel values.  I've updated them to use unit-less values from the theme.
I've requested a couple of reviewers, but I'll just merge this in once one of you approves.
=> [WEB-559] Set up and use standard line heights in theme

app/components/elements/.eslintrc, app/components/elements/DatePicker.js, app/components/elements/DateRangePicker.js, app/components/elements/IconButton.js, app/themes/.eslintrc
Updated the various Date Picker icons to use a new `IconButton` component that requires an aria-label prop to be passed to it to enforce better accessibility
=> [WEB-559] Add IconButton component with required aria labels

app/components/elements/DatePicker.js, app/components/elements/DateRangePicker.js, stories/Datepicker.stories.js
This PR updates the example date range picker in the storybook to be responsive.
I also made a couple of small changes to the datepicker component wrapper props. Initially, I had a couple of "extra" props available for setting initial values.
After taking a more minimalist approach on the Dialog component wrappers, I wanted to apply the same approach here to simplify them a little.  There is no lost functionality.  The extra props were not necessary, as they performed the same function as existing props, only with different names.
=> [WEB-591] Update Date Range Picker story to be responsive and simplify component API wrapper

app/components/elements/Button.js, app/themes/base/buttons.js, app/themes/colorPalette.js, stories/Button.stories.js, stories/Dialog.stories.js
[WEB-589]
This adds some missing disabled and processing button styles that were not present in the PR for the Dialog component, and a new `Buttons` storybook.
As well, you'll notice some reverted commits.  I'd accidentally committed these directly to the `web-559-component-library` branch, and reverted it there, which meant that I had to "revert the revert" in this branch to allow the changes to be applied.
Also includes a small console warning fix for the Dialog component
[WEB-589]: https://tidepool.atlassian.net/browse/WEB-589
=> [WEB-589] Add processing and disabled button states, and storybook for Primary and Secondary buttons

app/components/chart/daily.js, app/pages/patientdata/patientdata.js, package.json, test/unit/components/chart/daily.test.js, yarn.lock
Addresses [WEB-768] and [WEB-770]
Related PR: 
tidepool-org/viz#193
This PR addresses the 'rerenderChart' error found via rollbar, including getting to the root cause which was that sometimes the chart was being initialized with incorrect data (such as the data queried to determine the default initial view, or the PDF data).  This PR ensures that the daily data has been provided before initializing the chart.
It also helps in that if there is a chart error while initializing, the error popup doesn't fire indefinitely anymore.  It fires once, and then can be closed by the user and they can interact with the application again.
It also pulls in a fix from `viz` that addresses an issue where under certain circumstances, a user with no device settings data will show the settings data of the …
=> [WEB-768,WEB-770] Release v1.31.1 to master

app/core/api.js, app/redux/actions/async.js, app/routes.js, test/unit/app/core/api.test.js
For [WEB-777]. An analogue for changes reflected in Uploader in the following changeset: https://github.com/tidepool-org/uploader/pull/751
[WEB-777]: https://tidepool.atlassian.net/browse/WEB-777
=> [WEB-777] log original errors to rollbar

app/components/export/export.js
Covers [WEB-779] by initializing the `moment` with the dates in it's localized mode and then converting to a UTC timestamp before passing on to the export service as opposed to initializing an already assumed UTC timestamp from the dates directly. This branch was taken from and is intended to be merged into the current 1.32.0 release branch.
[WEB-779]: https://tidepool.atlassian.net/browse/WEB-779
=> [WEB-779] start with local time and convert to UTC

app/components/export/export.js
For [WEB-779] adjusts the `endDate` for export to the end of that date, making the export range for the dates _inclusive_ instead of just including the entirety of the start date and ending at the beginning of the end date.
[WEB-779]: https://tidepool.atlassian.net/browse/WEB-779
=> [WEB-779] export end date time

app/pages/patient/patientinfo.js, test/unit/pages/patient/patientinfo.test.js
Takes care of [WEB-767] by not considering an empty MRN form field to represent an intentional deletion of that field by a normal user (for whom the MRN field doesn't render). 
[WEB-767]: https://tidepool.atlassian.net/browse/WEB-767
=> [WEB-767] retain MRN when user edits profile

app/core/api.js
For [WEB-783] to prevent race condition between the `preferences` and `profile` calls, specifically.
[WEB-783]: https://tidepool.atlassian.net/browse/WEB-783
=> [WEB-783] use series instead of parallel for user.put

app/components/elements/Button.js, app/components/elements/FontStyles.js, app/components/elements/Icon.js, app/components/elements/Pagination.js, app/themes/base/buttons.js, app/themes/base/icons.js, app/themes/base/paginators.js, app/themes/baseTheme.js, package.json, stories/Icon.stories.js, stories/Pagination.stories.js, yarn.lock
See [WEB-758] for details
Includes `default` and `condensed` variants, and a new `pagination` button variant.  As well, I've dropped the `ButtonFont` styled component and implemented it as default styles within the button variants, to allow easier overrides.
I looked at a number of pagination libraries, but found MUI pagination was actually a smaller import cost than the others, and allowed me to control the markup via a hook it exposes which was helpful for managing the variants in the Figma spec.
[WEB-758]: https://tidepool.atlassian.net/browse/WEB-758
=> [WEB-758] Pagination component

stories/Table.stories.js
Added one small fix that I'd done locally but forgotten to push before merging the PR for the Table component.
Fixes scenario where if you're, say, on page 4 of the data and you filter the results with the search input so there is only 2 pages of data, you're still on page 4 so no data shows till you click one of the page numbers.
=> [WEB-585] Reset to page 1 when changing search text in Table story

app/components/sendverificationbanner/index.js, app/components/sendverificationbanner/sendverificationbanner.js, app/components/sendverificationbanner/sendverificationbanner.less, app/pages/app/app.js, app/redux/reducers/misc.js, app/style.less, test/unit/app/app.test.js, test/unit/components/sendverificationbanner.test.js, test/unit/redux/reducers/resentEmailVerification.test.js
For [WEB-785], adds a banner for clinicians viewing accounts with emails that are currently unclaimed allowing the clinician to resend the verification email.
Clears store state regarding sent status on `CLEAR_PATIENT_IN_VIEW` and `FETCH_PATIENT_SUCCESS`.
[WEB-785]: https://tidepool.atlassian.net/browse/WEB-785
=> [WEB-785] add email verification resend banner

app/redux/actions/async.js, package.json, test/unit/redux/actions/async.test.js
After thinking about this a little more the fix for [WEB-803], I felt it necessary to make a tweak to the logic.
In the current solution, if the latest fetched diabetes datum time is greater than the server time, we use the server time and fetch back the 30 days for our initial data fetch.
This would be problematic if, for instance, a user hasn’t uploaded in a couple months, and they have 1 future datum.  In this case, fetching back 30 days from server time would not return any data.  We instead need to check if any of the latest diabetes datums are < server time, and if so, use that as the date to query by, and only fall back to using the server time if necessary.
[WEB-803]: https://tidepool.atlassian.net/browse/WEB-803
=> [WEB-803] Tweaks for removing future data

app/components/chart/basics.js, app/components/chart/bgLog.js, app/components/chart/daily.js, app/components/chart/trends.js, app/pages/patientdata/patientdata.js, test/unit/components/chart/basics.test.js, test/unit/components/chart/daily.test.js, test/unit/pages/patientdata.test.js
See [WEB-807] for details of the main bug this is addressing.
While I was going about ensuring that the BG Log chart would not mount until it had the data it needed, I thought it made sense to go back and update the daily view mitigations put in place a few weeks ago to determine that it's data had been queried.
Likewise, it seemed to make sense to apply the same mitigations to the Basics and Trends views.
[WEB-807]: https://tidepool.atlassian.net/browse/WEB-807
=> [WEB-807] Fix BG Log JS errors stemming from chart mounting before data is ready 

app/pages/patientdata/patientdata.js, package.json, test/unit/pages/patientdata.test.js
See [WEB-831] for details.
Also addresses passing in future dates to the trends view, though that view handles the scenario without throwing an error.
[WEB-831]: https://tidepool.atlassian.net/browse/WEB-831
=> [WEB-831] Hotfix for js error when switching to daily view with a date beyond the latest renderable datum

karma.conf.js, package.json
Jira issue [WEB-841]
Disabling source maps while running in watch mode fixes crashes while recompiling.  Likely due to memory constraints.
Note: I was able to have source maps working by setting it to `inline-cheap-source-map` while running in watch mode instead of `false`, but the total time to recompile/run the tests jumped from about 8 seconds to 20, so I felt it was better to go with performance in this case.  If we ever really need the source maps while running unit tests, we can simply run the normal, single-run `test` command to see the output.
[WEB-841]: https://tidepool.atlassian.net/browse/WEB-841
=> [WEB-841] Disable source maps when running tests in watch mode

package.json, yarn.lock
Just bumping blip to use a build of `viz` built off of the `develop` branch so that the updates to the `viz` in the last release branch are present in feature branches.
=> Bump viz to latest develop version

app/core/forms.js, app/pages/prescription/PrescriptionForm.js, app/pages/prescription/prescriptionFormConstants.js, app/pages/prescription/prescriptionSchema.js, app/pages/prescription/reviewFormStep.js, app/pages/prescription/therapySettingsFormStep.js, test/unit/app/core/forms.test.js, test/unit/pages/prescription/prescriptionFormConstants.test.js, test/unit/pages/prescription/prescriptionSchema.test.js, test/unit/pages/prescription/therapySettingsFormStep.test.js, yarn.lock
See [WEB-893] for details.
I had to re-enable the commented-out `suspendThreshold` field, which is not yet implemented in the backend, but should be soon (via tidepool-org/platform#462).  Currently, this means the suspendThreshold input works, but the value will not be saved to the backend.
This also contains a few small fixes for issues I noticed with the therapy settings section while developing:
1. The threshold warnings now only show when numerical values are present.  This avoids them showing when set to a default empty string value.
2. The input step props were missing from the correction range schedule inputes
3. In addition to the logic defined by the Jira ticket, enforcing that the low correction range targets are not below the suspend threshold, I've also set it so that a High …
=> [WEB-893] Dynamic lower correction range limit

app/components/export/export.js, app/pages/patient/patientinfo.js, test/unit/components/export.test.js
For [WEB-982], adds metrics events for various interactions in the export interface
Replaces https://github.com/tidepool-org/blip/pull/799 targeting release branch instead of develop
[WEB-982]: https://tidepool.atlassian.net/browse/WEB-982
=> [WEB-982] add metrics for export to `release-1.38.0`

.nlu.example.json, app/components/ChartDateRangeModal.js, app/components/PrintDateRangeModal.js, app/components/chart/basics.js, app/components/chart/header.js, app/components/elements/Accordion.js, app/pages/patientdata/patientdata.js, app/pages/patientdata/patientdata.less, package.json, stories/ChartDateRangeModal.stories.js, stories/PrintDateRangeModal.stories.js, test/unit/components/ChartDateRangeModal.test.js, test/unit/pages/patientdata.test.js, yarn.lock
See [WEB-54]
Implements a custom date range picker on the basics view via a calendar icon beside the dates.  Similar to the implementation of the print view date dialog, we have a 90-day limit, and identical defaults/presets to the print view to facilitate a 1:1 experience.
Supporting PR: tidepool-org/tideline#408
[WEB-54]: https://tidepool.atlassian.net/browse/WEB-54
=> [WEB-54] Custom Basics date ranges

app/components/ChartDateRangeModal.js, app/components/PrintDateRangeModal.js, app/pages/patientdata/patientdata.js, stories/ChartDateRangeModal.stories.js, test/unit/components/ChartDateRangeModal.test.js, test/unit/pages/patientdata.test.js
Some additional requirements stemming from the comments on [WEB-54]
Default dates for basics is now the latest 14 days to match the new print view defaults.
As well, added a kissmetric event to track date changes, and a note regarding the 90 days max custom range.
[WEB-54]: https://tidepool.atlassian.net/browse/WEB-54
=> [WEB-54] Set basics dates default extent size to 14 days, and send metrics on date changes

app/pages/patientdata/patientdata.js, test/unit/pages/patientdata.test.js
See [WEB-1064] 
Basicslly, the BG Log view was sending the date as a UTC timestamp, but the handler for switching to Daily was only working when the provided datetime was an ISO string.  The handler now works with both formats.
[WEB-1064]: https://tidepool.atlassian.net/browse/WEB-1064
=> [WEB-1064] Fix for double clicking datums on BG Log not navigating to correct date in Daily

app/components/chart/header.js, app/pages/patientdata/patientdata.js, app/pages/patientdata/patientdata.less, test/unit/components/chart/settings.test.js
Small fix required for [WEB-981], where in scenarios that an async data fetch was required prior to generating a PDF report, the print window would be blocked by the browser's popup blocker.
The solution is to open the new window BEFORE sending the request for earlier data, and then updating the `location.href` of it once the data is received and the PDF is ready.  We show a short message in the new blank window while the user waits.
In cases where this pre-fetching is not required, the workflow has not been updated.  It will stay on the print modal until the processing is complete, and then open the new tab.
While implementing this fix, I also noticed some inconsistencies on hover states and flex positioning within the updated header bar, so I've cleaned up some styles as well. …
=> [WEB-981] Pre-open a PDF window async data fetch is required

app/components/PrintDateRangeModal.js, package.json, test/unit/components/printDateRangeModal.test.js
See Ginny's comments in [WEB-981]
This sets a better min-width for the modal for when only devices is enabled, adds validation to disable printing if no charts are enabled, and does not validate dates for a disabled chart.
[WEB-981]: https://tidepool.atlassian.net/browse/WEB-981
=> [WEB-981] Address print dialog UI feedback

Dockerfile
Sets the appropriate viz path in the docker container to allow linked viz package to run correctly with the updated npm scripts.
=> Fix for running linked viz within docker container

app/components/ChartDateRangeModal.js, app/components/PrintDateRangeModal.js, app/components/elements/Toast.js, app/pages/patientdata/patientdata.js, app/providers/ToastProvider.js, package.json, test/unit/pages/patientdata.test.js
Hotfix. See [WEB-1089] for details.
Mainly, this PR will catch errors caused by the popup blocker being invoked when a request to generate a PDF takes too long, and display a notification to the user.
It also adds an action prop to the Toast component that can be used to render a CTA within a notification, and fixes a couple of warnings on the proptypes for the print and chart date range modals, since some of the props are not immediately available on first rendering.
The fix on this one was relatively easy.  Getting the patientdata unit tests working ended up being a rather large trial, due to a 'perfect storm' of sorts in the way the ToastProvider context had to be applied to the 'create-react-class' component, which didn't play nicely with i18n's context within the enzyme mounts.  I …
=> [WEB-1089] Catch pdf window focus errors caused by popup blocker

app/pages/prescription/PrescriptionForm.js, app/pages/prescription/prescriptionFormConstants.js, app/pages/prescription/therapySettingsFormStep.js, test/unit/pages/prescription/prescriptionFormConstants.test.js
See [WEB-1094]
Also includes a small update to the blood glucose target low warning to be consistent with an updates to Loop.  (now <100, was <101)
[WEB-1094]: https://tidepool.atlassian.net/browse/WEB-1094
=> [WEB-1094] accomodate default therapy settings

app/pages/patientdata/patientdata.js, package.json
See [WEB-1129] for details.
Basically the wrong date was being used for requests for earlier data due to a missing `startDate` option being set when requesting a range for the basics view that required earlier data to be fetched.
[WEB-1129]: https://tidepool.atlassian.net/browse/WEB-1129
=> [WEB-1129] Basics date selection fix

app/components/elements/RadioGroup.js, app/components/elements/Select.js, app/components/elements/Stepper.js, app/core/constants.js, app/pages/prescription/PrescriptionForm.js, app/pages/prescription/prescriptionFormConstants.js, app/pages/prescription/prescriptionSchema.js, app/pages/prescription/profileFormSteps.js, app/pages/prescription/reviewFormStep.js, app/pages/prescription/settingsCalculatorFormSteps.js, app/pages/prescription/therapySettingsFormStep.js, app/themes/base/inputs.js, test/unit/app/core/constants.test.js, test/unit/pages/prescription/PrescriptionForm.test.js, test/unit/pages/prescription/accountFormSteps.test.js, test/unit/pages/prescription/prescriptionFormConstants.test.js, test/unit/pages/prescription/prescriptionSchema.test.js, test/unit/pages/prescription/profileFormSteps.test.js, test/unit/pages/prescription/reviewFormStep.test.js, test/unit/pages/prescription/settingsCalculatorFormSteps.test.js, test/unit/pages/prescription/therapySettingsFormStep.test.js
See [WEB-1134] for details
Some small things to note:
- Small changes to the Radio and Select components (for handling number values and refs for focus reasons, respectively)
- Added an `onSkip` handler to the Stepper to flush all calculator form values when step is skipped at any time
- Memoized some functions on the therapy settings step that were being called way more often than needed (the ones for determining input ranges, thresholds, and default values) 
- Fixed an invalid color reference for some input styles
- FIxed some unit tests for the validation of the existing form steps that were not really testing what I thought they were
[WEB-1134]: https://tidepool.atlassian.net/browse/WEB-1134
=> [WEB-1134] Add AACE calculator step to prescription form

.travis.yml
Seems to work.  Previously, Travis logs were getting inundated with error messages from `chokidar` along the lines of:
```
Error: ENOSPC: System limit for number of file watchers reached
```
=> Attempt to address max file watchers warnings that are clogging the travis logs

app/components/chart/trends.js, package.json, yarn.lock
See [WEB-1157]
Ensure that trends forward nav is disabled if end date is beyond most recent datum time
Related PR: https://github.com/tidepool-org/viz/pull/263
[WEB-1157]: https://tidepool.atlassian.net/browse/WEB-1157
=> [WEB-1157] Trends navigation fixes

.travis.yml
Docker pull rate limits are capped at 100 for unauthenticated requests.  Authenticating prior to pulling allows us to avoid these rate limit errors during high travis build usage.
=> Travis: docker login before pull

app/components/navbar/navbar.js, app/core/less/nav.less, app/pages/app/app.js, app/routes.js, config/local.example.js
See [WEB-1209]
Sets the default root redirect to `/workspaces` when new clinic flow is active, and disables logo link in certain circumstances.
[WEB-1209]: https://tidepool.atlassian.net/browse/WEB-1209
=> [WEB-1209] Logo link updates

app/components/navbar/navbar.js, app/routes.js, test/unit/routes.test.js
Part of [WEB-1209]
Looking over the Figma spec, it seems that there were 2 locations where the logo should have been linked that were missed on the first pass (These were not part of the 'Done Criteria', which has now been updated to match the Figma spec).
As well, I noticed a property nesting error on the base route handling when checking for clinic properties, which is fixed here.
[WEB-1209]: https://tidepool.atlassian.net/browse/WEB-1209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1209] Add logo link to a clinician's account settings and personal workspace pages

app/pages/clinicworkspace/ClinicPatients.js, app/pages/clinicworkspace/clinicworkspace.js, app/pages/share/PatientInvites.js, app/redux/actions/async.js, app/redux/actions/sync.js, app/redux/reducers/misc.js, test/unit/pages/share/PatientInvites.test.js, test/unit/redux/actions/async.test.js, test/unit/redux/actions/sync.test.js, test/unit/redux/reducers/clinics.test.js
Fixes [WEB-1295].  
Not sure why, but originally , the clinic's accepted patients and invitations were stored in the same clinic property in redux state.  This was causing collisions with the updated API.
They are now stored in a `patientInvites` property of a clinic.
Added a few missing redux tests around clinic patient invites as well.
[WEB-1295]: https://tidepool.atlassian.net/browse/WEB-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1295] Fix for conflicts between clinic invites and patients state

app/components/navbar/NavigationMenu.js, app/pages/workspaces/workspaces.js, app/routes.js, test/unit/components/navbar/NavigationMenu.test.js, test/unit/pages/workspaces/workspaces.test.js
See [WEB-1291].  Since this removes the link from the workspaces page, we need a way to still access the private workspace, the link now always shows in the top navigation menu
As well, this includes a small fix for the fallback routing based on whether or not a user is in a clinic workflow.
[WEB-1291]: https://tidepool.atlassian.net/browse/WEB-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1291] Remove private workspace link

app/components/clinic/WorkspaceSwitcher.js, app/components/elements/Popover.js, app/components/navbar/NavigationMenu.js, app/pages/patientdata/patientdata.js, app/pages/patientprofile/patientprofile.js, app/redux/actions/async.js, app/redux/actions/sync.js, app/redux/reducers/misc.js, test/unit/pages/patientprofile.test.js, test/unit/redux/actions/async.test.js, test/unit/redux/actions/sync.test.js
See [WEB-1301] for details.
I also noticed a couple of small issues that I fixed at the same time:
1. Since we no longer show the private workspace option on the 'Workspaces' page, it no longer makes sense to redirect there when a clinician is a member of only 1 clinic - even if they have an active private workspace.
2. There was a bug where the workspace switcher was sometimes not showing the private workspace option when it should.  This is now fixed
[WEB-1301]: https://tidepool.atlassian.net/browse/WEB-1301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1301] Fix for missing profile page custodial permissions

app/pages/clinicworkspace/ClinicPatients.js, test/unit/pages/ClinicPatients.test.js
Addresses some QA feedback for [WEB-1210]
[WEB-1210]: https://tidepool.atlassian.net/browse/WEB-1210?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1210] Fix for missing and non-triggering patient removal metrics

app/components/chart/basics.js, app/components/chart/bgLog.js, app/components/chart/daily.js, app/components/chart/deviceSelection.js, app/components/chart/stats.js, app/components/chart/trends.js, app/core/utils.js, app/pages/patientdata/patientdata.js, package.json, test/unit/components/chart/deviceSelection.test.js, test/unit/components/chart/stats.test.js, test/unit/components/chart/trends.test.js, test/unit/pages/patientdata.test.js, test/unit/utils/utils.test.js, yarn.lock
See [WEB-1204], [WEB-1182].  Adds `Avg Daily Insulin Ratio` stat to trends view, and sets any of the vertically-tall stats to collapsible.  Stat collapse state is persisted in local storage on a per-view basis.
Related PR: https://github.com/tidepool-org/viz/pull/285
[WEB-1204]: https://tidepool.atlassian.net/browse/WEB-1204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-1182]: https://tidepool.atlassian.net/browse/WEB-1182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1204, WEB-1182] Stat updates

app/pages/share/AccessManagement.js, test/unit/pages/share/AccessManagement.test.js
For old/classic clinic accounts, show share classification as "Clinician" to not confuse existing users who have existing relationships with a clinic. For [WEB-1366]
[WEB-1366]: https://tidepool.atlassian.net/browse/WEB-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1366] display 'clinician' for classic clinic accounts

app/pages/share/AccessManagement.js, test/unit/pages/share/AccessManagement.test.js
Set a `SHARING` status for invites that don't have another status (pending or declined). Handles [WEB-1365]
[WEB-1365]: https://tidepool.atlassian.net/browse/WEB-1365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1365] share status

app/core/utils.js, app/redux/actions/async.js, app/redux/store/configureStore.dev.js, app/redux/store/configureStore.prod.js, app/redux/utils/pendoMiddleware.js, test/unit/redux/utils/pendoMiddleware.test.js, test/unit/utils/utils.test.js
To address [WEB-1363]. Moves pendo related code into a middleware instead of being one-off utility functions called directly from our async action creators since I felt like it more appropriately resides there. Adds in some new clinic system specific properties for pendo and handles setting pendo states when switching clinic accounts.
[WEB-1363]: https://tidepool.atlassian.net/browse/WEB-1363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1363] additional pendo clinic updates and middleware migration

app/components/navbar/NavigationMenu.js, app/pages/clinicdetails/clinicdetails.js, app/redux/actions/async.js, app/routes.js, package.json, test/unit/redux/actions/async.test.js, test/unit/routes.test.js
Hotfix for [WEB-1522]
Primarily addresses users potentially being able to skip the route restriction checks on clinic UI routes if one of the backend calls made prior to the checks returns an error.
I also fixed a small bug where the nav menu wasn't updating to the default options if the user navigated away from the clinic profile page, and cleaned up the error handling on login failures a bit too, including dispatching the logout action if the backend calls fail.
[WEB-1522]: https://tidepool.atlassian.net/browse/WEB-1522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1522] Clinic route restriction fixes

app/pages/clinicworkspace/ClinicPatients.js, app/pages/clinicworkspace/ClinicianPatients.js, test/unit/pages/ClinicPatients.test.js, test/unit/pages/ClinicianPatients.test.js
Addresses [WEB-1543], for both the clinic and legacy clinician "Add Patient" forms.
As well, I noticed that the "Edit Patient" action was available on the legacy (private workspace) patient list for accounts without the appropriate permissions, so that now only shows if the clinician has `custodian` permission for the account (or if it's their own account)
[WEB-1543]: https://tidepool.atlassian.net/browse/WEB-1543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1543] Clear patient form between submissions

app/pages/clinicadmin/clinicadmin.js, app/pages/clinicworkspace/ClinicPatients.js, test/unit/pages/ClinicPatients.test.js, test/unit/pages/clinicadmin.test.js
Feedback via testing of [WEB-1347] revealed we weren't displaying the toast in as many places/on specific user actions as desired. This will cause a re-fetch of patients or clinicians when the list component mounts, regardless of whether or not the previous attempts have failed, in order to re-assess and re-display authorization errors to the user if necessary. Also un-blocks a number of error messages that wouldn't have been displayed due to checking for completed which will always be "falsy" on errored API calls.
`.1` branch to denote rebase against release branch and deprecating original branch
[WEB-1347]: https://tidepool.atlassian.net/browse/WEB-1347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1347] clinician authorization toast fixes/adjustments

docs/StartHere.md
Currently the dev guide has a typo in the link to the root readme leading to a 404. Fixed typo and now the link works.
I agree to the terms of Tidepool Project’s Volunteer/Contributor License Agreement v1.1 as
it exists at http://tidepool-org.github.io/files/TidepoolVCLA-1.1.pdf on 4/28/22
=> fix of readme link in dev guide (currently gives 404)

app/pages/clinicworkspace/ClinicPatients.js, test/unit/pages/ClinicPatients.test.js
See [WEB-1628]
This allows the previously filters to be properly represented on load, and the initial patient fetch query can then be generated accordingly.
[WEB-1628]: https://tidepool.atlassian.net/browse/WEB-1628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1628] Persist active patient list filters across page views

app/redux/actions/async.js, test/unit/redux/actions/async.test.js
See [WEB-1641]
[WEB-1641]: https://tidepool.atlassian.net/browse/WEB-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1641] - Add error message for failed custodial account creation due to duplicate email address

app/core/utils.js, app/pages/patientdata/patientdata.js, package.json
See [WEB-1660]
The main issue was that the code block that was intended to perform the override had some incorrect conditional logic for when to apply the overrides.  
Specifically, the override units from the clinic were stored in the following formats:  `mmol/L | mg/dL` 
The conditional code was validating that it matched one of `[mmoll, mgdl]`
I also updated it to allow the query param `units` override to take precedence over the clinic's preferred bg units so that it's still a functional option within a clinic context.
[WEB-1660]: https://tidepool.atlassian.net/browse/WEB-1660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1660] Fix for clinic preferred BG units not being applied correctly in certain circumstances.

app/pages/app/app.js, app/redux/reducers/data.js, package.json, test/unit/redux/reducers/data.test.js
See [WEB-1672]
Fixes a regression introduced in `v1.53.0` where switching between the profile page and the patient view causes the patient view to not load.  This was due to moving the queryDataCount metadata to the Data worker, and not resetting it to zero when we drop the redux state data, but preserve the cached data in the worker, as happens when navigating to the profile page from a data view.
With the queryDataCount set to zero, it now properly fetches the initial data (from the worker) and renders the view.
As well, I noticed that some old top-level code in `app.js` that was used to ensure we had `selectedClinicId` state set was affecting the page refreshes when viewing clinic custodial account data, setting the `selectedClinicId` arbitrarily to the first available clinic.  This …
=> [WEB-1672] Fix issues with patient data loading

app/redux/reducers/working.js, package.json, test/unit/redux/reducers/working.test.js
See [WEB-1682]
Basically, when the (broken) refresh functionality was fixed in `v1.52.0`, it was set to detect changes to react to the removal of patient data from the data worker.  Because the completed state of that action was never being set back to null, it was causing, in some instances, [the data fetch to fire over and over again](https://github.com/tidepool-org/blip/blob/24ee0e8a866545f6e4bbb23f8cab8e984d18fd6c/app/pages/patientdata/patientdata.js#L1457). 
[WEB-1682]: https://tidepool.atlassian.net/browse/WEB-1682?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1682] Fix for recursive patient data fetching immeditately after login

app/components/elements/Table.js, package.json
Hotfix for [WEB-1702]
`String.replaceAll` fails for chrome versions below `85` (released August 2020).  Switching to the far more broadly-supported `repalce` with a regex and global flag.
[WEB-1702]: https://tidepool.atlassian.net/browse/WEB-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1702] Fix Table component js error for older versions of Chrome

app/redux/actions/async.js, test/unit/redux/actions/async.test.js
[WEB-1642] Fixes an issue discovered in design review where, after a new clinician user creates a new clinic, logs out, and logs in again, they are redirected to the migrate form instead of the workspace.
[WEB-1642]: https://tidepool.atlassian.net/browse/WEB-1642?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1642] Fix migrate prompt for new clinician users on subsequent logins

app/components/clinic/PatientForm.js, test/unit/pages/ClinicPatients.test.js
For [WEB-1665], disables email field editing for non-custodial patient accounts
[WEB-1665]: https://tidepool.atlassian.net/browse/WEB-1665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1665] Disable non-custodial patient email editing

app/components/elements/Table.js, app/pages/clinicworkspace/ClinicPatients.js, test/unit/pages/ClinicPatients.test.js
for [WEB-1701], sets page size to 50 and adds support for scrolling table by capping the table container height
[WEB-1701]: https://tidepool.atlassian.net/browse/WEB-1701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1701] Use page size of 50 instead of 10 for patient list

app/pages/clinicworkspace/ClinicPatients.js, test/unit/pages/ClinicPatients.test.js
For [WEB-1738], defaults to sort by last upload date descending if it's available (if we're showing summary data).
[WEB-1738]: https://tidepool.atlassian.net/browse/WEB-1738?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1738] default to sort by last upload descending

app/pages/clinicworkspace/ClinicPatients.js, package.json, yarn.lock
An addition/alteration to [WEB-1701]. Lets the entire page scroll and adds a scroll to top button that appears as you scroll down the page.
[WEB-1701]: https://tidepool.atlassian.net/browse/WEB-1701?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1701] allow page scrolling, add scroll to top button

app/components/clinic/BgRangeSummary.js, test/unit/components/clinic/BgRangeSummary.test.js
For [WEB-1644], applies a number of rounding rules to prevent rounding display values into filter boundaries.
[WEB-1644]: https://tidepool.atlassian.net/browse/WEB-1644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1644] summary stat percentage rounding

app/pages/clinicworkspace/ClinicPatients.js
For [WEB-1835], combines two `useEffect` calls with overlapping dependency arrays. There's some subtle conflict where the combination of an object and an object's property being dependencies of two different `useEffect` calls will cause undesirable behavior. 
The `inProgress` property on `fetchingPatientsForClinic` would be `true` when I would have expected it to be `false` on the `useEffect` that should `setLoading` and then the second `useEffect` wouldn't actually run at all. By just combining them both, it runs when expected and has the proper `fetchingPatientsForClinic.inProgress` = `false` for the `FETCH_PATIENTS_FOR_CLINIC_SUCCESS` state update.
[WEB-1835]: https://tidepool.atlassian.net/browse/WEB-1835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …
=> [WEB-1835] simplify useEffect dependencies

.eslintrc, app/components/clinic/BgRangeSummary.js, app/components/clinic/ClinicProfile.js, app/components/elements/Popover.js, app/components/elements/Table.js, app/core/hooks.js, app/pages/clinicworkspace/ClinicPatients.js, app/pages/clinicworkspace/clinicworkspace.js, app/pages/prescription/reviewFormStep.js, app/providers/ToastProvider.js, package.json, test/unit/app/core/hooks.test.js, yarn.lock
As part of the latest design tweaks for [WEB-1701] (scrolling to the top of the patient interface on pagination) it was discovered that there were performance issues causing loading state hangs in the interface. As a start, I grabbed the eslint react-hooks/recommended plugin and went about trying to satisfy all of its errors and warnings for the ClinicPatients page. This lead to a lot of dependency adding, cascading into needing to move hook dependencies into hooks themselves and use-before-define errors to solve by rearranging significant portions of code. A couple sections were moved into sub-components in order to be able to move their prop processing into their own hooks as the renders for them were already in a hook (and, of course, one does not simply nest hooks).
In trying to keep …
=> [WEB-1701] scroll to top on page, performance pass, eslint react-hooks/recommended

app/pages/clinicworkspace/ClinicPatients.js
See [WEB-1857], reset local current page on default fetch options being set to avoid scrolling on perceived page change when navigating from page > 1 to a new clinic. 
[WEB-1857]: https://tidepool.atlassian.net/browse/WEB-1857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1857] reset currentPage on default fetch options

app/pages/patientdata/patientdata.js, test/unit/pages/patientdata.test.js
For [WEB-1838]. If the `chartKey` happens to match up with the incoming query metadata on a query that tries to force a remount, the result of the update is nil. This can happen because the chartKey only gets updated on forced remount attempts and can recycle through values as the query count gets reset to 0 on use of the Refresh button. If we force a remount (and thus update the chartKey state value) on "initial" queries when we've already got a value for `state.chartKey`, we can keep the values better in sync post-Refresh. 
[WEB-1838]: https://tidepool.atlassian.net/browse/WEB-1838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1838] force remount on data fetch after refresh

app/components/elements/Table.js
Went down this rabbit hole  and seems to be an issue specifically with Mozilla Firefox. https://bugzilla.mozilla.org/show_bug.cgi?id=688556 
background-clip: padding-box seems to fix the issue.
=> Make sure table border can be seen in mozilla

app/pages/clinicworkspace/ClinicPatients.js
In order to handle [WEB-2006], this unwraps a couple of the `handleAsyncResult` calls in order to more finely control when they fire. Specifically we need to prevent the selected patient reset and dialog closures on complete detection when only the selected patient value as changed (and not the working state). This ensures that the remove patient and send upload reminder handlers don't effectively reset the selected patient and dialogs states whenever attempting either of those actions a second time. 
[WEB-2006]: https://tidepool.atlassian.net/browse/WEB-2006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2006] Repeat patient deletes, tags, upload reminders fail

config/local.example.js
Local option was never added to the example file.  Now added.
=> Add local environment to apiHost config options list

app/pages/signup/signup.js, test/unit/pages/signup.test.js
To resolve [WEB-1997], pass along the email address for registration to keycloak if available
[WEB-1997]: https://tidepool.atlassian.net/browse/WEB-1997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1997] pass loginHint if available

app/components/loginnav/loginnav.js, app/keycloak.js, app/pages/login/login.js, app/pages/signup/signup.js, app/redux/actions/async.js, app/redux/actions/sync.js, app/redux/reducers/misc.js, test/unit/components/loginnav.test.js, test/unit/keycloak.test.js, test/unit/pages/login.test.js, test/unit/pages/signup.test.js, test/unit/redux/actions/async.test.js
For [WEB-1998], will send the user to the keycloak logout URL if it's available instead of redirecting to `\`, which can potentially beat out the `keycloak.logout()` call we were previously using, resulting in a not-logged-out state.
[WEB-1998]: https://tidepool.atlassian.net/browse/WEB-1998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1998] redirect logout through keycloak if available

app/pages/login/login.js, test/unit/pages/login.test.js
To handle [WEB-2024]. To prevent the race condition where keycloak initialization will forward a user to the normal login flow on the keycloak server, we check for the `signupEmail` and `signupKey` present on account claim flows and prevent keycloak forwarding if detected.
[WEB-2024]: https://tidepool.atlassian.net/browse/WEB-2024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2024] don't send to Keycloak for account confirmations

app/redux/actions/async.js, test/unit/redux/actions/async.test.js
[WEB-2064] 
Currently, we exclude the latest `pumpSettings`, `upload`, and `food` datums when determining the fetch range for the initial data fetch.
This can lead to a situation, however, where the latest `pumpSettings` are not fetched and added to the data worker, so this fix still uses only the latest diabetes (insulin or bg) datums to determine the start date of the fetch range, but ensures the end date accounts for the non-diabetes datums as well. 
[WEB-2064]: https://tidepool.atlassian.net/browse/WEB-2064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2064] Hotfix: Ensure latest pump settings are fetched

app/pages/uploadredirect/uploadredirect.js, test/unit/pages/uploadredirect.test.js
for [UPLOAD-987], drops the sometimes-non-functional close window link
[UPLOAD-987]: https://tidepool.atlassian.net/browse/UPLOAD-987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UPLOAD-987] drop close window link

app/components/clinic/PatientForm.js, app/components/clinic/ResendDexcomConnectRequestDialog.js, app/components/datasources/datasources.js, app/components/dexcombanner/dexcombanner.js, app/components/dexcombanner/dexcombanner.less, app/pages/app/app.js, app/redux/reducers/misc.js, test/unit/app/app.test.js, test/unit/components/dexcombanner.test.js, test/unit/pages/ClinicPatients.test.js, test/unit/redux/reducers/showingDexcomConnectBanner.test.js
[WEB-2059]
There is a lot more code shift here than I originally anticipated, so a few changes of note are worth highlighting:
- Moved dexcom connect request dialog out of the `PatientForm` component for reuse in the banner
- Decided it was better to expand the existing dexcom banner to allow handling both initial connection and reconnection states.  Splitting into separate banners with separate redux state seemed excessive, and would have required adding additional 'dismissTime' and 'clickedTime' properties to our seagull preferences.
- Removed forced disabling of `showingDexcomConnectBanner` upon user fetch, since we now need to allow a banner to show even if the initial banner was previously interacted with (dismissed or actioned) based also on the latest dexcom data source …
=> [WEB-2059] Dexcom reconnect banner

app/keycloak.js, app/pages/uploadredirect/uploadredirect.js
to take care of [UPLOAD-999] and [UPLOAD-1000] - adds Safari-specific launch dialog text and a couple preventative measures to keep the launch link from trying to open on a re-render/redirect that seems to only happen on Safari
[UPLOAD-999]: https://tidepool.atlassian.net/browse/UPLOAD-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UPLOAD-1000]: https://tidepool.atlassian.net/browse/UPLOAD-1000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [UPLOAD-999], [UPLOAD-1000] uploader launch Safari additions

app/keycloak.js, app/pages/loggedout/index.js, app/pages/loggedout/loggedout.js, app/redux/actions/async.js, app/routes.js, test/unit/keycloak.test.js, test/unit/pages/loggedout.test.js, test/unit/redux/actions/async.test.js
for [WEB-2098] creates logged out page which users will be sent to when keycloak token authentication/refresh fails. Additionally triggers a keycloak token refresh whenever any API call returns a 401/403 error to verify session validity.
[WEB-2098]: https://tidepool.atlassian.net/browse/WEB-2098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2098] logged out page and 401/403 redirects

app/core/clinicUtils.js, package.json, test/unit/pages/ClinicPatients.test.js
[WEB-2138]
[WEB-2138]: https://tidepool.atlassian.net/browse/WEB-2138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2138] Hotfix: patient form validation error when Dexcom is in "pendingReconnect" state

app/pages/userprofile/userprofile.js, app/redux/actions/async.js, app/redux/constants/errorMessages.js, test/unit/pages/userprofile.test.js, test/unit/redux/actions/async.test.js
for [WEB-2107]. also decided to use the `working` state to determine whether or not a save was successful instead of just _always_ optimistically telling the user that it was and disabling the save button while the call is in progress.
[WEB-2107]: https://tidepool.atlassian.net/browse/WEB-2107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2107] user profile email in use message

app/redux/actions/async.js, test/unit/redux/actions/async.test.js
for [WEB-1148]. Clinic custodial account creation already used ERR_ACCOUNT_ALREADY_EXISTS on 409's so I updated clinic and VCA update and create patient functions to match.
[WEB-1148]: https://tidepool.atlassian.net/browse/WEB-1148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-1148] bring all patient update/create duplicate email errors in alignment

app/pages/userprofile/userprofile.js, karma.conf.js, test/unit/pages/userprofile.test.js
augmentation to [WEB-2107] to handle when the user is logging out and the logged in ID has been cleared from redux state
[WEB-2107]: https://tidepool.atlassian.net/browse/WEB-2107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2107] handle logging-out case

app/keycloak.js, package.json, test/unit/keycloak.test.js
to handle [WEB-2285], preemptively refreshing the auth token 10 seconds prior to expiry as opposed to precisely at time of expiry
Web analog of https://github.com/tidepool-org/uploader/pull/1553
[WEB-2285]: https://tidepool.atlassian.net/browse/WEB-2285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2285] token refresh

app/pages/login/login.js, app/pages/patientdata/patientdata.js, app/redux/actions/async.js, app/routes.js, test/unit/pages/login.test.js, test/unit/pages/patientdata.test.js, test/unit/redux/actions/async.test.js, test/unit/routes.test.js
For [WEB-224], provides the ability to navigate directly to a given URL, even through the authentication flow. Adds a bit of logic to try and be smart about clinicians viewing patient data to reverse engineer what clinic should be selected so the interface is congruent with the current experience and restricts certain URLs based on account type (non-clinicians don't get clinician routes) and number of clinics a clinician is a member of (routes requiring a selected clinic go to workspace selection if no clinic is selected).
[WEB-224]: https://tidepool.atlassian.net/browse/WEB-224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-224] direct linking support

app/rollbar.js, karma.conf.js, test/unit/pages/ClinicPatients.test.js
for [WEB-2248], Rollbar has the `environment` as part of their URL structure for some pieces of their application, so using a full protocol+host breaks the URLs for those pieces of the application (and they don't urlencode it...) so we can just use the `host` going forward.
[WEB-2248]: https://tidepool.atlassian.net/browse/WEB-2248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2248] just use host for rollbar environment

app/bootstrap.js, karma.conf.js, package.json, test/unit/bootstrap.test.js
For [WEB-2383], taking some inspiration from how uploader handles adding some metric properties that should always be included if available (including `clinicId`)
[WEB-2383]: https://tidepool.atlassian.net/browse/WEB-2383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2383] Add `clinicId` to kissmetrics whenever available

app/pages/clinicadmin/clinicadmin.js, app/pages/clinicinvite/clinicinvite.js, test/unit/pages/clinicadmin.test.js
for [WEB-2428], uses the (already present) Redux state for `selectedClinicId` instead of the passing it in through the location state
[WEB-2428]: https://tidepool.atlassian.net/browse/WEB-2428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2428] use Redux state instead of location state for selected clinic

app/routes.js
for [WEB-2429], changes logic to _require_ a `selectedClinicId` for routes that require it
[WEB-2429]: https://tidepool.atlassian.net/browse/WEB-2429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2429] require selectedClinicId for restricted routes

app/routes.js
for [WEB-2430] adds exception to routing rule that allows navigation to `/clinic-details/new` without a selected clinic ID
[WEB-2430]: https://tidepool.atlassian.net/browse/WEB-2430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2430] allow create new clinic route without selected clinic

app/pages/patientdata/patientdata.js, test/unit/pages/patientdata.test.js
for [WEB-2431], expands selecting a clinic to handle cases where there _is_ a selected clinic, but it's not a clinic that the current patient-in-view is a member of instead of only handling the case where there is no selected clinic
[WEB-2431]: https://tidepool.atlassian.net/browse/WEB-2431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2431] handle selecting clinic a patient is a member of in all cases

app/pages/clinicdetails/clinicdetails.js
for [WEB-2435] make sure that we _do_ allow the redirect on the `new` action after the form has submit
[WEB-2435]: https://tidepool.atlassian.net/browse/WEB-2435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2435] allow redirect after submit on `new` action

app/routes.js
For [WEB-2444] allow the `/clinic-details/profile` route even without a selected clinic in the case that the user lacks a clinic profile (for new signups). Mimics logic from the routing when fetching new information on login.
[WEB-2444]: https://tidepool.atlassian.net/browse/WEB-2444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2444] allow clinic profile route for new clinician signups

app/core/constants.js, app/pages/patientdata/patientdata.js, app/redux/actions/async.js, package.json, test/unit/app/core/constants.test.js, test/unit/redux/actions/async.test.js
Addresses [WEB-2392]
List of fetched data types corresponds to the [expected list in the data util validation in viz](https://github.com/tidepool-org/viz/blob/907c7824f9dd4b6ed13ff8bd56ddeaf9c3478ecf/src/utils/validation/schema.js#L72-L88)
Also includes a small race condition fix for a state mutation error that was happening for me locally, but not on QA2 on the same build.
[WEB-2392]: https://tidepool.atlassian.net/browse/WEB-2392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2392] Only fetch required data types for patients

app/components/chart/basics.js, package.json
[WEB-2504]
Fixes and edge case where upon switching from BGM to CGM on the basics view, the matched devices list was not including the aggregated fingersticks, becuase they wasn't being queried upon bgSource change.  This is now queried to ensure that those will be included in the matched devices list.
It's a bit redundant to have to query the aggregations again, since they are not expected to change when only the bg source is updated, but it's the only way to ensure the matched devices metadata is correct on this view.
[WEB-2504]: https://tidepool.atlassian.net/browse/WEB-2504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2504] Uploaded device discrepancy fix for basics when toggling from BGM data source to CGM

app/components/clinic/TideDashboardConfigForm.js, app/components/navbar/navbar.js, app/pages/app/app.js, app/pages/clinicworkspace/ClinicPatients.js, app/pages/dashboard/TideDashboard.js, package.json, server.js, test/fixtures/mockTideDashboardPatients.json, test/unit/pages/ClinicPatients.test.js, test/unit/pages/TideDashboard.test.js, yarn.lock
[WEB-2500]
Related: https://github.com/tidepool-org/platform-client/pull/152
Includes:
- Flattening the average glucose summary values to correspond to backend change
- Updates to navbar 'back' link to return to either patients list, as it currently does, or to the tide dash if that's where the user navigated to the patient view from.
[WEB-2500]: https://tidepool.atlassian.net/browse/WEB-2500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2500] tide backend integration

app/pages/dashboard/TideDashboard.js, package.json, test/unit/pages/TideDashboard.test.js
[WEB-2541] Currently, was incorrectly using the last upload dates for the dashboard dates.  Changed to use the config period.
[WEB-2541]: https://tidepool.atlassian.net/browse/WEB-2541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2541] Use config period for TIDE dash dates

app/pages/dashboard/TideDashboard.js, package.json, test/unit/pages/TideDashboard.test.js
[WEB-2543], [WEB-2542]
Similar to what we do for the clinic and clinician patients lists, we need to clear the currently viewed patient here as well.
While it would be simpler to do it on unmount of the patient data view component, we currently don't because we intentionally retain the currently loaded patient so while the user navigates between the data views and profile/share pages.
[WEB-2543]: https://tidepool.atlassian.net/browse/WEB-2543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2542]: https://tidepool.atlassian.net/browse/WEB-2542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2543,WEB-2542] Clear patient in view state when mounting dashboard

app/components/clinic/BgRangeSummary.js, app/components/clinic/BgSummaryCell.js, app/components/elements/DeltaBar.js, app/core/constants.js, app/core/utils.js, app/pages/dashboard/TideDashboard.js, karma.conf.js, package.json, test/unit/components/clinic/BgRangeSummary.test.js, test/unit/pages/TideDashboard.test.js, test/unit/utils/utils.test.js
[WEB-2551]
This is basically a rewrite of the custom rounding we had applied for the Population Health dashboard to handle small numbers rounding to zero, and numbers rounding naturally to the filter time in range thresholds in a way that didn't comport well with the filters. 
For a more detailed description see the [internal documentaion](https://docs.google.com/document/d/1DaGKoSplCS1-NYDDyoCwv52pZQoIJFEO3H6VWsXsBQE/edit#heading=h.pcw1rfj1h4gl) 
[WEB-2551]: https://tidepool.atlassian.net/browse/WEB-2551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2551] Percentage rounding tweaks around thresholds

app/redux/utils/logErrorMiddleware.js, app/worker/PDFWorker.js, test/unit/redux/utils/logErrorMiddleware.test.js, test/unit/worker/PDFWorker.test.js
for [WEB-2534], expands our error logging gate check to include unmodified `Error` instances, which `_.isEmpty()` will consider empty due to having no enumerable properties of their own.
[WEB-2534]: https://tidepool.atlassian.net/browse/WEB-2534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2534] web worker error reporting

app/pages/share/ShareInvite.js, app/redux/reducers/misc.js, test/unit/pages/share/ShareInvite.test.js, test/unit/redux/reducers/clinics.test.js
Covers both [WEB-2572] and [WEB-2494]
Note that simply addressing [WEB-2494] would have prevented the scenario which caused [WEB-2572] to occur, but I decided it still made sense to address the 'hole' in our redux state logic that caused that issue, which was basically that the fetched clinic, which included fetched patients for that clinic as well, was being overwritten by the basic fetched clinic details when the clinic was searched for via the "Share code" field.
I've made it now so that the fetched clinic object is now merged with the existing to prevent a similar issue from conceivably happeing down the road.
[WEB-2572]: https://tidepool.atlassian.net/browse/WEB-2572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2494]: …
=> [WEB-2572,WEB-2494] Prevent inviting already-invited members or clinics

app/redux/utils/pendoMiddleware.js, package.json, test/unit/redux/utils/pendoMiddleware.test.js
See [WEB-2749] 
Basically, we were only setting `visitor.role` to `clinician` if the user had the legacy `clinic` role assigned.  It will now apply correctly for the `clinician` or `migrated_clinic` roles as well
[WEB-2749]: https://tidepool.atlassian.net/browse/WEB-2749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2749] Pendo clinician visitor role fix

app/core/clinicUtils.js, test/unit/app/core/clinicUtils.test.js
for [WEB-2847] tweaks logic to ensure that clinics with a hard limit but no start dates are assigned `base` tier
[WEB-2847]: https://tidepool.atlassian.net/browse/WEB-2847?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2847] no-date hard limit clinics assigned `base` 

app/pages/clinicworkspace/ClinicPatients.js, package.json, webpack.config.js
for [WEB-2784] - fixes issue with MRN edits clearing the selected patient information during the existing MRN patient search flow
also drops the `if`/`then` shell requirement from the `startLocal` command (which for whatever reason I ran into on zsh on macOS) and adds a filter for launchdarkly network problems showing up in dev overlays that I had to close on nearly every app interaction
[WEB-2784]: https://tidepool.atlassian.net/browse/WEB-2784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2784] fix mrn editing clearing patient information

app/components/elements/Dialog.js, package.json
[WEB-2874] [WEB-2887]
Basically, the z-index was set above the main content, even for closed/hidden dialogs, causing some UI elements to be unreachable by mouse events.
[WEB-2874]: https://tidepool.atlassian.net/browse/WEB-2874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2887]: https://tidepool.atlassian.net/browse/WEB-2887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2874,WEB-2887] Fix hidden dialog z-index issues

app/components/clinic/ClinicProfileFields.js, app/pages/clinicadmin/clinicadmin.js, package.json, test/unit/pages/clinicadmin.test.js
[WEB-2928]
[WEB-2928]: https://tidepool.atlassian.net/browse/WEB-2928?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2928] Ensure clinic details form is populated with latest clinic values when reopening after edit

app/components/clinic/WorkspaceSwitcher.js, app/pages/clinicdetails/clinicdetails.js, app/redux/reducers/working.js, test/unit/components/clinic/WorkspaceSwitcher.test.js
[WEB-2922]
Also, fixes a few other small issues I spotted:
1. The clinic create form would start pre-populated with the actively-selected clinic if set
2. The workspace switcher wasn't updating the clinic name upon edit
3. The Private Workspace option in the workspace switcher should show on the '/patients' page - otherwise, it's just a blank string with a downward caret beside it.
[WEB-2922]: https://tidepool.atlassian.net/browse/WEB-2922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2922] Fix clinic name in toast after creation

app/components/clinic/RpmReportConfigForm.js, app/components/elements/DateRangePicker.js, app/core/clinicUtils.js, app/themes/baseTheme.js, package.json
[WEB-2945] 
Basically, adjusts the date-blocking logic for the RPM date range UX, and also ignores the browser time zone, and treats all calendar dates as UTC, only converting to the requested time zone on submission, which fixes a few edge case issues that could affect selecting dates at the start of the range for certain time zones.
It also reduces the max days in past to 59 days from 60, since we only generate pop health stats on the backend for the past 60 days in UTC time, leaving some time zones with no data for up to 12 hours on the 60th day back.
[WEB-2945]: https://tidepool.atlassian.net/browse/WEB-2945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2945] RPM config form range selector tweaks

app/components/clinic/RpmReportConfigForm.js, package.json
[WEB-2939] 
Keeping the GMT offset to allow the backend to more accurately calculate the report accross DST changeovers, and produce a valid date count generally for timezones on the 'plus' side of UTC.
[WEB-2939]: https://tidepool.atlassian.net/browse/WEB-2939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2939] Keep gmt offset in RPM report date params

app/pages/clinicadmin/clinicadmin.js, package.json
[WEB-2932]
Issue was caused by an extra call to `setUserRolesInClinic` in back to back renders
[WEB-2932]: https://tidepool.atlassian.net/browse/WEB-2932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2932] Fix workspace admin page flicker

app/components/clinic/RpmReportConfigForm.js, package.json
Small tweak to requirements for [WEB-2945]
Allows any date within the past 59 days to be selected while start date selector is focused.
[WEB-2945]: https://tidepool.atlassian.net/browse/WEB-2945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2945] Allow any date within 59 days to be selected while start date selector is focused

app/components/clinic/RpmReportConfigForm.js, package.json
[WEB-2955] 
Had accidentally set it to 11:59:59.999 instead of 23:59:59.999
[WEB-2955]: https://tidepool.atlassian.net/browse/WEB-2955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2955] fix hardcoded rpm end time

app/components/clinic/RpmReportConfigForm.js, app/pages/clinicworkspace/ClinicPatients.js, app/redux/actions/async.js, package.json, test/unit/pages/ClinicPatients.test.js, webpack.config.js, yarn.lock
[WEB-2958] [WEB-2964]
While working on passing the relevant active patient filters to the RPM report endpoint, I noticed it wasn't sending them on initial load.  
This was due to a separate bug/regression [WEB-2964], that has been addressed here as well.
[WEB-2958]: https://tidepool.atlassian.net/browse/WEB-2958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-2964]: https://tidepool.atlassian.net/browse/WEB-2964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2958,WEB-2964] Send active patient filters to RPM report generation endpoint

app/components/clinic/RpmReportConfigForm.js, app/core/clinicUtils.js, app/pages/clinicworkspace/ClinicPatients.js, package.json, test/unit/app/core/clinicUtils.test.js
[WEB-2969]
There were a few timezone-related bugs that surfaced for users ahead of UTC time.  These were addressed in 2 main ways (I've added some comments to sections of code as I saw fit, but wanted to call them out here too):
1. I've set the global `moment` object to default to "UTC" whenever the rpm form modal is open.  It automatically resets to the default whenever the modal is closed, or the component unmounts.  [This issue](https://github.com/react-dates/react-dates/issues/1138#issuecomment-870240972) (among some others I found while debugging how to get `react-dates` to work with UTC internally) is one I came across earlier in development, and had hoped to avoid, but it's necessary to get this working as designed, and has the benefit of removing some workaround code cruft I had …
=> [WEB-2969,WEB-2974] Date range selection fix for certain time zones

app/core/clinicUtils.js, package.json
[WEB-2969]
One more small PR - I noticed this evening once ET went a day behind the UTC date that I had missed applying the utc date shift properly to some of the validation fields.
[WEB-2969]: https://tidepool.atlassian.net/browse/WEB-2969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2969] Apply utc day shifts to each report date check

app/pages/clinicworkspace/ClinicPatients.js, package.json
[WEB-2964]
The default sort was not being correctly set when navigating back to the patient list for clinics showing the summary table
[WEB-2964]: https://tidepool.atlassian.net/browse/WEB-2964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2964] Fix default sort on internal navigation

app/components/clinic/RpmReportConfigForm.js, package.json
[WEB-2995]
When I removed the `getCalendarDate` method to simplify the code in the previous PR, I missed wrapping this one check in `moment.utc` like I had with all other, and, more importantly, needed the precision set to `true`.
Technically, the `moment.utc` wrapping could be left out, since the global moment should default to UTC while the form is open, but I want it to be consistent with the others, and explicit that we're dealing exclusively with UTC when glancing at the code.
[WEB-2995]: https://tidepool.atlassian.net/browse/WEB-2995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2995] Fix day prior to start date not always being disabled

app/components/clinic/RpmReportConfigForm.js, package.json
[WEB-2995] Noticed that there was a similar intermittent error on the end date.
Also, resetting the form whenever the modal closes so it will automatically reset the default dates when it next opens (fixes a very remote UI edge case where a user can change timezone that allows a future date to be selected, then closes the modal, and reopens it in a non-future-date time zone).
[WEB-2995]: https://tidepool.atlassian.net/browse/WEB-2995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2995] Small tweak to blocked end date range when end date input is selected

.travis.yml, app/redux/utils/pendoMiddleware.js, package.json
for [WEB-2961] - tracked down the issue to a re-render loop that occurs when trying to fetch additional data during the PDF generation, since patientdata will presume that it re-renders during the PDF request (due to the store state changes throughout the process) and pick up on various states to continue the process. The synchronous setting of pendo data in the middleware after data fetch success will cause a re-render prior to the data success action returning, and during the new re-render, patientdata will try to initialize PDF generation again since it sees that new data has arrived, but hasn't been added to the data worker/processed. This process will loop. By just not setting the pendo data if it hasn't changed, we avoid the loop condition.
[WEB-2961]: …
=> [WEB-2961] Print range error fix

app/pages/clinicworkspace/ClinicPatients.js, package.json
[WEB-3055]
[WEB-3055]: https://tidepool.atlassian.net/browse/WEB-3055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3055] Limit tag column width on POP Health dashboard

app/pages/patientdata/patientdata.js, test/unit/pages/patientdata.test.js
I realized that one of the tests was broken due to firing the generate PDF success handler even if an error was thrown.  Also, the tests weren't always firing in the anticipated order which caused indeterminite results.
Once approved, I'll also back-merge this to `develop` so that we have it in a passing state
=> Only call generateAGPImagesSucces if no errors were thrown

app/core/utils.js, app/pages/patientdata/patientdata.js, package.json, test/unit/utils/utils.test.js
[WEB-2853]
New PR to address a change to the done criteria (bullet pt 2)
We want to use the timezone offset of the latest diabetes datum to determine the ideal timezone for display, and only use the latest upload timezone as a fallback for that.
[WEB-2853]: https://tidepool.atlassian.net/browse/WEB-2853?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2853] Use latest datum timezone offset to determine ideal timezone for display

app/pages/prescription/PrescriptionForm.js, app/pages/prescription/ScheduleForm.js, app/pages/prescription/prescriptionFormConstants.js, app/pages/prescription/prescriptionSchema.js, app/pages/prescription/reviewFormStep.js, app/pages/prescription/therapySettingsFormStep.js, package.json, test/unit/pages/prescription/PrescriptionForm.test.js, test/unit/pages/prescription/ScheduleForm.test.js, test/unit/pages/prescription/prescriptionFormConstants.test.js
[WEB-3022]
Implements the guardrails according to the ticket.
Other changes:
- Had to re-implement the time options for the ScheduleForm component as well, since the html5 time field no longer supports the 'step' prop as it had when this was originally developed.
- Also, made the time increment and max number of schedules configurable
- Fixed a navigation error when single-step editing from the review page
- Remove the `createdUserId` from the revision hash to account for a similar backend change.
[WEB-3022]: https://tidepool.atlassian.net/browse/WEB-3022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3022] Implement Palmtree guardrails

app/pages/patientdata/patientdata.js
To handle case in [WEB-3082] where the non-date-bounded data fetch for `settings` would be lost when using the Refresh button.
[WEB-3082]: https://tidepool.atlassian.net/browse/WEB-3082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3082] customize fetch options for settings refresh

app/core/utils.js, app/pages/patientdata/patientdata.js, app/pages/prescription/prescriptionSchema.js, package.json, test/unit/utils/utils.test.js, yarn.lock
[WEB-3251] Will go out as part of `1.81.1` hotfix
Moved the general logic for determining the ideal timezone based on data to the viz data worker.
Related PR: https://github.com/tidepool-org/viz/pull/415
[WEB-3251]: https://tidepool.atlassian.net/browse/WEB-3251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3251] Move latest time zone determination logic to data worker.

app/pages/prescription/PrescriptionForm.js, package.json
[WEB-3258]
[WEB-3258]: https://tidepool.atlassian.net/browse/WEB-3258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3258] Ensure accessCode is not used when generating revision hash

app/components/datasources/DataConnections.js, test/unit/components/datasources/DataConnections.test.js
[WEB-3439]
[WEB-3439]: https://tidepool.atlassian.net/browse/WEB-3439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3439] Remove "No Pending Connections" text from default data connection state UI

app/pages/oauth/OAuthConnection.js, package.json, test/unit/pages/OAuthConnection.test.js
[WEB-3460]
[WEB-3460]: https://tidepool.atlassian.net/browse/WEB-3460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3460] Use provider displayName in OAuth connection banners

package.json, yarn.lock
@krystophv , could you please verify I did the following things correctly?
- I merged my tideline PR to `develop`
- I merged the tideline `develop` branch into the tideline `release-1.31.0`
- I checked out the release candidate branch and bumped the `release-1.31.0` to `1.31.0-rc.2`
- On _my machine_, I modified the release branch's version from `1.31.0-rc.2` to `1.31.0-WEB-3399-underride-precision.1` and [published it to npm](https://www.npmjs.com/package/tideline/v/1.31.0-web-3399-underride-precision.1). I did not push this change to github, so there is no trace in the tideline repo about version `1.31.0-web-3399-underride-precision.1`
- I then created this PR to bump the tideline version to `1.31.0-web-3399-underride-precision.1` in devDependencies.
Thank you :)
=> WEB-3399 - Bump Tideline Version

app/pages/patientdata/patientdata.js, package.json, yarn.lock
Addresses [WEB-3465]
The issue was that Abbott sends a `cgmSettings` datum that is more recent than the latest `cbg` datum, causing it to default to the Basics view instead of the expected Trends.  I've pared down the list of datum types sent to `deriveChartTypeFromLatestData` to only those that are used to set the default view.
I've also pulled in this viz PR - which could have been handled separately, but it' one less blip PR this way (and I initally thought I'd be fixing this one by adding a device ID in the same section of viz code before I realized the actual issue):
https://github.com/tidepool-org/viz/pull/440
[WEB-3465]: https://tidepool.atlassian.net/browse/WEB-3465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3465] Set default chart type based only off of diabetes datums

app/redux/actions/async.js, package.json, yarn.lock
[WEB-3396] 
Filters out any cgm data that has a `sampleInterval` value less than 5 minutes
Related PR: https://github.com/tidepool-org/platform-client/pull/186
[WEB-3396]: https://tidepool.atlassian.net/browse/WEB-3396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3396] Send minimum sample interval parameter for data fetches

app/redux/utils/pendoMiddleware.js
I noticed that logging in to int was not registering in Pendo as the "INT" environment. It appears as if the "int-api" subdomain is missing from the environments defined in pendoMiddleware.js. Adding this URL should fix the issue.
=> Update pendoMiddleware.js to include missing subdomain of integration environment

app/components/datasources/DataConnections.js, package.json, test/unit/components/datasources/DataConnections.test.js
[WEB-3500]
The issue was that in cases where there were connections to multiple accounts for the same data source provider, the first one in the list of matching data sources was used.  Now, we order by modified time, so the latest matching data source that was interacted with gets chosen for display in the data connections UI
[WEB-3500]: https://tidepool.atlassian.net/browse/WEB-3500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3500] Abbott alternating accounts bugfix

app/pages/patientdata/patientdata.js, package.json
[WEB-3476] 
Fixes issue where a datetime query param in the integer timestamp format wasn't playing nice in `setInitialChartView`
[WEB-3476]: https://tidepool.atlassian.net/browse/WEB-3476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3476] Refresh leads to infinite loading when datetime query param is in integer timestamp format

app/components/chart/daily.js, app/pages/patientdata/patientdata.js, package.json, yarn.lock
[WEB-2960]
The failed tideling ref that was causing the JS error was dead code.  I've removed it, and some other message handling cruft that was hanging around in the daily view component.
I also noticed that the message preview tooltips weren't sanitized, so I have added the following PR to address that:
https://github.com/tidepool-org/tideline/pull/468 
[WEB-2960]: https://tidepool.atlassian.net/browse/WEB-2960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2960] Remove old message handling cruft.

app/components/datasources/DataConnections.js, package.json, test/unit/components/datasources/DataConnections.test.js
[WEB-3437]
Also includes some variable renaming I missed in the test file when switching from abbott to twiist.  Only the `getConnectStateUI` test update is relevant to this ticket.
[WEB-3437]: https://tidepool.atlassian.net/browse/WEB-3437?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3437] Ensure that the connected state correctly shows the last data time ago

app/components/datasources/DataConnections.js, package.json, test/unit/components/datasources/DataConnections.test.js, test/unit/pages/OAuthConnection.test.js
[WEB-3612]  Makes the lastImportTime check optional for data connection sources such as twiist where we won't have this set.
Also sets the displayName on the twiist data connection definition to lowercase, as it was incorrectly set to "Twiist"
[WEB-3612]: https://tidepool.atlassian.net/browse/WEB-3612?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3612] Show twiist as "Connected" instead of "Connecting"

app/providers/AppBanner/AppBannerProvider.js
[WEB-3582]
Basically, this particular banner was showing by default for a second or two while data was loading in as the 'show' criteria wasn't waiting until we had the data loaded in order to make the decision to show or not.
[WEB-3582]: https://tidepool.atlassian.net/browse/WEB-3582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3582] Prevent temporary display of uploader banner while initial data is loading

app/components/chart/bgLog.js, app/components/chart/daily.js, app/pages/patientdata/patientdata.js, package.json
[WEB-3663] 
A JS error was occurring due to various calls within the bgLog or daily data views for mobile users due to the chart not being initialized for mobile users, but lifecycle methods still calling various chart methods.  This was noticed by Dave when his production account, which had SMBG as the latest data, was loading the bgLog view by default and hitting the error state.
With this fixed, I noticed that we were still loading the bgLog view by default if the latest datum was an SMBG, so I've updated the default view to always be 'basics' for mobile users when not specified via a URL param.  This way, the user will see the full list of stats available on the basics view, instead of the SMBG-only stats shown on the BG Log view
[WEB-3663]: …
=> [WEB-3663] Fix JS error for mobile users when initial data view is bgLog or daily

app/pages/clinicworkspace/ClinicPatients.js, test/unit/pages/ClinicPatients.test.js
[WEB-3703]
[WEB-3703]: https://tidepool.atlassian.net/browse/WEB-3703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Here is each individual state:
No Filters
Filters + Search, No Matches
Filters, No Matches
Search, No Matches
Filters + Search with Matches
Search with Matches
Filters with Matches
=> WEB-3703 - Use custom copy when query is applied to patient list

app/pages/dashboard/PatientDrawer/MenuBar/CGMClipboardButton.js, test/unit/pages/dashboard/PatientDrawer/CGMStatistics/index.test.js, test/unit/pages/dashboard/PatientDrawer/MenuBar/CGMClipboardButton.test.js
[WEB-3707]
Looks like it was renamed recently in Viz. Because `sampleFrequency` is `undefined` here, the button thinks that data is insufficient even when it is not, so it disables itself
```js
const { count, sampleFrequency } = data?.data?.current?.stats?.sensorUsage || {};
const hoursOfCGMData = (count * sampleFrequency) / MS_IN_HOUR;
const isDataInsufficient = !hoursOfCGMData || hoursOfCGMData < 24;
```
[WEB-3707]: https://tidepool.atlassian.net/browse/WEB-3707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WEB-3707 - "Copy to Text" button is always disabled in TIDE Drawer

app/components/chart/trends.js, app/pages/patientdata/patientdata.less
[WEB-3758]
CSS positioning regression, likely from when I moved the container styles to the theme layer prior to our mobile work.
Just needed the items rendering within a relative-positioned chart area again.
[WEB-3758]: https://tidepool.atlassian.net/browse/WEB-3758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3758] Fix trends range label positions

app/bootstrap.js, app/components/chart/settings.js, app/components/datasources/DataConnections.js, app/components/datasources/DataConnectionsModal.js, app/pages/oauth/OAuthConnection.js, package.json, stories/DataConnection.stories.js, test/unit/components/chart/settings.test.js, test/unit/components/datasources/DataConnections.test.js, test/unit/components/datasources/DataConnectionsModal.test.js
[WEB-2826] 
This will likely only be needed for a few days when we enable Abbott by default for all users via [WEB-3835], but this pattern should allow us to soft-launch new providers in similar fashion down the line.
[WEB-2826]: https://tidepool.atlassian.net/browse/WEB-2826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3835]: https://tidepool.atlassian.net/browse/WEB-3835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-2826] Only enable Abbott data provider via an LD flag

__tests__/unit/app/pages/clinicworkspace/ClinicPatients.test.js, app/pages/clinicworkspace/ClinicPatients.js
[WEB-3570]
There is a regression due to the `id` not being sent when trying to update a clinic site
I'm absolutely confident it was working before. I think there may have been a backend change. The `siteId` is already in the URL, which is why it wasn't needed previously. However, the requirement to have the `id` in the payload matches the [PR Preview API doc](https://developer.tidepool.org/TidepoolApi/pr-preview/pr-159/#tag/Clinics/operation/UpdateSite), so we'll modify the frontend to meet the docs.
[WEB-3570]: https://tidepool.atlassian.net/browse/WEB-3570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> WEB-3570 - Fix Regression due to Site Id missing

app/pages/patientdata/patientdata.js, package.json, test/unit/pages/patientdata.test.js
[WEB-3757]
The primary issue was that the datetime query param could be outside of the range of the fetched data, and it was not properly handled post-refetch.  I ended up trying a few approaches, but decided that the best one was to remove the datetime param after refetch, which allowed the data view to simply fall back to the most recent data time, which is really what we want upon refresh.
I also noticed and fixed a secondary issue that was introduced with our device settings history update - namely that a refresh on the settings view only fetches the pump history.  I added a check within handleRouteChangeEvent to see if the settings view was previously refreshed, and we are now changing to one of the other data views.  In this case, I'm skipping the typical route switch handlers and …
=> [WEB-3757] Fix data refresh issues for BG Log

app/components/datasources/DataConnections.js, app/core/hooks.js, app/redux/utils/launchDarklyMiddleware.js, package.json, test/unit/app/core/hooks.test.js, test/unit/redux/utils/launchDarklyMiddleware.test.js
[WEB-3839]
It was deemed to be preferable to not send personal user IDs to LD in favor of allowing localStorage overrides in order to facilitate testing for personal user accounts prior to making the abbott provider feature globally accessible on prod. 
[WEB-3835]: https://tidepool.atlassian.net/browse/WEB-3835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[WEB-3839]: https://tidepool.atlassian.net/browse/WEB-3839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WEB-3839] Remove personal user ids from LaunchDarkly and add localStorage overrides

package.json, yarn.lock
for [WEB-3875] along with https://github.com/tidepool-org/viz/pull/525
This pull request updates the `DataUtil` utility to prioritize `originalFood` data when determining carbohydrate input for bolus calculations and adds corresponding test cases to ensure the functionality works as expected. This fixes a bug in WEB-3875, where later edits to the carb are displayed in connection with the bolus, even though the underlying dosing decision was based on the original carb value.
* In `src/utils/DataUtil.js`, modified the `carbInput` assignment to use `d.dosingDecision.originalFood?.nutrition?.carbohydrate?.net` as the primary source, falling back to `d.dosingDecision.food?.nutrition?.carbohydrate?.net` if `originalFood` is not present. This ensures the original carbohydrate value at the time …
=> [WEB-3875] Ensure that Original Carb Value is Displayed with Bolus (in tooltip) when Carb is Later Edited (hotfix) to master

__tests__/unit/app/pages/patient/DataDonationConsentDialog.test.js, app/pages/patient/DataDonationConsentDialog.js, app/pages/patient/DataDonationForm.js, package.json
[WEB-3771] Some tweaks for the consent flow consent dialog and form:
We needed to show different copy for the personal account + child patient scenario (was thought to be impossible in the original scope, but it can actually happen if the child account is started as a custodial one)
I had added copy for this, just in case there turned out to be a way, but it was previously just a copy of the personal account + youth flow.  
Bill and I went over this new scenario and agreed on what we need to show.  It should be single step, collecting the caregiver name, and  modifying the copy a bit.
The other change was a bug fix where I was showing the patient name instead of the caregiver name in the consent success message for the personal + youth scenario, and I needed to get the caregiverName from …
=> [WEB-3771] Informed consent flow tweaks
